(function(){
  const q=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#039;'}[m]));
  function year(){try{return typeof cur==='function'?cur():null}catch{return null}}
  function rows(){const y=year();if(!y)return[];const tasks=(Array.isArray(y.tasks)?y.tasks:[]).filter(x=>x?.source==='Desktop Bridge 자동감지'&&/^K-에듀파인/i.test(String(x.text||''))).map(x=>({kind:'task',title:x.text,due:x.due||'',done:!!x.done}));const projects=(Array.isArray(y.projects)?y.projects:[]).filter(x=>x?.source==='Desktop Bridge 자동감지'&&/^K-에듀파인/i.test(String(x.name||''))).map(x=>({kind:'project',title:x.name,due:x.due||'',done:String(x.status||'').includes('완료')}));return[...tasks,...projects]}
  function render38(){const card=q('#desktopBridge36');if(card&&!q('#kedufineLocal38'))card.insertAdjacentHTML('beforeend','<div id="kedufineLocal38" class="kedufine-local38"></div>');const box=q('#kedufineLocal38');if(box){const all=rows(),open=all.filter(x=>!x.done),docs=open.filter(x=>/공문함|행정업무/.test(x.title)),approvals=open.filter(x=>/결재/.test(x.title)),finance=open.filter(x=>/예산·지출/.test(x.title));box.innerHTML=`<div class="kedufine-local38-head"><div><span class="kicker">K-EDUFINE LOCAL ADAPTER · v0.38</span><b>K-에듀파인 업무 자동 집계</b></div><span class="pill ${open.length?'warn':''}">${open.length?`확인 ${open.length}건`:'대기 업무 없음'}</span></div><div class="kedufine-local38-grid"><div><b>${docs.length}</b><span>공문함</span></div><div><b>${approvals.length}</b><span>결재</span></div><div><b>${finance.length}</b><span>예산·지출</span></div><div><b>${open.length}</b><span>전체 확인</span></div></div>${open.length?'<div class="kedufine-local38-list">'+open.slice(0,4).map(x=>`<span>${esc(x.title)}${x.due?' · '+esc(x.due):''}</span>`).join('')+'</div>':'<div class="mini">K-에듀파인에서 정상적으로 내려받은 자료가 감시 폴더에 들어오면 공문함·결재·예산/지출 상태를 로컬에서 집계합니다.</div>'}`}
    const settings=q('#desktopSettings36');if(settings&&!q('#kedufineLocalPolicy38'))settings.insertAdjacentHTML('beforeend','<div id="kedufineLocalPolicy38" class="notice"><b>v0.38 K-에듀파인 Local Adapter:</b> 공문함·결재·예산/지출 내보내기 자료의 미처리·대기·반려·누락 건수만 집계합니다. 문서 본문, 결재 의견, 개인 이름, 원문 행은 Teacher OS로 전달하지 않습니다.</div>')
  }
  const previous=globalThis.render;if(typeof previous==='function')globalThis.render=function(){const r=previous.apply(this,arguments);setTimeout(render38,0);return r};
  setTimeout(render38,1000);setInterval(render38,120000);
})();
