(function(){
  const W=globalThis.TeacherOSWorkEntity39;if(!W)return;
  const q=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  let building=false,lastSig='';
  function year(){try{return typeof cur==='function'?cur():null}catch{return null}}
  function saveDirect(){try{localStorage.setItem(KEY,JSON.stringify(state));return true}catch{return false}}
  function signature(y){const arrays=['tasks','projects','assessments','calendarEvents'];return arrays.map(k=>(Array.isArray(y?.[k])?y[k]:[]).map(x=>`${x.id||x.externalKey||''}:${x.text||x.name||x.title||''}:${x.due||x.date||''}:${x.done||x.status||''}`).join('|')).join('||')}
  function rebuild(force=false){const y=year();if(!y||building)return[];const sig=signature(y);if(!force&&sig===lastSig&&Array.isArray(y.workEntities39))return y.workEntities39;building=true;try{const entities=W.build(y);y.workEntities39=entities;y.workEntities39UpdatedAt=new Date().toISOString();lastSig=sig;saveDirect();return entities}finally{building=false}}
  function sourceLabel(v){return({neis:'NEIS',kedufine:'K-에듀파인',gmail:'Gmail',drive:'Drive',google_calendar:'Google Calendar',calendar:'학사일정',assessment:'평가',project:'행정',task:'업무'})[v]||v}
  function dueText(v){if(!v)return'마감 미정';try{const today=new Date();today.setHours(0,0,0,0);const d=new Date(v+'T00:00:00');const n=Math.round((d-today)/86400000);return n===0?'오늘':n>0?`D-${n}`:`${Math.abs(n)}일 지남`}catch{return v}}
  function ensureUI(){const dash=q('#dashboardBody');if(dash&&!q('#workEntity39')){const anchor=q('#desktopBridge36')||q('#googleAutopilot34')||q('#workAgent33');const html=`<article id="workEntity39" class="card workentity39 spaced"><div class="workentity39-head"><div><span class="kicker">WORK ENTITY ENGINE · v0.39</span><h2>한 업무로 묶어서 보기</h2><p class="muted">NEIS · K-에듀파인 · Google · 기존 Teacher OS에서 같은 업무로 판단되는 항목을 보수적으로 연결합니다. 원본 기록은 삭제하거나 합쳐 쓰지 않습니다.</p></div><div id="workEntityStats39" class="workentity39-stats"></div></div><div id="workEntityList39" class="workentity39-list"></div></article>`;if(anchor)anchor.insertAdjacentHTML('afterend',html);else dash.insertAdjacentHTML('afterbegin',html)}}
  function render39(){ensureUI();const entities=rebuild(false),sum=W.summary(entities),stats=q('#workEntityStats39'),list=q('#workEntityList39');if(stats)stats.innerHTML=`<span><b>${sum.open}</b> 진행</span><span><b>${sum.multi}</b> 다중출처</span><span class="${sum.conflicts?'warn':''}"><b>${sum.conflicts}</b> 마감충돌</span>`;if(!list)return;const useful=entities.filter(x=>!x.completed&&(x.sourceCount>=2||x.dueConflict)).slice(0,8);if(!useful.length){list.innerHTML='<div class="workentity39-empty">서로 다른 시스템에서 같은 업무로 연결된 항목이 생기면 여기에 하나로 묶어 보여줍니다.</div>';return}list.innerHTML=useful.map(e=>`<div class="workentity39-row"><div class="grow"><div class="workentity39-title"><strong>${esc(e.title)}</strong>${e.dueConflict?'<span class="pill warn">마감 충돌</span>':''}</div><div class="mini">${esc(e.due||'마감 미정')} · ${esc(dueText(e.due))} · 원본 ${e.members.length}건</div><div class="workentity39-sources">${e.sourceKinds.map(x=>`<span>${esc(sourceLabel(x))}</span>`).join('')}</div></div><details><summary>연결 근거</summary>${e.members.map(m=>`<div class="workentity39-member"><b>${esc(sourceLabel(m.sourceKind))}</b><span>${esc(m.title)}</span><time>${esc(m.due||'')}</time></div>`).join('')}</details></div>`).join('')}
  const previous=globalThis.render;if(typeof previous==='function')globalThis.render=function(){const r=previous.apply(this,arguments);setTimeout(render39,0);return r};
  window.TeacherOSWorkEntityRuntime39={rebuild:()=>{lastSig='';const r=rebuild(true);render39();return r}};
  setTimeout(render39,1100);setInterval(()=>{lastSig='';render39()},180000);
})();
