(function(){
  const A=globalThis.TeacherOSAutonomous40;if(!A)return;
  const q=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#039;'}[m]));
  const AUDIT_KEY='myTeacherOS.autonomous40.audit.v1';let running=false,timer=null,lastPlan=null,lastApplied=0;
  function year(){try{return typeof cur==='function'?cur():null}catch{return null}}
  function save(){try{localStorage.setItem(KEY,JSON.stringify(state));return true}catch(e){console.error('v40 save',e);return false}}
  function json(key,fallback={}){try{return Object.assign({},fallback,JSON.parse(localStorage.getItem(key)||'{}'))}catch{return fallback}}
  function healthContext(y){const ds=json('myTeacherOS.desktop36.settings.v1'),dst=json('myTeacherOS.desktop36.state.v1'),ns=json('myTeacherOS.neis35.settings.v1'),gs=json('myTeacherOS.google34.settings.v1'),gst=json('myTeacherOS.google34.state.v1');return{desktopConfigured:!!ds.token,desktopConnected:!!dst.connected,neisConfigured:!!ns.apiKey,neisHealthy:!y?.neis35?.lastError,googleConfigured:!!gs.gatewayUrl,googleHealthy:!!gst.connected&&!gst.lastError}}
  function audit(event,message,extra){let a=[];try{a=JSON.parse(localStorage.getItem(AUDIT_KEY)||'[]');if(!Array.isArray(a))a=[]}catch{}a.push({at:new Date().toISOString(),event,message,extra:extra||{}});a=a.slice(-240);try{localStorage.setItem(AUDIT_KEY,JSON.stringify(a))}catch{}return a}
  function audits(){try{const a=JSON.parse(localStorage.getItem(AUDIT_KEY)||'[]');return Array.isArray(a)?a:[]}catch{return[]}}
  function ensureEntities(y){try{if(globalThis.TeacherOSWorkEntityRuntime39?.rebuild)return globalThis.TeacherOSWorkEntityRuntime39.rebuild();if(globalThis.TeacherOSWorkEntity39){y.workEntities39=globalThis.TeacherOSWorkEntity39.build(y);return y.workEntities39}}catch(e){console.warn('v40 entity rebuild',e)}return Array.isArray(y?.workEntities39)?y.workEntities39:[]}
  function run(autoApply=true){const y=year();if(!y||running)return lastPlan;running=true;try{ensureEntities(y);let plan=A.buildPlan(y,{...healthContext(y),now:new Date()});let added=0;if(autoApply){y.tasks=Array.isArray(y.tasks)?y.tasks:[];const c=A.safeTaskCandidates(plan,y.tasks,4);if(c.length){y.tasks.push(...c);added=c.length;lastApplied=added;save();audit('auto_apply',`오늘 우선업무 ${added}건을 안전한 로컬 할 일로 자동 생성했습니다.`,{keys:c.map(x=>x.agentKey)});ensureEntities(y);plan=A.buildPlan(y,{...healthContext(y),now:new Date()})}else lastApplied=0}lastPlan=plan;render40();return plan}finally{running=false}}
  function sourceText(a){if(a.dueConflict)return'마감 충돌 · 사람 확인';if(a.domain==='system')return'자동화 연결 상태';if(a.autoSafe)return'안전 작업 자동관리';return'사람 판단 필요'}
  function dueLabel(due){const n=A.dueDays(due,new Date());if(n===null)return'마감 미정';if(n<0)return`${Math.abs(n)}일 지남`;if(n===0)return'오늘 마감';return`D-${n}`}
  function ensureUI(){const dash=q('#dashboardBody');if(dash&&!q('#autonomous40')){const anchor=q('#workEntity39')||q('#desktopBridge36')||q('#workAgent33');const html=`<article id="autonomous40" class="card autonomous40 spaced"><div class="autonomous40-head"><div><span class="kicker">AUTONOMOUS TEACHER AGENT · v0.40</span><h2>오늘 해야 할 일을 먼저 판단합니다</h2><p class="muted">NEIS · K-에듀파인 · Google · Teacher OS 업무를 종합해 마감·충돌·누락·우선순위를 계산합니다. 안전한 로컬 작업만 자동 실행하고 외부 발송·결재·성적/학생부 확정은 자동 실행하지 않습니다.</p></div><div class="autonomous40-actions"><span class="autonomous40-mode">SAFE AUTO</span><button id="autonomousRun40" class="btn secondary tiny" type="button">다시 판단</button></div></div><div id="autonomousStats40" class="autonomous40-stats"></div><div id="autonomousFocus40" class="autonomous40-focus"></div><div id="autonomousAudit40" class="autonomous40-audit"></div></article>`;if(anchor)anchor.insertAdjacentHTML('beforebegin',html);else dash.insertAdjacentHTML('afterbegin',html);q('#autonomousRun40')?.addEventListener('click',()=>{audit('manual','사용자가 자율 판단 재실행을 요청했습니다.');run(true)})}}
  function render40(){ensureUI();const p=lastPlan,stats=q('#autonomousStats40'),focus=q('#autonomousFocus40'),log=q('#autonomousAudit40');if(!p){if(stats)stats.innerHTML='<div class="autonomous40-empty">업무 데이터를 준비하는 중입니다.</div>';return}const s=p.summary;if(stats)stats.innerHTML=`<div><b>${s.critical}</b><span>즉시 확인</span></div><div><b>${s.warning}</b><span>이번 주</span></div><div><b>${s.autoSafe}</b><span>안전 자동관리</span></div><div><b>${s.approvalOnly}</b><span>사람 확인</span></div><div><b>${s.conflicts}</b><span>마감 충돌</span></div><div><b>${lastApplied}</b><span>이번 자동생성</span></div>`;if(focus){const rows=(p.focus||[]).slice(0,7);focus.innerHTML=rows.length?`<div class="autonomous40-title"><b>오늘의 우선순위</b><span>점수가 높은 업무부터 자동 정렬</span></div>`+rows.map((a,i)=>`<div class="autonomous40-row ${esc(a.severity)}"><span class="rank">${i+1}</span><div class="grow"><strong>${esc(a.title)}</strong><div class="mini">${esc(dueLabel(a.due))} · ${esc(sourceText(a))}</div><p>${esc(a.reason)}</p><em>${esc(a.nextAction)}</em></div><span class="score">${a.score}</span></div>`).join(''):'<div class="autonomous40-empty">현재 즉시 처리할 우선업무가 없습니다.</div>'}if(log){const rows=audits().slice(-5).reverse();log.innerHTML=rows.length?`<div class="autonomous40-title"><b>자율 작업 기록</b><span>언제 무엇을 왜 했는지 로컬에 기록</span></div>`+rows.map(x=>`<div class="autonomous40-log"><time>${esc(formatWhen(x.at))}</time><span>${esc(x.message||x.event)}</span></div>`).join(''):''}}
  function formatWhen(v){try{return new Date(v).toLocaleString('ko-KR',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'})}catch{return String(v||'')}}
  function schedule(){if(timer)clearTimeout(timer);timer=setTimeout(()=>{run(true);schedule()},120000)}
  const prev=globalThis.render;if(typeof prev==='function')globalThis.render=function(){const r=prev.apply(this,arguments);setTimeout(()=>run(true),0);return r};
  document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')run(true)});window.addEventListener('online',()=>run(true));
  window.TeacherOSAutonomousRuntime40={run:()=>run(true),plan:()=>lastPlan,audit:()=>audits().slice()};
  setTimeout(()=>{ensureUI();run(true);schedule()},1500);
})();
