(function(){
  const V6=globalThis.TeacherOSCoreV6,C=globalThis.TeacherOSCore;
  if(!V6||!C)return;
  const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)];
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random().toString(16).slice(2);
  const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
  const BUILTINS=[
    {id:'lesson-auto-progress',name:'수업 종료 → 진도 자동갱신',icon:'◉',category:'수업',trigger:'수업기록 종료',desc:'실시간 수업 음성을 분석해 근거가 충분할 때 해당 반 진도와 다음 시작점을 자동 갱신합니다.',steps:['오늘 반·교시 확인','수업 음성 핵심내용 분석','신뢰도 확인','반별 진도 +1','다음 시작점 저장'],mode:'embedded'},
    {id:'assessment-countdown',name:'평가 역산 준비',icon:'✓',category:'평가',trigger:'데이터 변경 / OS 열기',desc:'평가일까지 반별 남은 수업 횟수를 계산하고 준비가 촉박한 반만 자동 할 일로 올립니다.',steps:['평가일 확인','반별 실제 수업 가능일 계산','3회 이하 반 탐지','중복 없이 준비 할 일 생성'],mode:'auto'},
    {id:'calendar-impact',name:'학사일정 수업영향 반영',icon:'▣',category:'수업',trigger:'학사일정 변경',desc:'휴업·체험학습·고사 등은 남은 수업 계산에서 자동 제외하고, 봉사·창체 등 일부 영향 일정은 점검 대상으로 표시합니다.',steps:['일정 범위 확인','수업 영향 판정','반별 수업 횟수 재계산','일부 영향 일정 경고'],mode:'auto'},
    {id:'grade3-pace',name:'3학년 조기완료 감시',icon:'↗',category:'진도',trigger:'진도/평가 변경',desc:'중학교 3학년은 입시 일정을 고려해 진도 지연과 평가 전 수업 부족을 우선 감지합니다.',steps:['3학년 반 추출','학년 평균 진도 비교','평가 전 남은 차시 확인','지연 반 자동 경고'],mode:'auto'},
    {id:'admin-deadline',name:'행정 마감 감시',icon:'☷',category:'행정',trigger:'행정업무 변경 / 매일',desc:'7일 안에 마감되는 행정업무를 오늘 할 일에 중복 없이 자동 올립니다.',steps:['마감일 정렬','7일 이내 필터','기존 할 일 중복 검사','자동 할 일 생성'],mode:'auto'},
    {id:'club-deadline',name:'동아리 일정 감시',icon:'♬',category:'동아리',trigger:'동아리 일정 변경',desc:'국제교류·밴드 자율동아리의 가까운 일정을 자동으로 오늘 할 일과 연결합니다.',steps:['동아리 일정 확인','7일 이내 일정 추출','중복 검사','자동 할 일 생성'],mode:'auto'},
    {id:'daily-brief',name:'오늘 자동 브리핑',icon:'⌂',category:'통합',trigger:'OS 열기 / 데이터 변경',desc:'학사일정·평가·진도·행정·동아리를 한 번에 점검해 오늘 놓치기 쉬운 항목을 요약합니다.',steps:['전체 데이터 스캔','긴급도 계산','중복 제거','오늘 브리핑 생성'],mode:'auto'}
  ];
  let running=false,lastSig='';
  function ensureState(){
    state.version=Math.max(Number(state.version)||0,10);
    state.teacherSkills=Array.isArray(state.teacherSkills)?state.teacherSkills:BUILTINS.map(x=>({id:x.id,enabled:true,lastRunAt:null,runCount:0,lastResult:''}));
    BUILTINS.forEach(b=>{if(!state.teacherSkills.some(s=>s.id===b.id))state.teacherSkills.push({id:b.id,enabled:true,lastRunAt:null,runCount:0,lastResult:''})});
    Object.values(state.years||{}).forEach(y=>{y.skillBrief=Array.isArray(y.skillBrief)?y.skillBrief:[];y.tasks=Array.isArray(y.tasks)?y.tasks:[]});
    localStorage.setItem(KEY,JSON.stringify(state));
  }
  function skillState(id){return state.teacherSkills.find(x=>x.id===id)}
  function targets(y){return V6.classTargets(y.timetable||[])}
  function addTask(y,key,text){if(y.tasks.some(t=>t.skillKey===key&&!t.done))return false;y.tasks.push({id:uid(),text,done:false,skillKey:key,createdAt:new Date().toISOString()});return true}
  function days(d){return C.dueDays(d)}
  function nearestRemaining(y,a,target){return V6.countClassTeachingSlots(y.timetable||[],y.calendarEvents||[],y.timetableExceptions||[],target,today(),a.due)}
  function runAssessment(y){let added=0;const notes=[];for(const a of (y.assessments||[])){if(!a.due||days(a.due)<0)continue;const ts=targets(y).filter(t=>!a.target||V6.scopeMatches(a.target,t));for(const t of ts){const n=nearestRemaining(y,a,t);if(n<=3){const key=`skill:assessment:${a.id}:${t}`;if(addTask(y,key,`${t} · ${a.name} 준비 (${a.due}, 남은 수업 약 ${n}회)`))added++;notes.push(`${t} ${a.name} ${n}회`)}}}return{added,notes}}
  function runCalendar(y){const notes=[];for(const ev of (y.calendarEvents||[])){const d=days(ev.date);if(d===null||d<0||d>21)continue;const impact=ev.impact&&ev.impact!=='auto'?ev.impact:V6.inferImpact(ev.title);if(impact==='partial')notes.push(`${ev.date} ${ev.title} · ${ev.scope||'전체'} 수업영향 확인`)}return{added:0,notes}}
  function runGrade3(y){if(y.schoolLevel!=='중학교')return{added:0,notes:[]};let added=0;const notes=[];const t3=targets(y).filter(t=>V6.gradeFromTarget(t)==='3');const stats=V6.paceStats(y.classProgress||{},t3);for(const s of stats){if(s.gap!=null&&s.gap<=-1.5){const key=`skill:g3pace:${s.target}:${Math.floor(s.lesson)}`;if(addTask(y,key,`${s.target} 진도 점검 · 3학년 평균보다 ${Math.abs(s.gap).toFixed(1)}차시 느림`))added++;notes.push(`${s.target} 진도 지연`)}}
    for(const a of (y.assessments||[])){if(!a.due||days(a.due)<0)continue;for(const t of t3.filter(t=>!a.target||V6.scopeMatches(a.target,t))){const n=nearestRemaining(y,a,t);if(n<=2){const key=`skill:g3eval:${a.id}:${t}`;if(addTask(y,key,`${t} ${a.name}까지 수업 약 ${n}회 · 3학년 일정 우선 조정`))added++;notes.push(`${t} 평가까지 ${n}회`)}}}return{added,notes}}
  function runDeadlines(y,kind){let added=0;const notes=[];const list=kind==='admin'?(y.projects||[]):(y.clubs||[]);for(const x of list){if(!x.due)continue;const d=days(x.due);if(d===null||d<0||d>7)continue;const key=`skill:${kind}:${x.id}:${x.due}`;const label=kind==='admin'?'행정':'동아리';if(addTask(y,key,`${label} · ${x.name} (${x.due}, ${d===0?'오늘':`D-${d}`})`))added++;notes.push(`${x.name} ${d===0?'오늘':`D-${d}`}`)}return{added,notes}}
  function buildBrief(y){const items=[];const upcoming=(typeof allUpcoming==='function'?allUpcoming(y):[]).slice(0,6);upcoming.forEach(x=>items.push(`${x.type} · ${x.title} · ${x.date}`));const partial=runCalendar(y).notes.slice(0,3);items.push(...partial);const stats=V6.paceStats(y.classProgress||{},targets(y)).filter(s=>s.gap!=null&&s.gap<=-1.5).slice(0,3);stats.forEach(s=>items.push(`진도 · ${s.target} 평균보다 ${Math.abs(s.gap).toFixed(1)}차시 느림`));return [...new Set(items)].slice(0,10)}
  function execute(id,y){if(!y)return{added:0,notes:[]};if(id==='assessment-countdown')return runAssessment(y);if(id==='calendar-impact')return runCalendar(y);if(id==='grade3-pace')return runGrade3(y);if(id==='admin-deadline')return runDeadlines(y,'admin');if(id==='club-deadline')return runDeadlines(y,'club');if(id==='daily-brief'){const notes=buildBrief(y);y.skillBrief=notes.map((text,i)=>({id:`brief-${today()}-${i}`,text,date:today()}));return{added:0,notes}};if(id==='lesson-auto-progress')return{added:0,notes:['수업기록 종료 시 v0.9 엔진에서 자동 실행']};return{added:0,notes:[]}}
  function runSkill(id,manual=false){const y=cur(),s=skillState(id);if(!y||!s||(!s.enabled&&!manual))return{added:0,notes:[]};const r=execute(id,y);s.lastRunAt=new Date().toISOString();s.runCount=(Number(s.runCount)||0)+1;s.lastResult=r.notes.length?r.notes.slice(0,3).join(' / '):(r.added?`${r.added}개 자동 처리`:'특이사항 없음');return r}
  function signature(y){if(!y)return'';return JSON.stringify({c:(y.calendarEvents||[]).map(x=>[x.id,x.date,x.title,x.scope,x.impact]),a:(y.assessments||[]).map(x=>[x.id,x.due,x.target]),p:(y.projects||[]).map(x=>[x.id,x.due]),cl:(y.clubs||[]).map(x=>[x.id,x.due]),pr:y.classProgress,ll:(y.lessonLogs||[]).length})}
  function runAutoSkills(force=false){if(running)return;const y=cur();if(!y)return;const sig=signature(y);if(!force&&sig===lastSig)return;lastSig=sig;running=true;let added=0;try{for(const b of BUILTINS){const s=skillState(b.id);if(s?.enabled&&b.mode==='auto'){const r=runSkill(b.id,false);added+=r.added||0}}localStorage.setItem(KEY,JSON.stringify(state));renderSkills(y);renderBrief(y);if(added&&typeof renderTasks==='function')renderTasks(y)}finally{running=false}}
  function ensureUI(){const nav=q('#nav');if(nav&&!nav.querySelector('[data-view="skills"]'))nav.querySelector('[data-view="lessonlog"]')?.insertAdjacentHTML('afterend','<button data-view="skills">✦ <span>Skills</span></button>');if(!q('#skills'))q('#assessment')?.insertAdjacentHTML('beforebegin',`<section id="skills" class="view"><div class="section-intro"><div><span class="kicker">TEACHER SKILLS</span><h2>교사 업무 Skill</h2><p class="muted">반복 업무 절차를 한 번 정의해 두고 Teacher OS가 상황에 맞춰 자동 실행합니다.</p></div><button class="btn primary" id="runAllSkills">전체 점검 실행</button></div><div class="notice"><b>자동화 원칙:</b> 일정 계산·진도 점검·마감 알림처럼 되돌릴 수 있는 작업만 자동 실행합니다. 학생 개인정보 처리, 평가 판정, 문서 제출·삭제 같은 고위험 작업은 자동 실행하지 않습니다.</div><div id="skillGrid" class="skill-grid spaced"></div></section>`);const dash=q('#dashboardBody');if(dash&&!q('#skillBriefCard'))dash.querySelector('.grid2')?.insertAdjacentHTML('beforebegin',`<article id="skillBriefCard" class="card spaced"><div class="head"><div><span class="kicker">SKILL BRIEF</span><h3>Teacher OS 자동 브리핑</h3></div><button class="btn secondary tiny" id="briefRefresh">지금 다시 점검</button></div><div id="skillBrief" class="skill-brief"></div></article>`);const foot=q('.side-foot');if(foot)foot.textContent='v0.10 · Teacher Skills 자동화 엔진'}
  function renderSkills(y){const box=q('#skillGrid');if(!box)return;box.innerHTML=BUILTINS.map(b=>{const s=skillState(b.id)||{};const on=s.enabled!==false;return `<article class="card skill-card"><div class="skill-head"><span class="skill-icon">${b.icon}</span><div class="grow"><span class="pill">${esc(b.category)}</span><h3>${esc(b.name)}</h3></div><label class="skill-toggle"><input type="checkbox" data-skill-toggle="${b.id}" ${on?'checked':''}><span>자동</span></label></div><p class="muted">${esc(b.desc)}</p><div class="skill-trigger"><b>트리거</b> ${esc(b.trigger)}</div><ol>${b.steps.map(x=>`<li>${esc(x)}</li>`).join('')}</ol><div class="skill-foot"><span class="mini">${s.lastRunAt?`최근 실행 ${new Date(s.lastRunAt).toLocaleString('ko-KR')} · ${s.runCount||0}회`:'아직 실행 전'}</span><button class="linkbtn" data-skill-run="${b.id}">지금 실행</button></div>${s.lastResult?`<div class="skill-result">${esc(s.lastResult)}</div>`:''}</article>`}).join('')}
  function renderBrief(y){const box=q('#skillBrief');if(!box)return;const a=y.skillBrief||[];box.innerHTML=a.length?a.map(x=>`<div class="brief-item">${esc(x.text)}</div>`).join(''):'<div class="empty">현재 자동 브리핑에서 특별히 표시할 항목이 없습니다.</div>'}
  const oldSwitch=switchView;switchView=function(id){oldSwitch(id);if(id==='skills'){qa('.view').forEach(x=>x.classList.toggle('active',x.id===id));qa('#nav button').forEach(x=>x.classList.toggle('active',x.dataset.view===id));q('#title').textContent='Skills'}};
  function bind(){q('#skillGrid').onclick=e=>{const b=e.target.closest('[data-skill-run]');if(!b)return;const r=runSkill(b.dataset.skillRun,true);localStorage.setItem(KEY,JSON.stringify(state));render();switchView('skills')};q('#skillGrid').onchange=e=>{const c=e.target.closest('[data-skill-toggle]');if(!c)return;const s=skillState(c.dataset.skillToggle);if(s){s.enabled=c.checked;localStorage.setItem(KEY,JSON.stringify(state));renderSkills(cur())}};q('#runAllSkills').onclick=()=>{runAutoSkills(true);render();switchView('skills')};q('#briefRefresh').onclick=()=>{runAutoSkills(true);render()}}
  const prevRender=render;render=function(){ensureState();prevRender();const y=cur();if(y){renderSkills(y);renderBrief(y);setTimeout(()=>runAutoSkills(false),0)}else{if(q('#skillGrid'))q('#skillGrid').innerHTML='<div class="empty">학년도를 먼저 만들어 주세요.</div>';if(q('#skillBrief'))q('#skillBrief').innerHTML=''}};
  ensureUI();ensureState();bind();render();
})();
