(function(){
  const D=globalThis.TeacherOSDesktopCore36;if(!D)return;
  const q=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  const SETTINGS_KEY='myTeacherOS.desktop36.settings.v1',STATE_KEY='myTeacherOS.desktop36.state.v1',AUDIT_KEY='myTeacherOS.desktop36.audit.v1';
  let busy=false,timer=null,lastSnapshot=null;
  function settings(){try{return Object.assign({endpoint:D.ENDPOINT,token:'',autoSync:true,minutes:2},JSON.parse(localStorage.getItem(SETTINGS_KEY)||'{}'))}catch{return{endpoint:D.ENDPOINT,token:'',autoSync:true,minutes:2}}}
  function writeSettings(v){localStorage.setItem(SETTINGS_KEY,JSON.stringify(v))}
  function readState(){try{return Object.assign({cursor:0,lastSyncAt:'',connected:false,lastError:''},JSON.parse(localStorage.getItem(STATE_KEY)||'{}'))}catch{return{cursor:0,lastSyncAt:'',connected:false,lastError:''}}}
  function writeState(v){localStorage.setItem(STATE_KEY,JSON.stringify(v))}
  function currentYear(){try{return typeof cur==='function'?cur():null}catch{return null}}
  function saveBase(){try{localStorage.setItem(KEY,JSON.stringify(state));return true}catch{return false}}
  function audit(event,message,extra){let a=[];try{a=JSON.parse(localStorage.getItem(AUDIT_KEY)||'[]');if(!Array.isArray(a))a=[]}catch{}a.push({at:new Date().toISOString(),event,message,extra:extra||{}});a=a.slice(-200);try{localStorage.setItem(AUDIT_KEY,JSON.stringify(a))}catch{}return a}
  function audits(){try{const a=JSON.parse(localStorage.getItem(AUDIT_KEY)||'[]');return Array.isArray(a)?a:[]}catch{return[]}}
  function setStatus(text,kind='pending'){const el=q('#desktopStatus36');if(el){el.textContent=text;el.className='desktop36-status '+kind}}
  function masked(v){const s=String(v||'');return s?`${s.slice(0,4)}••••${s.slice(-4)}`:'미설정'}

  function ensureUI(){
    const dash=q('#dashboardBody');if(dash&&!q('#desktopBridge36')){
      const anchor=q('#neisOfficial35')||q('#googleAutopilot34')||q('#workAgent33');
      const html=`<article id="desktopBridge36" class="card desktop36 spaced"><div class="desktop36-head"><div><span class="kicker">LOCAL BRIDGE · v0.36</span><h2>NEIS · K-에듀파인 자료 자동감지</h2><p class="muted">PC의 Teacher OS Inbox와 다운로드 폴더를 로컬에서 감시합니다. 원문은 PC 밖으로 보내지 않고 업무 종류·마감 같은 파생 정보만 Teacher OS에 반영합니다.</p></div><div class="desktop36-actions"><span id="desktopStatus36" class="desktop36-status pending">로컬 에이전트 확인 중</span><button class="btn secondary tiny" id="desktopSync36" type="button">지금 확인</button></div></div><div id="desktopSummary36" class="desktop36-summary"></div><div id="desktopAudit36" class="desktop36-audit"></div></article>`;
      if(anchor)anchor.insertAdjacentHTML('afterend',html);else dash.insertAdjacentHTML('afterbegin',html);
      q('#desktopSync36')?.addEventListener('click',()=>syncNow(true));
    }
    const view=q('#settings');if(view&&!q('#desktopSettings36')){
      const panel=`<article id="desktopSettings36" class="card desktop36-settings spaced"><div class="head"><div><span class="kicker">TEACHER OS DESKTOP BRIDGE</span><h3>로컬 자동화 연결</h3><p class="muted">한 번 설치·페어링하면 문서를 다시 업로드할 필요가 없습니다. Bridge는 127.0.0.1에서만 실행되고 원문을 외부로 전송하지 않습니다.</p></div></div><label class="desktop36-label">기기 페어링 토큰<input id="desktopToken36" class="field" type="password" autocomplete="off" placeholder="Desktop Bridge 실행 화면의 pairing token"></label><div class="desktop36-toggle"><label><input id="desktopAuto36" type="checkbox"> 사이트 열려 있을 때 자동 반영</label><span id="desktopTokenState36" class="mini"></span></div><div class="quick"><button class="btn primary" id="desktopSave36" type="button">페어링 저장</button><button class="btn secondary" id="desktopRescan36" type="button">폴더 다시 검사</button><a class="btn secondary" href="https://github.com/puzzlex5/my-teacher-os/tree/main/local_bridge" target="_blank" rel="noopener">설치 안내</a></div><div class="notice spaced"><b>개인정보 경계:</b> PDF/HWP/HWPX/XLSX/CSV 원문은 로컬에서만 처리합니다. Teacher OS에는 파일명 기반 업무제목, 업무분류, 마감일, 신뢰도 등 최소 파생정보만 전달합니다.</div></article>`;
      const anchor=q('#neisSettings35')||q('#googleSettings34')||view.querySelector('.health-grid');if(anchor)anchor.insertAdjacentHTML('afterend',panel);else view.insertAdjacentHTML('afterbegin',panel);
      q('#desktopSave36')?.addEventListener('click',()=>{const token=String(q('#desktopToken36')?.value||'').trim();if(!D.validToken(token)){setStatus('페어링 토큰 형식 확인','warn');return}const s=settings();s.endpoint=D.ENDPOINT;s.token=token;s.autoSync=!!q('#desktopAuto36')?.checked;writeSettings(s);writeState({...readState(),cursor:0,connected:false,lastError:''});q('#desktopToken36').value='';audit('config','Desktop Bridge 페어링을 저장했습니다.');renderSettings();syncNow(true);schedule()});
      q('#desktopAuto36')?.addEventListener('change',e=>{const s=settings();s.autoSync=!!e.target.checked;writeSettings(s);renderSettings();schedule()});
      q('#desktopRescan36')?.addEventListener('click',()=>rescan());
    }
    renderSettings();
  }
  function renderSettings(){const s=settings();const a=q('#desktopAuto36'),t=q('#desktopTokenState36');if(a)a.checked=!!s.autoSync;if(t)t.textContent=`페어링 ${masked(s.token)} · ${s.minutes}분 반영`;}
  async function call(path,opt={}){const s=settings(),endpoint=D.normalizeEndpoint(s.endpoint||D.ENDPOINT);if(!endpoint)throw new Error('로컬 Bridge 주소 오류');const headers=Object.assign({'Cache-Control':'no-store'},opt.headers||{});if(path!=='/v1/health'){if(!D.validToken(s.token))throw new Error('Desktop Bridge 페어링이 필요합니다.');headers['X-Teacher-OS-Token']=s.token}const r=await fetch(endpoint+path,{...opt,headers,cache:'no-store',referrerPolicy:'no-referrer'});if(!r.ok){let msg=`HTTP ${r.status}`;try{const e=await r.json();msg=e.error||msg}catch{}throw new Error(msg)}return r.json()}
  async function health(){return call('/v1/health')}
  async function fetchPages(cursor){let c=Number(cursor||0),all=[],last=null;for(let i=0;i<5;i++){const snap=await call('/v1/snapshot?cursor='+encodeURIComponent(c));last=snap;all.push(...(snap.items||[]));c=Number(snap.cursor||c);if(!snap.hasMore)break}return Object.assign({},last||{},{items:all,cursor:c,hasMore:!!last?.hasMore})}
  async function rescan(){try{setStatus('폴더 다시 검사 중…','pending');await call('/v1/rescan',{method:'POST'});await syncNow(true)}catch(e){setStatus('로컬 재검사 실패','fail');audit('failure','Desktop Bridge 재검사 실패',{error:String(e.message||e)})}}
  async function syncNow(manual=false){if(busy)return;ensureUI();busy=true;const btn=q('#desktopSync36');if(btn)btn.disabled=true;try{await health();const st=readState(),snap=await fetchPages(st.cursor),y=currentYear();lastSnapshot=snap;let result={applied:0,byType:{}};if(y){const changes=D.plan(y,snap);result=D.apply(y,changes);if(result.applied){saveBase();audit('auto_apply',`로컬 문서 업무 ${result.applied}건을 자동 반영했습니다.`,result.byType);if(typeof globalThis.render==='function')try{globalThis.render()}catch{}if(typeof globalThis.TeacherOSAgent33?.run==='function')setTimeout(()=>globalThis.TeacherOSAgent33.run(false),0)}}writeState({...st,cursor:Number(snap.cursor||st.cursor||0),lastSyncAt:new Date().toISOString(),connected:true,lastError:''});renderSnapshot(snap,result);setStatus(snap.hasMore?'대량 문서 다음 동기화 계속':'Desktop Bridge 정상','ok');if(manual)audit('sync','Desktop Bridge 수동 확인 완료',{received:(snap.items||[]).length,applied:result.applied})}
    catch(e){const msg=String(e?.message||e);writeState({...readState(),connected:false,lastError:msg});renderSnapshot(lastSnapshot);setStatus(msg.includes('페어링')||msg.includes('not_authorized')?'로컬 에이전트 페어링 필요':'Desktop Bridge 실행 필요','warn');if(manual)audit('failure','Desktop Bridge 연결 실패',{error:msg})}finally{busy=false;if(btn)btn.disabled=false;schedule()}}
  function renderSnapshot(snap,result){ensureUI();const sum=q('#desktopSummary36'),log=q('#desktopAudit36'),st=readState(),s=settings();if(sum){if(!snap){sum.innerHTML=`<div class="desktop36-empty">${D.validToken(s.token)?'PC에서 Desktop Bridge가 실행되면 새 문서를 자동 감지합니다.':'Desktop Bridge를 한 번 설치하고 페어링 토큰을 저장하세요.'}</div>`}else{const x=D.summarize(snap);sum.innerHTML=`<div><b>${x.total}</b><span>이번 감지</span></div><div><b>${x.admin}</b><span>행정</span></div><div><b>${x.assessment}</b><span>평가</span></div><div><b>${x.schedule}</b><span>일정</span></div><div><b>${x.student_record}</b><span>학생부</span></div><div><b>${Number(result?.applied||0)}</b><span>자동 반영</span></div>`}}if(log){const server=(snap?.audit||[]).slice(-5),local=audits().slice(-4),rows=[...server.map(x=>({...x,scope:'PC'})),...local.map(x=>({...x,scope:'Teacher OS'}))].sort((a,b)=>String(b.at).localeCompare(String(a.at))).slice(0,7);log.innerHTML=rows.length?`<div class="desktop36-section-title"><b>로컬 자동화 기록</b><span>원문 내용은 기록하지 않습니다.</span></div>`+rows.map(x=>`<div class="desktop36-log"><time>${esc(formatWhen(x.at))}</time><span>${esc(x.message||x.event||'자동화')}</span><em>${esc(x.scope)}</em></div>`).join(''):''}renderSettings()}
  function formatWhen(v){try{return new Date(v).toLocaleString('ko-KR',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'})}catch{return String(v||'')}}
  function schedule(){if(timer)clearTimeout(timer);const s=settings();if(!s.autoSync||!D.validToken(s.token))return;timer=setTimeout(()=>syncNow(false),Math.max(1,Number(s.minutes)||2)*60*1000)}
  const prev=globalThis.render;if(typeof prev==='function')globalThis.render=function(){const r=prev.apply(this,arguments);setTimeout(()=>{ensureUI();renderSnapshot(lastSnapshot)},0);return r};
  document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')syncNow(false)});window.addEventListener('online',()=>syncNow(false));
  setTimeout(async()=>{ensureUI();try{await health();if(D.validToken(settings().token))syncNow(false);else setStatus('Desktop Bridge 페어링 필요','warn')}catch{setStatus('Desktop Bridge 실행 필요','warn')}schedule()},700);
})();
