const KEY='myTeacherOS.v01';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],arr=v=>Array.isArray(v)?v:[];
const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random().toString(16).slice(2);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const fresh=()=>({version:3,currentYear:null,profile:{major:'음악',minutes:45,style:''},years:{}});
let state=(()=>{try{return JSON.parse(localStorage.getItem(KEY))||fresh()}catch{return fresh()}})();
let suggestions=[];
function defaultClubs(){return[{id:uid(),name:'국제교류 자율동아리',type:'국제교류',goal:'국제교류 활동 운영',due:'',activities:[]},{id:uid(),name:'밴드 자율동아리',type:'밴드',goal:'합주와 공연 운영',due:'',activities:[]}]}
function migrate(){state=state&&typeof state==='object'?state:fresh();state.version=3;state.years=state.years||{};Object.values(state.years).forEach(y=>{y.projects=arr(y.projects);y.assessments=arr(y.assessments);y.memories=arr(y.memories);y.tasks=arr(y.tasks);y.attachments=arr(y.attachments);y.clubs=arr(y.clubs);if(!y.clubs.length)y.clubs=defaultClubs();y.calendarEvents=arr(y.calendarEvents);y.imports=arr(y.imports)});localStorage.setItem(KEY,JSON.stringify(state))}
function cur(){return state.currentYear?state.years[state.currentYear]:null}
function yearObj(n,l='중학교',s=''){return{year:Number(n),schoolLevel:l,schoolName:s,subjects:[],grades:[],homeroom:'',projects:[],clubs:defaultClubs(),assessments:[],memories:[],tasks:[],attachments:[],calendarEvents:[],imports:[]}}
function save(){localStorage.setItem(KEY,JSON.stringify(state));render()}
function dueDays(d){if(!d)return null;const t=new Date(d+'T00:00:00'),n=new Date();n.setHours(0,0,0,0);return Math.ceil((t-n)/86400000)}
function dueText(d){const n=dueDays(d);if(n===null)return'';if(n===0)return'오늘';return n>0?`D-${n}`:`${Math.abs(n)}일 지남`}
function switchView(id){$$('.view').forEach(x=>x.classList.toggle('active',x.id===id));$$('#nav button').forEach(x=>x.classList.toggle('active',x.dataset.view===id));$('#title').textContent=({dashboard:'오늘',importer:'자동세팅',calendar:'학사일정',assessment:'수업·평가',clubs:'동아리',projects:'행정업무',documents:'자료함',memory:'업무기억'})[id]||id}
function openDlg(id){$(id).showModal()}function closeDlgs(){$$('dialog[open]').forEach(d=>d.close())}
function ensureYear(){if(cur())return true;openYear();return false}
function openYear(){const y=cur();$('#yYear').value=y?.year||new Date().getFullYear();$('#yLevel').value=y?.schoolLevel||'중학교';$('#ySchool').value=y?.schoolName||'';$('#ySubjects').value=arr(y?.subjects).join(', ');$('#yHome').value=y?.homeroom||'';openDlg('#yearDlg')}
function render(){const y=cur(),years=Object.keys(state.years).sort((a,b)=>b-a);$('#yearSelect').innerHTML=years.length?years.map(k=>`<option value="${k}" ${String(state.currentYear)===String(k)?'selected':''}>${k}학년도</option>`).join(''):'<option>학년도 없음</option>';$('#firstHero').hidden=!!y;$('#dashboardBody').style.display=y?'block':'none';if(!y){['nextList','calendarList','assItems','clubGrid','projectGrid','sourceList','memoryList'].forEach(id=>$('#'+id).innerHTML='<div class="empty">학년도를 먼저 만들어 주세요.</div>');return}y.calendarEvents=arr(y.calendarEvents);y.assessments=arr(y.assessments);y.projects=arr(y.projects);y.clubs=arr(y.clubs);y.tasks=arr(y.tasks);y.imports=arr(y.imports);y.memories=arr(y.memories);$('#mEnv').textContent=[y.schoolLevel,y.schoolName].filter(Boolean).join(' · ')||'-';$('#mCal').textContent=y.calendarEvents.length+'개';$('#mAss').textContent=y.assessments.length+'개';$('#mClub').textContent=y.clubs.length+'개';$('#mProj').textContent=y.projects.length+'개';renderNext(y);renderCalendar(y);renderAssess(y);renderClubs(y);renderProjects(y);renderSources(y);renderMemory(y);renderTasks(y)}
function allUpcoming(y){let a=[];y.calendarEvents.forEach(e=>a.push({date:e.date,title:e.title,type:e.type||'학교'}));y.assessments.forEach(e=>e.due&&a.push({date:e.due,title:e.name,type:'평가'}));y.projects.forEach(e=>e.due&&a.push({date:e.due,title:e.name,type:'행정'}));y.clubs.forEach(e=>e.due&&a.push({date:e.due,title:e.name,type:'동아리'}));return a.filter(x=>x.date&&dueDays(x.date)>=0).sort((a,b)=>a.date.localeCompare(b.date))}
function renderNext(y){const a=allUpcoming(y).slice(0,8);$('#nextList').innerHTML=a.length?a.map(x=>`<div class="row"><div class="calendar-date">${esc(x.date)}</div><div class="grow"><strong>${esc(x.title)}</strong><div class="mini">${esc(x.type)} · ${dueText(x.date)}</div></div></div>`).join(''):'<div class="empty">다가오는 일정이 없습니다.</div>'}
function renderCalendar(y){const a=y.calendarEvents.slice().sort((a,b)=>(a.date||'').localeCompare(b.date||''));$('#calendarList').innerHTML=a.length?a.map(e=>`<div class="row"><div class="calendar-date">${esc(e.date)}</div><div class="grow"><strong>${esc(e.title)}</strong><div class="mini">${esc(e.type||'학교')} · <span class="source">${esc(e.source||'직접')}</span></div></div><button class="linkbtn danger-text" data-cal-del="${e.id}">삭제</button></div>`).join(''):'<div class="empty">자동세팅에서 학사일정 파일을 올리세요.</div>'}
function renderAssess(y){$('#assItems').innerHTML=y.assessments.length?y.assessments.map(a=>`<div class="row"><div class="grow"><strong>${esc(a.name)}</strong><div class="mini">${esc(a.target||'')} ${a.weight?'· '+esc(a.weight):''} ${a.due?'· '+esc(a.due):''}</div><div class="source">${esc(a.source||'')}</div></div><button class="linkbtn danger-text" data-ass-del="${a.id}">삭제</button></div>`).join(''):'<div class="empty">평가계획서를 자동세팅에서 올리세요.</div>'}
function renderClubs(y){$('#clubGrid').innerHTML=y.clubs.map(c=>`<article class="card project"><span class="pill blue">${c.type==='국제교류'?'🌏':'🎸'} ${esc(c.type)}</span><h3>${esc(c.name)}</h3><p class="muted">${esc(c.goal||'')}</p><div class="mini due">${c.due?esc(c.due)+' · '+dueText(c.due):'다음 일정 미정'}</div></article>`).join('')}
function renderProjects(y){$('#projectGrid').innerHTML=y.projects.length?y.projects.map(p=>`<article class="card project"><span class="pill">행정</span><h3>${esc(p.name)}</h3><p class="muted">${esc(p.desc||'')}</p><div class="mini due">${p.due?esc(p.due)+' · '+dueText(p.due):'마감 미정'}</div><div class="source">${esc(p.source||'')}</div></article>`).join(''):'<div class="empty">업무분장표나 공문을 자동세팅에서 올리세요.</div>'}
function renderSources(y){$('#sourceList').innerHTML=y.imports.length?y.imports.slice().reverse().map(f=>`<div class="row"><div class="grow"><strong>${esc(f.name)}</strong><div class="mini">${esc(f.kind)} · ${esc(f.when||'')}</div></div></div>`).join(''):'<div class="empty">분석한 원본 자료가 없습니다.</div>'}
function renderMemory(y){$('#memoryList').innerHTML=y.memories.length?y.memories.slice().reverse().map(m=>`<div class="row"><div class="grow"><strong>${esc(m.note)}</strong><div class="mini">다음: ${esc(m.improve||'')}</div></div></div>`).join(''):'<div class="empty">업무기억이 없습니다.</div>'}
function renderTasks(y){$('#taskList').innerHTML=y.tasks.length?y.tasks.map(t=>`<div class="row task ${t.done?'done':''}"><input type="checkbox" data-task="${t.id}" ${t.done?'checked':''}><div class="grow">${esc(t.text)}</div><button class="linkbtn danger-text" data-task-del="${t.id}">삭제</button></div>`).join(''):'<div class="empty">문서에 없는 임시 할 일만 여기에 적으세요.</div>'}
function normDate(y,m,d){const yy=Number(y||cur()?.year||new Date().getFullYear()),mm=Number(m),dd=Number(d);if(!mm||!dd)return'';return `${yy}-${String(mm).padStart(2,'0')}-${String(dd).padStart(2,'0')}`}
function findDates(text){const out=[];const push=(date,idx,raw)=>{if(date&&!out.some(x=>x.date===date&&x.idx===idx))out.push({date,idx,raw})};let m;const regs=[/(20\d{2})[.\-/년\s]+(\d{1,2})[.\-/월\s]+(\d{1,2})일?/g,/(\d{1,2})월\s*(\d{1,2})일/g,/(\d{1,2})[./-](\d{1,2})(?!\d)/g];for(let r=0;r<regs.length;r++){const re=regs[r];while((m=re.exec(text))){if(r===0)push(normDate(m[1],m[2],m[3]),m.index,m[0]);else push(normDate(null,m[1],m[2]),m.index,m[0])}}return out.sort((a,b)=>a.idx-b.idx)}
function classify(line,hint='auto'){if(hint!=='auto')return hint;if(/평가|수행|지필|성취기준|반영비율|고사/.test(line))return'assessment';if(/업무분장|담당|제출|공문|기안|결재|보고|신청/.test(line))return'admin';return'calendar'}
function cleanTitle(line,raw){let t=line.replace(raw,' ').replace(/\s+/g,' ').trim();t=t.replace(/^[-–—•·\d.()\s]+/,'').trim();return t.slice(0,100)||'학교 일정'}
function textToSuggestions(text,source,hint='auto'){const lines=text.replace(/\r/g,'').split('\n').map(x=>x.trim()).filter(Boolean);const res=[];for(const line of lines){const ds=findDates(line);if(!ds.length)continue;for(const d of ds){const kind=classify(line,hint),title=cleanTitle(line,d.raw);res.push({id:uid(),checked:true,kind,date:d.date,title,source,raw:line})}}return dedupeSuggestions(res)}
function dedupeSuggestions(a){const seen=new Set();return a.filter(x=>{const k=[x.kind,x.date,x.title].join('|');if(seen.has(k))return false;seen.add(k);return true})}
async function fileText(file){const ext=file.name.split('.').pop().toLowerCase();if(['txt','csv','ics'].includes(ext))return await file.text();if(['xlsx','xls'].includes(ext)){const ab=await file.arrayBuffer();const wb=XLSX.read(ab,{type:'array',cellDates:false});return wb.SheetNames.map(n=>XLSX.utils.sheet_to_csv(wb.Sheets[n])).join('\n')}if(ext==='docx'){const ab=await file.arrayBuffer();const r=await mammoth.extractRawText({arrayBuffer:ab});return r.value}if(ext==='hwpx'){const zip=await JSZip.loadAsync(await file.arrayBuffer());const names=Object.keys(zip.files).filter(n=>/Contents\/section\d+\.xml$/i.test(n));let s='';for(const n of names)s+='\n'+(await zip.file(n).async('text')).replace(/<[^>]+>/g,' ');return s}if(ext==='pdf'){const pdfjs=await import('https://cdn.jsdelivr.net/npm/pdfjs-dist@4.8.69/build/pdf.min.mjs');pdfjs.GlobalWorkerOptions.workerSrc='https://cdn.jsdelivr.net/npm/pdfjs-dist@4.8.69/build/pdf.worker.min.mjs';const doc=await pdfjs.getDocument({data:new Uint8Array(await file.arrayBuffer())}).promise;let out='';for(let i=1;i<=doc.numPages;i++){const p=await doc.getPage(i),c=await p.getTextContent();out+='\n'+c.items.map(x=>x.str).join(' ')}return out}throw new Error('지원하지 않는 형식')}
function parseICS(text,source){const r=[];for(const block of text.split('BEGIN:VEVENT').slice(1)){const dt=(block.match(/DTSTART(?:;[^:]*)?:(\d{8})/)||[])[1],sum=(block.match(/SUMMARY:(.*)/)||[])[1];if(dt&&sum)r.push({id:uid(),checked:true,kind:'calendar',date:`${dt.slice(0,4)}-${dt.slice(4,6)}-${dt.slice(6,8)}`,title:sum.trim(),source,raw:sum.trim()})}return r}
function renderSuggestions(){if(!suggestions.length){$('#suggestions').innerHTML='<div class="empty">추출된 항목이 없습니다.</div>';return}$('#suggestions').innerHTML=suggestions.map(s=>`<label class="suggestion"><input type="checkbox" data-sg="${s.id}" ${s.checked?'checked':''}><span class="tag">${s.kind==='calendar'?'학사':s.kind==='assessment'?'평가':'행정'}</span><span class="sg-date">${esc(s.date||'')}</span><span class="sg-title"><b>${esc(s.title)}</b><div class="source">${esc(s.source)}</div></span></label>`).join('')}
async function analyzeFiles(){if(!ensureYear())return;const files=[...$('#importFiles').files];if(!files.length){alert('파일을 선택해 주세요.');return}const hint=$('#importHint').value;$('#importStatus').textContent='자료를 읽는 중...';let add=[];for(const f of files){try{const ext=f.name.split('.').pop().toLowerCase();const text=await fileText(f);const got=ext==='ics'?parseICS(text,f.name):textToSuggestions(text,f.name,hint);add.push(...got);cur().imports.push({id:uid(),name:f.name,kind:hint==='auto'?'자동판별':hint,when:new Date().toLocaleString('ko-KR')})}catch(e){add.push({id:uid(),checked:false,kind:'calendar',date:'',title:`${f.name} 분석 실패: ${e.message}`,source:f.name,raw:''})}}suggestions=dedupeSuggestions([...suggestions,...add]);$('#importStatus').textContent=`${files.length}개 파일에서 ${add.filter(x=>x.checked).length}개 후보를 찾았습니다.`;renderSuggestions();save()}
function applySuggestions(){const y=cur();if(!y)return;const sel=suggestions.filter(x=>x.checked&&x.date);for(const s of sel){if(s.kind==='calendar'){if(!y.calendarEvents.some(e=>e.date===s.date&&e.title===s.title))y.calendarEvents.push({id:uid(),date:s.date,title:s.title,type:'학교',source:s.source})}else if(s.kind==='assessment'){if(!y.assessments.some(e=>e.due===s.date&&e.name===s.title))y.assessments.push({id:uid(),name:s.title,target:'',weight:'',due:s.date,criteria:s.raw,source:s.source})}else if(s.kind==='admin'){if(!y.projects.some(e=>e.due===s.date&&e.name===s.title))y.projects.push({id:uid(),name:s.title,desc:s.raw,due:s.date,carry:false,source:s.source})}}suggestions=[];renderSuggestions();save();switchView('dashboard')}
function runAgent(){const y=cur();if(!y)return;const a=allUpcoming(y).filter(x=>dueDays(x.date)<=30).slice(0,12);const t=y.tasks.filter(x=>!x.done);$('#agentResult').innerHTML=[...a.map(x=>`• ${esc(x.type)} · ${esc(x.title)} — ${dueText(x.date)}`),...t.map(x=>`• 할 일 · ${esc(x.text)}`)].join('<br>')||'30일 안에 등록된 일정이나 미완료 할 일이 없습니다.'}
function simpleOpen(kind){$('#simpleKind').value=kind;$('#simpleTitle').textContent=kind==='club'?'동아리 추가':kind==='project'?'예외 업무 추가':'업무기억';$('#simpleName').value='';$('#simpleMemo').value='';$('#simpleDue').value='';openDlg('#simpleDlg')}
$('#today').textContent=new Intl.DateTimeFormat('ko-KR',{dateStyle:'full'}).format(new Date());migrate();render();
$('#nav').onclick=e=>{const b=e.target.closest('[data-view]');if(b)switchView(b.dataset.view)};$('#yearSelect').onchange=e=>{if(state.years[e.target.value]){state.currentYear=e.target.value;save()}};$('#newYear').onclick=openYear;$('#firstYear').onclick=openYear;$('#yearForm').onsubmit=e=>{e.preventDefault();const k=String($('#yYear').value),y=state.years[k]||yearObj(Number(k),$('#yLevel').value,$('#ySchool').value);y.year=Number(k);y.schoolLevel=$('#yLevel').value;y.schoolName=$('#ySchool').value.trim();y.subjects=$('#ySubjects').value.split(',').map(x=>x.trim()).filter(Boolean);y.homeroom=$('#yHome').value.trim();state.years[k]=y;state.currentYear=k;closeDlgs();save()};
$('#analyzeBtn').onclick=analyzeFiles;$('#applySuggestions').onclick=applySuggestions;$('#suggestions').onchange=e=>{const c=e.target.closest('[data-sg]');if(c){const s=suggestions.find(x=>x.id===c.dataset.sg);if(s)s.checked=c.checked}};
$('#manualCal').onclick=()=>ensureYear()&&openDlg('#calDlg');$('#calForm').onsubmit=e=>{e.preventDefault();cur().calendarEvents.push({id:uid(),date:$('#calDate').value,title:$('#calTitle').value.trim(),type:$('#calType').value,source:'직접 추가'});e.target.reset();closeDlgs();save()};$('#calendarList').onclick=e=>{const b=e.target.closest('[data-cal-del]');if(b){cur().calendarEvents=cur().calendarEvents.filter(x=>x.id!==b.dataset.calDel);save()}};
$('#taskAdd').onclick=()=>{if(!ensureYear())return;const v=$('#taskInput').value.trim();if(v){cur().tasks.push({id:uid(),text:v,done:false});$('#taskInput').value='';save()}};$('#taskList').onclick=e=>{const c=e.target.closest('[data-task]'),d=e.target.closest('[data-task-del]');if(c){const t=cur().tasks.find(x=>x.id===c.dataset.task);if(t){t.done=c.checked;save()}}if(d){cur().tasks=cur().tasks.filter(x=>x.id!==d.dataset.taskDel);save()}};$('#agentRun').onclick=runAgent;
$('#clubAdd').onclick=()=>ensureYear()&&simpleOpen('club');$('#projAdd').onclick=()=>ensureYear()&&simpleOpen('project');$('#memoryAdd').onclick=()=>ensureYear()&&simpleOpen('memory');$('#simpleForm').onsubmit=e=>{e.preventDefault();const k=$('#simpleKind').value,n=$('#simpleName').value.trim(),m=$('#simpleMemo').value.trim(),d=$('#simpleDue').value;if(k==='club')cur().clubs.push({id:uid(),name:n,type:'기타',goal:m,due:d,activities:[]});if(k==='project')cur().projects.push({id:uid(),name:n,desc:m,due:d,carry:false,source:'직접 추가'});if(k==='memory')cur().memories.push({id:uid(),note:n,improve:m,created:new Date().toISOString()});closeDlgs();save()};
$('#assItems').onclick=e=>{const b=e.target.closest('[data-ass-del]');if(b){cur().assessments=cur().assessments.filter(x=>x.id!==b.dataset.assDel);save()}};$$('[data-close]').forEach(b=>b.onclick=closeDlgs);