(function(){
  const D=globalThis.TeacherOSDocAI,C=globalThis.TeacherOSCore,V6=globalThis.TeacherOSCoreV6;
  if(!D||!C||typeof readTextFile!=='function'||typeof textSuggestions!=='function')return;
  const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)];
  const esc23=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  const id23=()=>crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random().toString(16).slice(2);
  const FEEDBACK_KEY='myTeacherOS.docClassifierFeedback.v1';
  const PADDLE_MODULE='https://cdn.jsdelivr.net/npm/@paddleocr/paddleocr-js@0.4.2/+esm';
  const TESSERACT_JS='https://cdn.jsdelivr.net/npm/tesseract.js@5.1.1/dist/tesseract.min.js';
  const PDFJS='https://cdn.jsdelivr.net/npm/pdfjs-dist@4.8.69/build/pdf.min.mjs';
  const PDFWORKER='https://cdn.jsdelivr.net/npm/pdfjs-dist@4.8.69/build/pdf.worker.min.mjs';
  let running23=false,batchReports23=[],paddlePromise23=null,tessWorker23=null,batchSeq23=0;

  const pad=n=>String(n).padStart(2,'0');
  const localDate=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
  function mondayOf23(input=new Date()){const d=new Date(input);d.setHours(0,0,0,0);d.setDate(d.getDate()-((d.getDay()+6)%7));return localDate(d)}
  function addDays23(date,n){const d=new Date(date+'T00:00:00');d.setDate(d.getDate()+n);return localDate(d)}
  function parseWeekStart23(text){const s=String(text||''),m=s.match(/(\d{2,4})\s*[.\/-]\s*(\d{1,2})\s*[.\/-]\s*(\d{1,2})\s*(?:~|～|-|부터)\s*(\d{2,4})?\s*[.\/-]?\s*(\d{1,2})?\s*[.\/-]?\s*(\d{1,2})?/);if(!m)return mondayOf23();let y=Number(m[1]);if(y<100)y+=2000;return mondayOf23(new Date(`${y}-${pad(m[2])}-${pad(m[3])}T00:00:00`))}
  function readFeedback23(){try{const x=JSON.parse(localStorage.getItem(FEEDBACK_KEY)||'{}');return x&&typeof x==='object'?x:{}}catch{return{}}}
  function feedbackFor23(name){return readFeedback23()[D.feedbackSignature(name)]||''}
  function saveFeedback23(name,classId){const all=readFeedback23(),sig=D.feedbackSignature(name);if(sig){all[sig]=classId;localStorage.setItem(FEEDBACK_KEY,JSON.stringify(all))}}
  function setStatus23(text){const el=q('#importStatus');if(el)el.innerHTML=text}
  function progress23(fileIndex,total,name,phase){setStatus23(`<b>${fileIndex}/${total}</b> · ${esc23(name)} · ${esc23(phase)}`)}
  function ext23(file){return String(file?.name||'').split('.').pop().toLowerCase()}

  async function hashFile23(file){const ab=await file.arrayBuffer(),dig=await crypto.subtle.digest('SHA-256',ab);return [...new Uint8Array(dig)].map(x=>x.toString(16).padStart(2,'0')).join('')}
  function derivedSourceCount23(y,source){if(!y||!source)return 0;return['calendarEvents','timetable','assessments','projects'].reduce((n,k)=>n+(Array.isArray(y[k])?y[k].filter(x=>x?.source===source).length:0),0)}
  function duplicateImport23(hash,y){return !!hash?(y?.imports||[]).find(x=>x.hash===hash&&x.status!=='ignored'&&x.status!=='superseded')||null:null}
  function isDuplicate23(hash,y){const prev=duplicateImport23(hash,y);if(!prev)return false;return derivedSourceCount23(y,prev.name)>0||Number(prev.appliedCount||0)>0}

  function boxFromPoly23(poly){const pts=Array.isArray(poly)?poly:[];const xs=[],ys=[];pts.forEach(p=>{if(Array.isArray(p)){xs.push(Number(p[0]));ys.push(Number(p[1]))}else if(p&&typeof p==='object'){xs.push(Number(p.x));ys.push(Number(p.y))}});if(!xs.length)return{left:0,top:0,width:0,height:0};const l=Math.min(...xs),r=Math.max(...xs),t=Math.min(...ys),b=Math.max(...ys);return{left:l,top:t,width:r-l,height:b-t}}
  function itemsText23(items){const list=(items||[]).filter(x=>x.text).map(x=>({...x,cx:x.left+x.width/2,cy:x.top+x.height/2}));if(!list.length)return'';const heights=list.map(x=>x.height).filter(Boolean).sort((a,b)=>a-b),med=heights[Math.floor(heights.length/2)]||18,tol=Math.max(5,med*.55),rows=[];list.sort((a,b)=>a.cy-b.cy||a.left-b.left).forEach(it=>{let row=rows.find(r=>Math.abs(r.y-it.cy)<=tol);if(!row){row={y:it.cy,items:[]};rows.push(row)}row.items.push(it);row.y=row.items.reduce((s,x)=>s+x.cy,0)/row.items.length});return rows.sort((a,b)=>a.y-b.y).map(r=>r.items.sort((a,b)=>a.left-b.left).map(x=>x.text).join(' ')).join('\n')}
  function layoutSignals23(items,text=''){const it=items||[],tokens=it.map(x=>String(x.text||'').replace(/\s/g,''));return{dayHeaders:new Set(tokens.filter(x=>/^[월화수목금](?:요일)?$/.test(x)).map(x=>x[0])).size,classCodes:tokens.filter(x=>/^[1-3]\d{2}$|^[1-3]-\d{1,2}$/.test(x)).length,periodMarkers:tokens.filter(x=>/^\d{1,2}교시$|^[1-9]$/.test(x)).length,textLength:String(text||'').length}}
  function ocrQuality23(r){return D.clamp((Number(r?.confidence)||0)*.6+D.textQuality(r?.text||'')*.4,0,1)}

  async function getPaddle23(){
    if(paddlePromise23)return paddlePromise23;
    paddlePromise23=(async()=>{const mod=await import(PADDLE_MODULE);if(!mod?.PaddleOCR?.create)throw new Error('PaddleOCR 브라우저 모듈을 불러오지 못했습니다.');return mod.PaddleOCR.create({lang:'korean',ocrVersion:'PP-OCRv5',ortOptions:{backend:'wasm'}})})();
    return paddlePromise23;
  }
  async function paddleRecognize23(input){
    const ocr=await getPaddle23(),out=await ocr.predict(input,{textRecScoreThresh:.3}),r=out?.[0];if(!r)throw new Error('PaddleOCR 결과가 없습니다.');
    const items=(r.items||[]).map(x=>{const b=boxFromPoly23(x.poly);return{text:String(x.text||'').trim(),score:Number(x.score)||0,...b}}).filter(x=>x.text);const confidence=items.length?items.reduce((s,x)=>s+x.score,0)/items.length:0,text=itemsText23(items)||items.map(x=>x.text).join('\n');return{text,confidence,items,engine:'PaddleOCR PP-OCRv5 Korean'}
  }
  async function loadTesseract23(){if(globalThis.Tesseract)return globalThis.Tesseract;await new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=TESSERACT_JS;s.onload=resolve;s.onerror=()=>reject(new Error('Tesseract 보조 OCR을 불러오지 못했습니다.'));document.head.appendChild(s)});return globalThis.Tesseract}
  async function getTess23(){if(tessWorker23)return tessWorker23;const T=await loadTesseract23();tessWorker23=await T.createWorker('kor+eng',1,{logger:m=>{if(m.status==='recognizing text'&&q('#importStatus'))q('#importStatus').textContent=`보조 OCR ${Math.round((m.progress||0)*100)}%`}});return tessWorker23}
  function tsvItems23(tsv){return String(tsv||'').split('\n').slice(1).map(line=>line.split('\t')).filter(a=>a.length>=12&&a[0]==='5'&&a[11]?.trim()).map(a=>({left:Number(a[6]),top:Number(a[7]),width:Number(a[8]),height:Number(a[9]),score:D.clamp(Number(a[10])/100,0,1),text:a.slice(11).join('\t').trim()}))}
  async function tesseractRecognize23(input){const w=await getTess23(),r=await w.recognize(input),items=tsvItems23(r.data.tsv),confidence=D.clamp(Number(r.data.confidence||0)/100,0,1),text=items.length?itemsText23(items):String(r.data.text||'');return{text,confidence,items,engine:'Tesseract Korean fallback'}}
  async function smartOCR23(input,label='이미지'){
    let p=null,t=null;setStatus23(`<b>${esc23(label)}</b> · 고정밀 한국어 OCR 모델 준비 중...`);
    try{p=await paddleRecognize23(input)}catch(e){console.warn('PaddleOCR fallback:',e)}
    if(p&&p.text.trim().length>=20&&ocrQuality23(p)>=.66)return p;
    try{t=await tesseractRecognize23(input)}catch(e){console.warn('Tesseract fallback failed:',e)}
    if(!p&&!t)throw new Error('OCR 엔진을 사용할 수 없습니다.');if(!p)return t;if(!t)return p;return ocrQuality23(t)>ocrQuality23(p)?t:p
  }
  async function closeTess23(){if(tessWorker23){try{await tessWorker23.terminate()}catch{}tessWorker23=null}}

  function pdfLayoutText23(items){const mapped=(items||[]).map(x=>({text:String(x.str||'').trim(),left:Number(x.transform?.[4]||0),top:-Number(x.transform?.[5]||0),width:Number(x.width||0),height:Math.max(8,Math.abs(Number(x.height||x.transform?.[0]||12))),score:1})).filter(x=>x.text);return itemsText23(mapped)}
  async function renderPDFPage23(page){let scale=1.8,viewport=page.getViewport({scale});const maxPixels=4800000;if(viewport.width*viewport.height>maxPixels){scale*=Math.sqrt(maxPixels/(viewport.width*viewport.height));viewport=page.getViewport({scale})}const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(viewport.width));canvas.height=Math.max(1,Math.round(viewport.height));const ctx=canvas.getContext('2d',{willReadFrequently:false});ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);await page.render({canvasContext:ctx,viewport}).promise;return canvas}
  async function extractPDF23(file){
    const pdfjs=await import(PDFJS);pdfjs.GlobalWorkerOptions.workerSrc=PDFWORKER;const doc=await pdfjs.getDocument({data:new Uint8Array(await file.arrayBuffer())}).promise;let parts=[],ocrPages=[],nativePages=0,ocrCount=0,ocrScores=[];
    for(let i=1;i<=doc.numPages;i++){setStatus23(`<b>${esc23(file.name)}</b> · PDF ${i}/${doc.numPages}쪽 구조 분석 중...`);const page=await doc.getPage(i),content=await page.getTextContent(),native=pdfLayoutText23(content.items),nativeQ=D.textQuality(native);if(native.replace(/\s/g,'').length>=70&&nativeQ>=.52){parts.push(`--- ${i}쪽 ---\n${native}`);nativePages++}else{const canvas=await renderPDFPage23(page),ocr=await smartOCR23(canvas,`${file.name} ${i}쪽`);parts.push(`--- ${i}쪽 OCR ---\n${ocr.text}`);ocrPages.push({page:i,...ocr});ocrScores.push(ocr.confidence);ocrCount++}}
    const method=ocrCount===0?'pdf-native-layout':nativePages===0?'pdf-ocr':'pdf-hybrid-layout+ocr',ocrConfidence=ocrScores.length?ocrScores.reduce((a,b)=>a+b,0)/ocrScores.length:null;return{text:parts.join('\n'),method,ocrConfidence,ocrPages,pageCount:doc.numPages,layout:layoutSignals23(ocrPages.flatMap(x=>x.items),parts.join('\n'))}
  }
  async function extractPPTX23(file){const zip=await JSZip.loadAsync(await file.arrayBuffer()),names=Object.keys(zip.files).filter(n=>/^ppt\/slides\/slide\d+\.xml$/i.test(n)).sort((a,b)=>Number((a.match(/slide(\d+)/i)||[])[1])-Number((b.match(/slide(\d+)/i)||[])[1]));const parts=[];for(const n of names){const xml=await zip.file(n).async('text'),doc=new DOMParser().parseFromString(xml,'application/xml'),texts=[...doc.getElementsByTagName('*')].filter(x=>x.localName==='t').map(x=>x.textContent||'').filter(Boolean);parts.push(texts.join(' '))}return{text:parts.join('\n'),method:'pptx-native',ocrConfidence:null,ocrPages:[],pageCount:names.length,layout:{}}
  }
  async function extractSmart23(file,y){
    const ext=ext23(file);if(['jpg','jpeg','png','webp','bmp'].includes(ext)){const o=await smartOCR23(file,file.name);return{text:o.text,method:`image-ocr:${o.engine}`,ocrConfidence:o.confidence,ocrPages:[{page:1,...o}],pageCount:1,layout:layoutSignals23(o.items,o.text),rows:[]}}
    if(ext==='pdf')return{...(await extractPDF23(file)),rows:[]};
    if(ext==='pptx')return{...(await extractPPTX23(file)),rows:[]};
    const text=await readTextFile(file),rows=await spreadsheetRows(file),method=['xlsx','xls','csv'].includes(ext)?'spreadsheet-native':ext==='ics'?'ics-native':ext==='docx'?'docx-native':ext==='hwp'?'hwp-native':ext==='hwpx'?'hwpx-native':'native-text';
    const tt=rows.length?C.parseTimetableGrid(rows,(y?.subjects||['음악'])[0]||'음악'):[];return{text,method,ocrConfidence:null,ocrPages:[],pageCount:1,rows,layout:{tableRows:rows.length,timetableSlots:tt.length}}
  }

  function cluster23(nums,threshold=28){const a=[...nums].filter(Number.isFinite).sort((x,y)=>x-y),out=[];a.forEach(n=>{const last=out[out.length-1];if(!last||Math.abs(n-last.mean)>threshold)out.push({vals:[n],mean:n});else{last.vals.push(n);last.mean=last.vals.reduce((s,v)=>s+v,0)/last.vals.length}});return out.map(x=>x.mean)}
  function targetToken23(v){const s=String(v||'').replace(/\s/g,'');let m=s.match(/^([1-3])-?(\d{1,2})$/);if(m)return`${m[1]}-${Number(m[2])}`;if(/^([1-3])\d{2}$/.test(s))return`${s[0]}-${Number(s.slice(1))}`;return''}
  function parseTimetableLayout23(page,source,docClass,year){
    const items=(page?.items||[]).filter(x=>x.text),text=page?.text||items.map(x=>x.text).join(' '),days=['월','화','수','목','금'],dayXs={};items.forEach(x=>{const t=String(x.text).replace(/\s/g,'');const m=t.match(/^([월화수목금])(?:요일)?$/);if(m&&!dayXs[m[1]])dayXs[m[1]]=x.left+x.width/2});
    const classItems=items.map(x=>({...x,target:targetToken23(x.text),cx:x.left+x.width/2,cy:x.top+x.height/2})).filter(x=>x.target);if(Object.keys(dayXs).length<4&&classItems.length>=4){const xs=cluster23(classItems.map(x=>x.cx),55);if(xs.length>=4){const min=Math.min(...xs),max=Math.max(...xs);days.forEach((d,i)=>dayXs[d]=min+(max-min)*(i/4))}}
    const periodItems=items.map(x=>({...x,cy:x.top+x.height/2})).filter(x=>/^\s*\d{1,2}\s*교시\s*$/.test(x.text)||/^\s*[1-9]\s*$/.test(x.text));let ys=cluster23(periodItems.map(x=>x.cy),30);if(ys.length<3)ys=cluster23(classItems.map(x=>x.cy),30);if(Object.keys(dayXs).length<3||ys.length<2)return[];
    const ws=parseWeekStart23(text),out=[];classItems.forEach(x=>{const day=days.slice().sort((a,b)=>Math.abs(dayXs[a]-x.cx)-Math.abs(dayXs[b]-x.cx))[0];if(!day||Math.abs(dayXs[day]-x.cx)>Math.max(120,(Math.max(...Object.values(dayXs))-Math.min(...Object.values(dayXs)))/5))return;let pi=0;ys.forEach((y,i)=>{if(Math.abs(y-x.cy)<Math.abs(ys[pi]-x.cy))pi=i});const period=pi+1;if(period<1||period>12)return;const near=items.filter(z=>Math.abs((z.left+z.width/2)-x.cx)<95&&Math.abs((z.top+z.height/2)-x.cy)<55&&z!==x).map(z=>z.text).join(' '),subject=(near.match(/음악|창체|창동|예술|체육|진로/)||[])[0]||'수업';if(docClass==='live'){const date=addDays23(ws,days.indexOf(day));out.push({id:id23(),checked:false,kind:'live',date,weekStart:ws,day,period,target:x.target,subject,title:`${x.target} ${subject}`,source,raw:near,confidence:.84})}else out.push({id:id23(),checked:false,kind:'timetable',day,period,target:x.target,label:`${x.target} ${subject}`,title:`${x.target} ${subject}`,source,raw:near,confidence:.86})});return C.dedupe(out,x=>`${x.kind}|${x.date||''}|${x.day}|${x.period}|${x.target}`)
  }

  function classMatch23(docClass,kind){if(kind==='profile')return true;if(docClass==='schoolplan')return true;return({calendar:'calendar',timetable:'timetable',live:'live',assessment:'assessment',admin:'admin',club:'calendar'})[docClass]===kind}
  function rescore23(got,doc,quality,sensitive,batchId,method){return(got||[]).map(s=>{const base=Number(s.confidence)||.5,f=D.fuseSuggestion({baseConfidence:base,docClass:doc.classId,docConfidence:doc.confidence,extractionQuality:quality,kind:s.kind,mixed:doc.mixed,sensitive:sensitive||doc.classId==='student'});return{...s,v23BaseConfidence:base,v23BatchId:batchId,v23DocClass:doc.classId,v23DocLabel:doc.label,v23ExtractMethod:method,v23Quality:quality,v23Auto:f.auto,checked:f.auto,confidence:f.confidence}})}
  function sourceSuggestions23(extracted,file,y,doc,batchId){
    const ext=ext23(file),text=extracted.text||'';let got=ext==='ics'?parseICS(text,file.name):textSuggestions(text,file.name,'auto',y.year);if(extracted.rows?.length){const tt=C.parseTimetableGrid(extracted.rows,(y.subjects||['음악'])[0]||'음악');got.push(...tt.map(x=>({id:id23(),checked:false,kind:'timetable',title:x.label,label:x.label,day:x.day,period:x.period,target:x.target,source:file.name,confidence:.97})))}
    if(extracted.ocrPages?.length&&(doc.classId==='timetable'||doc.classId==='live'||/시간표|컴시간|교시/.test(text))){extracted.ocrPages.forEach(p=>got.push(...parseTimetableLayout23(p,file.name,doc.classId==='live'?'live':'timetable',y.year)))}
    if(doc.classId==='student')got=got.filter(x=>x.kind==='profile');return got
  }

  function reportClassLabel23(r){if(r.duplicate)return'중복 파일';if(r.error)return'분석 실패';if(r.doc?.mixed)return`복합 · ${r.doc.label}`;return r.doc?.label||'분류 미확정'}
  function methodLabel23(m){const s=String(m||'');if(s.startsWith('image-ocr:Paddle'))return'PP-OCRv5 한국어 OCR';if(s.startsWith('image-ocr:Tesseract'))return'Tesseract 보조 OCR';return({ 'pdf-native-layout':'PDF 원문+레이아웃','pdf-ocr':'스캔 PDF OCR','pdf-hybrid-layout+ocr':'PDF 원문+OCR 혼합','spreadsheet-native':'Excel/CSV 표 원문','docx-native':'DOCX 원문','hwp-native':'HWP 원문','hwpx-native':'HWPX 원문','pptx-native':'PPTX 원문','ics-native':'ICS 구조','native-text':'텍스트 원문'})[s]||s}
  function ensureReportUI23(){
    const importer=q('#importer');if(!importer)return;const input=q('#importFiles');if(input)input.accept='.hwp,.hwpx,.pdf,.xlsx,.xls,.csv,.txt,.docx,.pptx,.ics,.jpg,.jpeg,.png,.webp,.bmp';
    const banner=q('#bulkInboxBanner .mini');if(banner)banner.textContent='Google Document AI 방식처럼 파일형식 판별 → 원문/표/레이아웃 추출 → 필요한 페이지만 고정밀 OCR → 문서 전체 분류 → 신뢰도 재검증을 거쳐 확실한 항목만 자동 적용합니다.';
    const small=q('#importer .upload small');if(small)small.textContent='HWP · HWPX · PDF(스캔 포함) · Excel · DOCX · PPTX · ICS · 이미지';
    if(!q('#v23DocReport')){const anchor=q('#inboxSummary')||q('#bulkInboxBanner');anchor?.insertAdjacentHTML('afterend',`<article id="v23DocReport" class="card v23-report spaced"><div class="head"><div><span class="kicker">DOCUMENT INTELLIGENCE</span><h3>문서 인식 리포트</h3><p class="muted">원문을 우선 읽고, 스캔된 페이지만 한국어 PP-OCRv5로 보완합니다. 문서 전체 종류와 항목별 신뢰도를 함께 계산해 애매한 것만 검토합니다.</p></div><span id="v23BatchBadge" class="pill">대기</span></div><div class="v23-pipeline"><span>① 형식</span><b>→</b><span>② 원문·표</span><b>→</b><span>③ OCR 보완</span><b>→</b><span>④ 문서분류</span><b>→</b><span>⑤ 신뢰도</span><b>→</b><span>⑥ 자동/검토</span></div><div id="v23ReportList" class="v23-report-list"><div class="empty">파일을 올리면 파일별 인식 방식과 분류 신뢰도를 보여줍니다.</div></div><div class="notice v23-local-note"><b>개인정보 보호:</b> Google·Azure·AWS의 문서 처리 구조를 모티브로 했지만 학교 파일을 해당 서비스로 전송하지 않습니다. 원문 추출과 OCR은 이 브라우저에서 처리하고 구조화된 결과만 Teacher OS에 저장합니다.</div></article>`)}
    const chip=q('#v17Chip');if(chip)chip.textContent='v0.23 · Document Intelligence';const foot=q('.side-foot');if(foot)foot.textContent='v0.23 · smart multi-document intake';
  }
  function renderReports23(){const box=q('#v23ReportList'),badge=q('#v23BatchBadge');if(!box)return;if(!batchReports23.length){box.innerHTML='<div class="empty">파일을 올리면 파일별 인식 방식과 분류 신뢰도를 보여줍니다.</div>';if(badge)badge.textContent='대기';return}const auto=batchReports23.reduce((n,r)=>n+(r.autoCount||0),0),review=batchReports23.reduce((n,r)=>n+(r.reviewCount||0),0);if(badge)badge.textContent=`자동 ${auto} · 검토 ${review}`;const options=D.classOptions();box.innerHTML=batchReports23.map(r=>{if(r.duplicate)return`<div class="v23-file-row is-duplicate"><div class="grow"><b>${esc23(r.name)}</b><div class="mini">이미 반영된 같은 내용의 파일입니다.</div></div><span class="pill">중복 건너뜀</span></div>`;if(r.error)return`<div class="v23-file-row is-error"><div class="grow"><b>${esc23(r.name)}</b><div class="mini">${esc23(r.error)}</div></div><span class="pill warn">실패</span></div>`;const conf=Math.round((r.doc?.confidence||0)*100),quality=Math.round((r.quality||0)*100),warn=r.doc?.classId==='student'?' · 학생자료는 자동 적용 차단':!r.count?' · 자동세팅 항목 미검출':'';return`<div class="v23-file-row"><div class="v23-file-main"><b>${esc23(r.name)}</b><div class="mini">${esc23(methodLabel23(r.method))} · 추출품질 ${quality}% · 후보 ${r.count||0}개${esc23(warn)}</div></div><div class="v23-file-class"><span class="pill ${conf<82||!r.count?'warn':''}">${esc23(reportClassLabel23(r))} ${conf}%</span><select class="field v23-class-select" data-v23-class="${r.id}" title="분류가 틀리면 수정하세요. 같은 파일명 패턴은 다음부터 학습합니다.">${options.map(o=>`<option value="${o.id}" ${o.id===r.doc?.classId?'selected':''}>${esc23(o.label)}</option>`).join('')}</select></div><div class="v23-file-result"><b>${r.autoCount||0}</b><small>자동</small><b>${r.reviewCount||0}</b><small>검토</small></div></div>`}).join('')}

  const previousRenderSuggestions23=renderSuggestions;
  renderSuggestions=function(){previousRenderSuggestions23();qa('#suggestions .suggestion').forEach(row=>{const id=row.querySelector('[data-sg]')?.dataset.sg,s=(suggestions||[]).find(x=>x.id===id);if(!s?.v23DocLabel||row.querySelector('.v23-sg-meta'))return;const src=row.querySelector('.source');src?.insertAdjacentHTML('beforeend',`<div class="v23-sg-meta">문서 ${esc23(s.v23DocLabel)} · ${esc23(methodLabel23(s.v23ExtractMethod))} · 종합신뢰 ${Math.round((s.confidence||0)*100)}%${s.v23Auto?' · 자동적용 기준':' · 검토 필요'}</div>`)})};

  async function analyzeOne23(file,y,batchId,index,total){
    const report={id:id23(),name:file.name,ext:ext23(file),autoCount:0,reviewCount:0,count:0};try{progress23(index,total,file.name,'중복 확인');const hash=await hashFile23(file);report.hash=hash;if(isDuplicate23(hash,y)){report.duplicate=true;return report}progress23(index,total,file.name,'원문·레이아웃 추출');const extracted=await extractSmart23(file,y);report.method=extracted.method;report.extracted=extracted;const privacy=C.privacySignals(extracted.text||'');report.privacy=privacy;const feedback=feedbackFor23(file.name),layout={...(extracted.layout||{})};if(extracted.rows?.length){layout.tableRows=extracted.rows.length;layout.timetableSlots=C.parseTimetableGrid(extracted.rows,(y.subjects||['음악'])[0]||'음악').length}const doc=D.classifyDocument({name:file.name,text:extracted.text,ext:report.ext,layout,feedbackClass:feedback});report.doc=doc;const quality=D.extractionQuality({text:extracted.text,method:extracted.method,ocrConfidence:extracted.ocrConfidence});report.quality=quality;let got=sourceSuggestions23(extracted,file,y,doc,batchId),sensitive=privacy.length>0&&doc.classId==='student';got=rescore23(got,doc,quality,sensitive,batchId,extracted.method);report.count=got.length;report.autoCount=got.filter(x=>x.v23Auto).length;report.reviewCount=got.length-report.autoCount;report.suggestions=got;suggestions=C.dedupe([...(suggestions||[]),...got],x=>`${x.kind}|${x.date||''}|${x.day||''}|${x.period||''}|${x.title||x.label||''}|${x.profileType||''}|${x.target||''}`);let imp=(y.imports||[]).find(x=>x.hash===hash);if(!imp){imp={id:id23(),name:file.name,hash,kind:'지능형 자동분류',when:new Date().toLocaleString('ko-KR')};y.imports.push(imp)}Object.assign(imp,{name:file.name,docClass:doc.classId,docLabel:doc.label,confidence:doc.confidence,extractMethod:extracted.method,analysisStatus:got.length?'candidates':'no-candidates',candidateCount:got.length,autoCandidateCount:report.autoCount,extractionQuality:quality,lastAnalyzedAt:new Date().toISOString(),lastBatchId:batchId});return report}catch(e){report.error=String(e?.message||e);return report}
  }
  function applyCurrentAuto23(batchId){const preserve=new Map(),attempted=[];(suggestions||[]).forEach(s=>{if(s.v23BatchId===batchId){s.checked=!!s.v23Auto;if(s.checked)attempted.push(s)}else{preserve.set(s.id,!!s.checked);s.checked=false}});if(attempted.length)applySuggestions();const remainingIds=new Set((suggestions||[]).map(s=>s.id)),applied=attempted.filter(s=>!remainingIds.has(s.id)),blocked=attempted.length-applied.length,y=cur();const bySource=new Map();applied.forEach(s=>bySource.set(s.source,(bySource.get(s.source)||0)+1));for(const [source,n] of bySource){const imp=[...(y?.imports||[])].reverse().find(x=>x.name===source&&x.lastBatchId===batchId);if(imp){imp.appliedCount=Number(imp.appliedCount||0)+n;imp.lastAppliedAt=new Date().toISOString();imp.analysisStatus='applied'}}(suggestions||[]).forEach(s=>{if(preserve.has(s.id))s.checked=preserve.get(s.id)});renderSuggestions();return{attempted:attempted.length,applied:applied.length,blocked}}
  async function analyzeBatch23(){
    if(running23)return;if(!ensureYear())return;const input=q('#importFiles'),files=[...(input?.files||[])];if(!files.length){alert('파일을 선택해 주세요.');return}running23=true;const btn=q('#analyzeBtn');if(btn)btn.disabled=true;batchSeq23++;const batchId='v23-'+Date.now()+'-'+batchSeq23,batch=[];batchReports23=[];renderReports23();let privacy=[];
    try{for(let i=0;i<files.length;i++){const r=await analyzeOne23(files[i],cur(),batchId,i+1,files.length);batch.push(r);batchReports23=[...batch];privacy.push(...(r.privacy||[]).map(x=>`${r.name}: ${x}`));renderReports23();renderSuggestions();localStorage.setItem(KEY,JSON.stringify(state))}const auto=applyCurrentAuto23(batchId),review=(suggestions||[]).filter(s=>s.v23BatchId===batchId).length;const fails=batch.filter(r=>r.error).length,dups=batch.filter(r=>r.duplicate).length,empty=batch.filter(r=>!r.error&&!r.duplicate&&!r.count).length;localStorage.setItem(KEY,JSON.stringify(state));setStatus23(`<b>${files.length}개 파일 처리 완료</b> · ${auto.applied}개 자동 반영 · ${review}개 확인 필요${auto.blocked?` · 자동 보류 ${auto.blocked}개`:''}${empty?` · 항목 미검출 ${empty}개`:''}${dups?` · 이미 반영된 중복 ${dups}개`:''}${fails?` · 실패 ${fails}개`:''}`);const pn=q('#privacyNotice');if(pn){pn.hidden=!privacy.length;pn.innerHTML=privacy.length?`<b>개인정보 형태 감지:</b> ${esc23([...new Set(privacy)].join(' / '))}. 원문 파일은 저장하지 않습니다. 학생자료로 판정된 파일은 자동 적용을 막았습니다.`:''}switchView('importer');renderReports23()}finally{await closeTess23();if(btn)btn.disabled=false;running23=false}
  }
  function rescoreCorrected23(report,classId){const doc={...report.doc,classId,label:D.LABELS[classId]||classId,confidence:.99,mixed:false};report.doc=doc;report.reviewCount=0;report.autoCount=0;(suggestions||[]).filter(s=>s.source===report.name&&s.v23BatchId).forEach(s=>{const f=D.fuseSuggestion({baseConfidence:s.v23BaseConfidence||s.confidence,docClass:classId,docConfidence:.99,extractionQuality:s.v23Quality||report.quality,kind:s.kind,mixed:false,sensitive:classId==='student'});s.v23DocClass=classId;s.v23DocLabel=doc.label;s.confidence=f.confidence;s.v23Auto=f.auto;s.checked=false;if(f.auto)report.autoCount++;else report.reviewCount++});renderSuggestions();renderReports23();setStatus23(`<b>${esc23(report.name)}</b> 분류를 ${esc23(doc.label)}로 학습했습니다. 남아 있는 후보의 신뢰도를 다시 계산했습니다.`)}
  function bind23(){
    const input=q('#importFiles'),btn=q('#analyzeBtn');if(input&&!input.dataset.v23){input.dataset.v23='1';input.addEventListener('change',e=>{if(!e.target.files?.length)return;e.stopImmediatePropagation();analyzeBatch23()},true)}if(btn){btn.onclick=analyzeBatch23;btn.textContent='고정밀 다시 분석'}
    document.body.addEventListener('change',e=>{const sel=e.target.closest('[data-v23-class]');if(!sel)return;const r=batchReports23.find(x=>x.id===sel.dataset.v23Class);if(!r)return;saveFeedback23(r.name,sel.value);rescoreCorrected23(r,sel.value)});
  }
  function boot23(){ensureReportUI23();bind23();renderReports23();const importer=q('#importer .section-intro .muted');if(importer)importer.textContent='여러 종류의 학교 문서를 한꺼번에 올리면 원문·표·레이아웃·OCR을 결합해 자동 분류하고, 확실한 항목만 적용합니다.'}
  boot23();const prevRender23=globalThis.render;if(typeof prevRender23==='function')globalThis.render=function(){const r=prevRender23.apply(this,arguments);setTimeout(()=>{ensureReportUI23();bind23();renderReports23()},0);return r};
})();