(function(){
  const S=globalThis.TeacherOSSupervisor41;if(!S)return;
  const q=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  const STATE_KEY='myTeacherOS.supervisor41.state.v1',AUDIT_KEY='myTeacherOS.supervisor41.audit.v1';let busy=false,timer=null,lastPlan=null;
  function json(key,fallback={}){try{return Object.assign({},fallback,JSON.parse(localStorage.getItem(key)||'{}'))}catch{return fallback}}
  function readState(){try{return S.normalizeState(JSON.parse(localStorage.getItem(STATE_KEY)||'{}'))}catch{return S.emptyState()}}
  function writeState(v){try{localStorage.setItem(STATE_KEY,JSON.stringify(v))}catch{}}
  function year(){try{return typeof cur==='function'?cur():null}catch{return null}}
  function context(){const y=year(),ds=json('myTeacherOS.desktop36.settings.v1'),dst=json('myTeacherOS.desktop36.state.v1'),ns=json('myTeacherOS.neis35.settings.v1'),gs=json('myTeacherOS.google34.settings.v1'),gst=json('myTeacherOS.google34.state.v1');return{desktopConfigured:!!ds.token,desktopConnected:!!dst.connected,desktopError:String(dst.lastError||''),neisConfigured:!!ns.apiKey,neisHealthy:!y?.neis35?.lastError,neisError:String(y?.neis35?.lastError||''),googleConfigured:!!gs.gatewayUrl,googleConnected:!!gst.connected,googleError:String(gst.lastError||'')}}
  function audit(event,message,extra){let a=[];try{a=JSON.parse(localStorage.getItem(AUDIT_KEY)||'[]');if(!Array.isArray(a))a=[]}catch{}a.push({at:new Date().toISOString(),event,message,extra:extra||{}});a=a.slice(-300);try{localStorage.setItem(AUDIT_KEY,JSON.stringify(a))}catch{}return a}
  function audits(){try{const a=JSON.parse(localStorage.getItem(AUDIT_KEY)||'[]');return Array.isArray(a)?a:[]}catch{return[]}}
  function trigger(action){const map={desktop_rescan:'#desktopRescan36',neis_sync:'#neisSync35',google_repair:'#googleRepair34'},sel=map[action?.type],btn=sel?q(sel):null;if(!btn||btn.disabled)return false;btn.click();return true}
  function run(){if(busy)return lastPlan;busy=true;try{let state=readState();const plan=S.plan(context(),state,new Date());state=plan.state;const action=plan.actions.find(S.mayAutoExecute);if(action&&trigger(action)){state=S.recordAttempt(state,action,new Date());audit('recovery',`${action.title} 실행`,{source:action.source,type:action.type,attempt:action.attempts+1,reason:action.reason});state.lastAction=action.type}writeState(state);lastPlan={...plan,state};render41();return lastPlan}finally{busy=false}}
  function sourceStatus(source){const c=context(),h=S.sourceHealth(c,source),st=readState().sources[source]||{};return{...h,attempts:Number(st.attempts)||0,nextAt:st.nextAt||'',lastAttemptAt:st.lastAttemptAt||''}}
  function label(k){return({desktop:'Desktop Bridge',neis:'NEIS 공식',google:'Google Autopilot'})[k]||k}
  function ensureUI(){const dash=q('#dashboardBody');if(dash&&!q('#supervisor41')){const anchor=q('#autonomous40')||q('#workEntity39')||q('#desktopBridge36');const html=`<article id="supervisor41" class="card supervisor41 spaced"><div class="supervisor41-head"><div><span class="kicker">SELF-HEALING SUPERVISOR · v0.41</span><h2>연결 실패를 스스로 점검하고 복구합니다</h2><p class="muted">Desktop Bridge · NEIS · Google 자동화 상태를 감시하고 실패 시 안전한 재검사·재동기화·트리거 복구만 자동 실행합니다. 발송·결재·삭제·성적/학생부 변경은 복구 대상이 아닙니다.</p></div><div class="supervisor41-actions"><span id="supervisorStatus41" class="supervisor41-status">점검 중</span><button id="supervisorRun41" class="btn secondary tiny" type="button">상태 재점검</button><button id="supervisorExport41" class="btn secondary tiny" type="button">감사로그</button></div></div><div id="supervisorSources41" class="supervisor41-sources"></div><div id="supervisorAudit41" class="supervisor41-audit"></div></article>`;if(anchor)anchor.insertAdjacentHTML('afterend',html);else dash.insertAdjacentHTML('afterbegin',html);q('#supervisorRun41')?.addEventListener('click',()=>{audit('manual','사용자가 시스템 상태 재점검을 요청했습니다.');run()});q('#supervisorExport41')?.addEventListener('click',exportAudit)}}
  function render41(){ensureUI();const box=q('#supervisorSources41'),status=q('#supervisorStatus41'),log=q('#supervisorAudit41'),rows=S.SOURCES.map(sourceStatus),configured=rows.filter(x=>x.configured),bad=configured.filter(x=>!x.healthy);if(status){status.textContent=!configured.length?'연결 설정 대기':bad.length?`${bad.length}개 자동 복구 중`:'자동화 연결 정상';status.className='supervisor41-status '+(bad.length?'warn':'ok')}if(box)box.innerHTML=rows.map((x,i)=>{const source=S.SOURCES[i];return`<div class="supervisor41-source ${!x.configured?'off':x.healthy?'ok':'warn'}"><div><b>${esc(label(source))}</b><span>${!x.configured?'미설정':x.healthy?'정상':'복구 대기'}</span></div><p>${!x.configured?'연결 후 자동 감독을 시작합니다.':x.healthy?'최근 상태가 정상입니다.':esc(x.reason||'연결 오류')}</p>${x.attempts?`<em>재시도 ${x.attempts}회 · 다음 ${esc(formatWhen(x.nextAt))}</em>`:''}</div>`}).join('');if(log){const a=audits().slice(-5).reverse();log.innerHTML=a.length?`<div class="supervisor41-title"><b>자동 복구 기록</b><span>로컬 감사로그</span></div>`+a.map(x=>`<div class="supervisor41-log"><time>${esc(formatWhen(x.at))}</time><span>${esc(x.message||x.event)}</span></div>`).join(''):''}}
  function formatWhen(v){if(!v)return'';try{return new Date(v).toLocaleString('ko-KR',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'})}catch{return String(v)}}
  function exportAudit(){const payload={version:41,exportedAt:new Date().toISOString(),state:readState(),audit:audits()};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`teacher-os-supervisor-audit-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);audit('export','자동 복구 감사로그를 내보냈습니다.')}
  function schedule(){if(timer)clearTimeout(timer);timer=setTimeout(()=>{run();schedule()},5*60*1000)}
  const prev=globalThis.render;if(typeof prev==='function')globalThis.render=function(){const r=prev.apply(this,arguments);setTimeout(()=>{ensureUI();render41()},0);return r};
  document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')run()});window.addEventListener('online',()=>run());
  window.TeacherOSSupervisorRuntime41={run,state:readState,audit:()=>audits().slice()};
  setTimeout(()=>{ensureUI();run();schedule()},2200);
})();
