(function(){
  const V6=globalThis.TeacherOSCoreV6;
  if(!V6||!globalThis.TeacherOSCore)return;
  const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)];
  const esc7=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  const id7=()=>crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random().toString(16).slice(2);
  const SYNC_KEY='teacherOS.comciganSyncKey';
  function iso(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
  function mondayOf(input=new Date()){const d=new Date(input);d.setHours(0,0,0,0);const day=d.getDay();d.setDate(d.getDate()-((day+6)%7));return iso(d)}
  function addDays(date,n){const d=new Date(date+'T00:00:00');d.setDate(d.getDate()+n);return iso(d)}
  function weekLabel(ws){return `${ws} ~ ${addDays(ws,4)}`}
  function weekForDate(date){return mondayOf(new Date(date+'T00:00:00'))}
  function targetFromCls(v){const n=Number(v);if(!Number.isFinite(n)||n<101)return'';return `${Math.floor(n/100)}-${n%100}`}
  function dayFromDate(date){return ['일','월','화','수','목','금','토'][new Date(date+'T00:00:00').getDay()]}
  function migrateV7(){state.version=7;Object.values(state.years||{}).forEach(y=>{y.liveTimetableWeeks=y.liveTimetableWeeks&&typeof y.liveTimetableWeeks==='object'&&!Array.isArray(y.liveTimetableWeeks)?y.liveTimetableWeeks:{};y.comciganSync=y.comciganSync&&typeof y.comciganSync==='object'?y.comciganSync:{lastChecked:null,lastApplied:null,status:'not-connected'}});localStorage.setItem(KEY,JSON.stringify(state))}
  function ensureV7UI(){
    const foot=q('.side-foot');if(foot)foot.textContent='v0.7 · 실시간 주간표 + 자동분류 인박스';
    const upload=q('#importFiles');if(upload)upload.accept='.pdf,.xlsx,.xls,.csv,.txt,.docx,.hwpx,.ics,.jpg,.jpeg,.png,.webp';
    const hint=q('#importHint');if(hint){hint.value='auto';hint.style.display='none'}
    const importer=q('#importer');if(importer&&!q('#bulkInboxBanner')){importer.querySelector('.section-intro')?.insertAdjacentHTML('afterend',`<div id="bulkInboxBanner" class="bulk-banner"><div style="font-size:24px">⌁</div><div><b>한꺼번에 올리세요.</b><div class="mini">파일마다 종류를 고르지 않습니다. 문서·엑셀·컴시간 캡처를 함께 선택하면 학사일정 / 기본시간표 / 이번 주 실제시간표 / 평가 / 행정으로 자동 분류합니다.</div><div class="bulk-cats"><span>학사일정</span><span>기본 시간표</span><span>컴시간 변경표</span><span>평가계획</span><span>업무분장</span></div></div></div><div id="inboxSummary" class="inbox-summary"></div>`);const strong=importer.querySelector('.upload strong');if(strong)strong.textContent='학교 자료·시간표 캡처를 한 번에 선택';const small=importer.querySelector('.upload small');if(small)small.textContent='PDF · Excel · HWPX · DOCX · ICS · 이미지(JPG/PNG)';const btn=q('#analyzeBtn');if(btn)btn.textContent='한꺼번에 자동 분류'}
    const tt=q('#timetable');if(tt&&!q('#liveWeekPanel'))tt.querySelector('.notice')?.insertAdjacentHTML('afterend',`<article id="liveWeekPanel" class="card live-panel spaced"><div class="live-head"><div><span class="kicker">LIVE WEEK</span><h3>이번 주 실제 시간표</h3><p class="muted">컴시간 변경표가 있으면 기본 시간표보다 이 표를 우선합니다. 노란색은 기본표와 달라진 칸입니다.</p></div><div class="week-nav"><button class="btn secondary tiny" id="livePrev">←</button><input class="field" id="liveWeek" type="date"><button class="btn secondary tiny" id="liveNext">→</button></div></div><div id="liveSyncCard" class="sync-card spaced"></div><div class="timetable-wrap spaced"><table id="liveTimetableTable" class="live-grid"></table></div></article>`);
    if(!q('#syncDlg'))document.body.insertAdjacentHTML('beforeend',`<dialog id="syncDlg"><form class="modal" id="syncForm"><div class="modal-head"><div><span class="kicker">ENCRYPTED SYNC</span><h2>컴시간 자동동기화 키</h2></div><button type="button" class="close" data-v7-close>×</button></div><div class="stack"><div class="notice"><b>학교코드와 교사 선택값은 GitHub Secrets에만 저장</b>하고, 공개 저장소에는 암호화된 시간표만 올라오게 설계했습니다.</div><label>동기화 키<input class="field sync-key-input" id="syncKeyInput" type="password" autocomplete="off" placeholder="GitHub Secret TEACHEROS_SYNC_KEY와 같은 값"></label><p class="sync-note">이 키는 이 브라우저에만 저장됩니다. 공개 GitHub에는 저장하지 않습니다.</p></div><div class="modal-actions"><button type="button" class="btn secondary" data-v7-close>취소</button><button class="btn primary">저장하고 확인</button></div></form></dialog>`)
  }
  function liveWeek(y,ws){return y?.liveTimetableWeeks?.[ws]||null}
  function baseAt(y,day,period){return (y.timetable||[]).filter(s=>s.day===day&&Number(s.period)===Number(period))}
  function isChangedFromBase(y,s){const base=baseAt(y,s.day,s.period);if(!base.length)return true;return !base.some(b=>V6.normalizeScope(b.target||V6.targetFromLabel(b.label))===V6.normalizeScope(s.target||'')&&(b.subject||'음악')===(s.subject||'음악'))}
  function renderLiveWeek(y){
    if(!q('#liveTimetableTable'))return;const ws=q('#liveWeek')?.value||mondayOf();if(q('#liveWeek')&&!q('#liveWeek').value)q('#liveWeek').value=ws;const w=liveWeek(y,ws),slots=(w?.slots||[]).slice(),days=['월','화','수','목','금'];let h='<thead><tr><th>교시</th>'+days.map((d,i)=>`<th>${d}<div class="mini">${addDays(ws,i).slice(5)}</div></th>`).join('')+'</tr></thead><tbody>';const max=Math.max(7,...slots.map(s=>Number(s.period)||0),...(y.timetable||[]).map(s=>Number(s.period)||0));for(let p=1;p<=max;p++){h+=`<tr><td><b>${p}</b></td>`+days.map((d,i)=>{const date=addDays(ws,i),ls=slots.filter(s=>s.date===date&&Number(s.period)===p);if(ls.length)return `<td>${ls.map(s=>`<span class="live-slot ${isChangedFromBase(y,s)?'changed':''}"><b>${esc7(s.target||'')}</b> ${esc7(s.subject||'')}</span>`).join('')}</td>`;const base=baseAt(y,d,p),changed=!!w&&base.length>0;return `<td><div class="live-empty ${changed?'changed':''}">${!w&&base.length?base.map(s=>`<span class="live-slot"><b>${esc7(s.target||V6.targetFromLabel(s.label))}</b> ${esc7(s.subject||'음악')}</span>`).join(''):''}</div></td>`}).join('')+'</tr>'}h+='</tbody>';q('#liveTimetableTable').innerHTML=h;
    const sc=q('#liveSyncCard');if(sc){const key=localStorage.getItem(SYNC_KEY);sc.innerHTML=`<div class="sync-row"><span class="pill ${w?'':'warn'}">${w?'실제표 적용':'기본표 사용 중'}</span><b>${esc7(weekLabel(ws))}</b><span class="live-source">${w?esc7(w.source||'업로드')+' · '+esc7(w.updatedAt?new Date(w.updatedAt).toLocaleString('ko-KR'):''):''}</span><span style="flex:1"></span><button class="btn secondary tiny" id="syncNow">컴시간 확인</button><button class="btn secondary tiny" id="syncSetup">${key?'동기화 키 변경':'자동동기화 연결'}</button></div><div class="sync-note spaced">${key?'암호화된 최신 컴시간 파일을 확인합니다.':'자동동기화는 한 번 연결하면 GitHub Actions가 평일 아침에 컴시간을 확인하고, OS를 열 때 최신 암호화 파일을 반영합니다.'}</div>`;q('#syncNow').onclick=()=>syncComcigan(true);q('#syncSetup').onclick=()=>{q('#syncKeyInput').value=localStorage.getItem(SYNC_KEY)||'';q('#syncDlg').showModal()}}
    renderTodayFromLive(y)
  }
  function renderTodayFromLive(y){const date=iso(new Date()),ws=weekForDate(date),w=liveWeek(y,ws);if(!w)return;const slots=(w.slots||[]).filter(s=>s.date===date).sort((a,b)=>a.period-b.period);q('#todayTimetable').innerHTML=slots.length?slots.map(s=>`<span class="today-slot ${isChangedFromBase(y,s)?'changed':''}">${s.period}교시 · ${esc7(s.target)} ${esc7(s.subject||'음악')} <button type="button" class="mini-action" data-progress-plus="${esc7(s.target)}">수업완료 +1</button></span>`).join(''):'<span class="muted">컴시간 기준 오늘 등록된 수업이 없습니다.</span>'}
  function summaryCounts(list){const c={calendar:0,timetable:0,live:0,assessment:0,admin:0};list.forEach(s=>{if(c[s.kind]!==undefined)c[s.kind]++});return c}
  function renderInboxSummary(list=suggestions){const el=q('#inboxSummary');if(!el)return;const c=summaryCounts(list);el.innerHTML=`<div>학사일정 <b>${c.calendar}</b></div><div>기본 시간표 <b>${c.timetable}</b></div><div>실제 주간표 <b>${c.live}</b></div><div>평가 <b>${c.assessment}</b></div><div>행정 <b>${c.admin}</b></div>`}
  async function loadTesseract(){if(globalThis.Tesseract)return globalThis.Tesseract;await new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/tesseract.js@5.1.1/dist/tesseract.min.js';s.onload=resolve;s.onerror=()=>reject(new Error('이미지 분석 모듈을 불러오지 못했습니다.'));document.head.appendChild(s)});return globalThis.Tesseract}
  function parseWeekStart(text){const m=String(text).match(/(\d{2,4})[-./](\d{1,2})[-./](\d{1,2})\s*[~～-]\s*(\d{2,4})[-./](\d{1,2})[-./](\d{1,2})/);if(m){let yy=Number(m[1]);if(yy<100)yy+=2000;return mondayOf(new Date(`${yy}-${String(m[2]).padStart(2,'0')}-${String(m[3]).padStart(2,'0')}T00:00:00`))}return mondayOf()}
  function parseTsvWords(tsv){return String(tsv||'').split('\n').slice(1).map(line=>line.split('\t')).filter(a=>a.length>=12&&a[0]==='5'&&a[11]?.trim()).map(a=>({left:Number(a[6]),top:Number(a[7]),width:Number(a[8]),height:Number(a[9]),conf:Number(a[10]),text:a.slice(11).join('\t').trim()}))}
  function clusterNumbers(nums,threshold=24){const a=[...nums].sort((x,y)=>x-y),out=[];a.forEach(n=>{const last=out[out.length-1];if(!last||Math.abs(n-last.mean)>threshold)out.push({vals:[n],mean:n});else{last.vals.push(n);last.mean=last.vals.reduce((s,v)=>s+v,0)/last.vals.length}});return out.map(x=>x.mean)}
  function parseComciganOCR(data,source,year){
    const text=data.text||'',words=parseTsvWords(data.tsv),ws=parseWeekStart(text),dayNames=['월','화','수','목','금'];let dayXs={};dayNames.forEach(d=>{const w=words.find(x=>new RegExp('^'+d+'(?:\\(|요일|$)').test(x.text));if(w)dayXs[d]=w.left+w.width/2});if(Object.keys(dayXs).length<3){const codes=words.filter(w=>/^[123]\d{2}$/.test(w.text.replace(/\s/g,''))),xs=clusterNumbers(codes.map(w=>w.left+w.width/2),45);if(xs.length>=3){const min=Math.min(...xs),max=Math.max(...xs);dayNames.forEach((d,i)=>dayXs[d]=min+(max-min)*(i/4))}}
    const timeWords=words.filter(w=>/^(0?9|1[0-6])[:.]\d{2}/.test(w.text)),rowYs=clusterNumbers(timeWords.map(w=>w.top+w.height/2),28),codes=words.filter(w=>/^[123]\d{2}$/.test(w.text.replace(/\s/g,''))&&w.conf>=20),codeYs=rowYs.length>=3?rowYs:clusterNumbers(codes.map(w=>w.top+w.height/2),28),out=[];
    codes.forEach(w=>{const raw=w.text.replace(/\s/g,''),cx=w.left+w.width/2,cy=w.top+w.height/2,day=dayNames.slice().sort((a,b)=>Math.abs((dayXs[a]??99999)-cx)-Math.abs((dayXs[b]??99999)-cx))[0];if(!day||dayXs[day]===undefined||!codeYs.length)return;let period=codeYs.reduce((best,y,i)=>Math.abs(y-cy)<Math.abs(codeYs[best]-cy)?i:best,0)+1;if(period<1||period>12)return;const target=targetFromCls(raw);if(!target)return;const near=words.filter(x=>Math.abs((x.left+x.width/2)-cx)<70&&Math.abs((x.top+x.height/2)-cy)<70&&x.text!==w.text).map(x=>x.text).join(' '),subject=/창동|창체/.test(near)?'창동':/음악/.test(near)||/음악/.test(text)?'음악':'';const date=addDays(ws,dayNames.indexOf(day));out.push({id:id7(),checked:true,kind:'live',date,weekStart:ws,day,period,target,subject:subject||'수업',title:`${target} ${subject||'수업'}`,source,confidence:.82})});return C.dedupe(out,x=>`${x.date}|${x.period}|${x.target}|${x.subject}`)
  }
  async function imageSuggestions(file,y){const T=await loadTesseract();q('#importStatus').textContent=`${file.name} 이미지 읽는 중...`;const worker=await T.createWorker('kor+eng',1,{logger:m=>{if(m.status==='recognizing text')q('#importStatus').textContent=`${file.name} 이미지 분석 ${Math.round((m.progress||0)*100)}%`}});try{const r=await worker.recognize(file),text=r.data.text||'';if(/컴시간|시간표|교시/.test(text)){const live=parseComciganOCR(r.data,file.name,y.year);if(live.length)return live}return textSuggestions(text,file.name,'auto',y.year)}finally{await worker.terminate()}}
  async function analyzeAllFiles(){
    if(!ensureYear())return;const files=[...q('#importFiles').files];if(!files.length){alert('파일을 선택해 주세요.');return}const y=cur();q('#importStatus').textContent='자료 종류를 자동 판별하는 중...';let add=[],privacy=[];for(const f of files){try{const ext=f.name.split('.').pop().toLowerCase();let got=[];if(['jpg','jpeg','png','webp'].includes(ext))got=await imageSuggestions(f,y);else{const text=await readTextFile(f);privacy.push(...C.privacySignals(text).map(x=>`${f.name}: ${x}`));got=ext==='ics'?parseICS(text,f.name):textSuggestions(text,f.name,'auto',y.year);const rows=await spreadsheetRows(f);if(rows.length){const tt=C.parseTimetableGrid(rows,'음악');got.push(...tt.map(x=>({id:id7(),checked:true,kind:'timetable',title:x.label,label:x.label,day:x.day,period:x.period,target:x.target,source:f.name,confidence:.96})))}}add.push(...got);if(!y.imports.some(x=>x.name===f.name))y.imports.push({id:id7(),name:f.name,kind:'자동분류',when:new Date().toLocaleString('ko-KR')})}catch(err){add.push({id:id7(),checked:false,kind:'calendar',date:'',title:`${f.name} 분석 실패: ${err.message}`,source:f.name,confidence:.1})}}
    suggestions=C.dedupe([...suggestions,...add],x=>`${x.kind}|${x.date||''}|${x.day||''}|${x.period||''}|${x.title}|${x.profileType||''}|${x.target||''}`);q('#importStatus').textContent=`${files.length}개 파일에서 ${add.length}개 항목을 자동 분류했습니다.`;q('#privacyNotice').hidden=!privacy.length;q('#privacyNotice').innerHTML=privacy.length?`<b>개인정보 형태 감지:</b> ${esc7([...new Set(privacy)].join(' / '))}. 원문은 저장하지 않습니다.`:'';renderSuggestions();renderInboxSummary();localStorage.setItem(KEY,JSON.stringify(state))
  }
  renderSuggestions=function(){if(!suggestions.length){q('#suggestions').innerHTML='<div class="empty">추출된 항목이 없습니다.</div>';renderInboxSummary();return}q('#suggestions').innerHTML=suggestions.map(s=>{const [ct,cc]=confidenceLabel(s.confidence||.5),kind=s.kind==='calendar'?'학사':s.kind==='timetable'?'기본 시간표':s.kind==='live'?'실제 주간표':s.kind==='assessment'?'평가':s.kind==='admin'?'행정':'환경',detail=s.kind==='live'?`${s.date} · ${s.period}교시`:s.kind==='timetable'?`${s.day} ${s.period}교시`:s.kind==='profile'?(s.profileType==='office'?'교육청':'학교명'):(s.date||'날짜 없음');return `<label class="suggestion"><input type="checkbox" data-sg="${s.id}" ${s.checked?'checked':''}><span class="tag ${s.kind==='timetable'||s.kind==='live'?'timetable':''}">${kind}</span><span class="sg-date">${esc7(detail)}</span><span class="sg-title"><b>${esc7(s.title||s.label)}</b><div class="source">${esc7(s.source)}${s.weight?' · '+esc7(s.weight):''}${s.target?' · '+esc7(s.target):''}</div></span><span class="confidence ${cc}">${ct}</span></label>`}).join('');renderInboxSummary()};
  const baseApply=applySuggestions;applySuggestions=function(){const y=cur();if(!y)return;const liveSel=suggestions.filter(x=>x.checked&&x.kind==='live');if(liveSel.length){const groups={};liveSel.forEach(s=>{const k=s.weekStart||weekForDate(s.date);(groups[k]||(groups[k]=[])).push(s)});Object.entries(groups).forEach(([ws,list])=>{y.liveTimetableWeeks[ws]={weekStart:ws,source:list[0]?.source||'컴시간 캡처',updatedAt:new Date().toISOString(),slots:list.map(s=>({date:s.date,day:s.day||dayFromDate(s.date),period:Number(s.period),target:V6.normalizeScope(s.target),subject:s.subject||'음악',label:s.title||`${s.target} ${s.subject||'음악'}`,changed:true,source:s.source}))}});suggestions=suggestions.filter(x=>!(x.checked&&x.kind==='live'))}baseApply();renderLiveWeek(cur())};
  function b64ToBytes(s){return Uint8Array.from(atob(s),c=>c.charCodeAt(0))}
  async function deriveSyncKey(pass,salt){const mat=await crypto.subtle.importKey('raw',new TextEncoder().encode(pass),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',hash:'SHA-256',salt:new TextEncoder().encode(salt),iterations:150000},mat,{name:'AES-GCM',length:256},false,['decrypt'])}
  async function decryptSync(blob,pass){const key=await deriveSyncKey(pass,blob.salt||'teacher-os-comcigan-v1'),plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:b64ToBytes(blob.iv)},key,b64ToBytes(blob.data));return JSON.parse(new TextDecoder().decode(plain))}
  async function syncComcigan(manual=false){const y=cur();if(!y)return;const pass=localStorage.getItem(SYNC_KEY);if(!pass){if(manual){q('#syncKeyInput').value='';q('#syncDlg').showModal()}return}y.comciganSync.lastChecked=new Date().toISOString();try{const r=await fetch('./live/comcigan.enc.json?v='+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error('아직 자동동기화 파일이 없습니다.');const blob=await r.json(),p=await decryptSync(blob,pass);if(!p||!Array.isArray(p.slots)||!p.weekStart)throw new Error('동기화 파일 형식 오류');y.liveTimetableWeeks[p.weekStart]={weekStart:p.weekStart,source:'컴시간 자동동기화',updatedAt:p.fetchedAt||new Date().toISOString(),slots:p.slots};y.comciganSync.lastApplied=new Date().toISOString();y.comciganSync.status='ok';localStorage.setItem(KEY,JSON.stringify(state));render();if(manual)alert('최신 컴시간 시간표를 반영했습니다.')}catch(err){y.comciganSync.status='error';localStorage.setItem(KEY,JSON.stringify(state));renderLiveWeek(y);if(manual)alert('컴시간 자동동기화 확인: '+err.message)}}
  function initV7(){const btn=q('#analyzeBtn');if(btn)btn.onclick=analyzeAllFiles;if(q('#liveWeek')){q('#liveWeek').value=mondayOf();q('#liveWeek').onchange=()=>renderLiveWeek(cur());q('#livePrev').onclick=()=>{q('#liveWeek').value=addDays(q('#liveWeek').value,-7);renderLiveWeek(cur())};q('#liveNext').onclick=()=>{q('#liveWeek').value=addDays(q('#liveWeek').value,7);renderLiveWeek(cur())}}q('#syncForm').onsubmit=async ev=>{ev.preventDefault();const v=q('#syncKeyInput').value.trim();if(!v)return;localStorage.setItem(SYNC_KEY,v);q('#syncDlg').close();await syncComcigan(true)};qa('[data-v7-close]').forEach(b=>b.onclick=()=>b.closest('dialog')?.close())}
  const previousRender=render;render=function(){migrateV7();previousRender();const y=cur();if(y){renderLiveWeek(y);renderInboxSummary()}else if(q('#liveTimetableTable'))q('#liveTimetableTable').innerHTML='<tbody><tr><td class="empty">학년도를 먼저 만들어 주세요.</td></tr></tbody>'};
  ensureV7UI();migrateV7();initV7();render();const y=cur();if(y){const last=y.comciganSync?.lastChecked?new Date(y.comciganSync.lastChecked):null;if(!last||Date.now()-last.getTime()>20*60*60*1000)syncComcigan(false)}
})();
