(function(){
  const D=globalThis.TeacherOSDeskCore;if(!D)return;
  const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)];
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  const WIDGET_KEY='myTeacherOS.teacherDeskWidgets.v1';
  const CONTACT_KEY='myTeacherOS.staffContacts.v1';
  const DEFAULT_WIDGETS=['next','brief','tools','docs'];
  let timer27=null;

  function widgetConfig(){try{const x=JSON.parse(localStorage.getItem(WIDGET_KEY)||'null');if(x&&Array.isArray(x.order)&&x.enabled)return x}catch{}return{order:[...DEFAULT_WIDGETS],enabled:{next:true,brief:true,tools:true,docs:true}}}
  function saveWidgetConfig(c){localStorage.setItem(WIDGET_KEY,JSON.stringify(c))}
  function contacts(){try{const x=JSON.parse(localStorage.getItem(CONTACT_KEY)||'[]');return Array.isArray(x)?x:[]}catch{return[]}}
  function saveContacts(rows){localStorage.setItem(CONTACT_KEY,JSON.stringify(rows||[]))}
  function currentYear(){return typeof cur==='function'?cur():null}
  function currentDate(){return D.iso(new Date())}
  function prettyTarget(v){const m=String(v||'').match(/^(\d+)-(\d+)$/);return m?`${m[1]}학년 ${m[2]}반`:String(v||'')}
  function subjectOf(slot){if(slot?.subject)return slot.subject;const label=String(slot?.label||'').replace(/^\s*\d+[-학년반 ]+\d+\s*/,'').trim();return label||'수업'}

  function ensureUI(){
    const dash=q('#dashboardBody');
    if(dash&&!q('#teacherDesk27'))dash.insertAdjacentHTML('afterbegin',`<section id="teacherDesk27" class="teacher-desk27">
      <div class="desk-head27"><div><span class="kicker">TEACHER DESK</span><h2>지금 필요한 것만</h2><p class="muted">실제 시간표·진도·일정·자료를 한 화면에서 확인합니다.</p></div><button type="button" class="btn secondary tiny" id="deskWidgetBtn27">위젯 설정</button></div>
      <div id="deskGrid27" class="desk-grid27">
        <article class="desk-widget27 desk-next27" data-widget27="next"><div id="deskNext27"></div></article>
        <article class="desk-widget27" data-widget27="brief"><div class="desk-widget-title27"><span>오늘 한눈에</span><button type="button" class="linkbtn" data-go27="calendar">일정 보기</button></div><div id="deskBrief27"></div></article>
        <article class="desk-widget27" data-widget27="tools"><div class="desk-widget-title27"><span>빠른 도구</span><span class="mini">기기 안에서 처리</span></div><div class="desk-tools27"><button type="button" data-tool27="contacts"><span>☎</span><b>연락처</b><small>내선 검색</small></button><button type="button" data-tool27="message"><span>≡</span><b>메시지 정리</b><small>요점·할 일·기한</small></button><button type="button" data-go27="importer"><span>⇧</span><b>자동세팅</b><small>학교 자료 넣기</small></button><button type="button" data-go27="studentrecords"><span>♙</span><b>학생 기록</b><small>근거·초안</small></button></div></article>
        <article class="desk-widget27" data-widget27="docs"><div class="desk-widget-title27"><span>최근 자료 서랍</span><button type="button" class="linkbtn" data-go27="documents">전체 보기</button></div><div id="deskDocs27"></div></article>
      </div>
    </section>`);
    if(!q('#deskWidgetDlg27'))document.body.insertAdjacentHTML('beforeend',`<dialog id="deskWidgetDlg27"><form class="modal desk-modal27" id="deskWidgetForm27"><div class="modal-head"><div><span class="kicker">TODAY WIDGETS</span><h2>오늘 화면 위젯</h2><p class="muted">자주 보는 것만 남기고 순서를 바꿀 수 있습니다.</p></div><button type="button" class="close" data-close27>×</button></div><div id="deskWidgetList27" class="desk-widget-list27"></div><div class="modal-actions"><button type="button" class="btn secondary" data-close27>취소</button><button class="btn primary">저장</button></div></form></dialog>`);
    if(!q('#contactDlg27'))document.body.insertAdjacentHTML('beforeend',`<dialog id="contactDlg27"><div class="modal desk-modal27"><div class="modal-head"><div><span class="kicker">LOCAL CONTACTS</span><h2>교무실 연락처</h2><p class="muted">이름·부서·내선을 빠르게 찾습니다. 연락처는 이 브라우저에만 저장됩니다.</p></div><button type="button" class="close" data-close27>×</button></div><div class="notice warning"><b>내부자료 주의:</b> 연락처 파일이나 내용은 공개 GitHub로 보내지 않습니다. 학생 연락처는 넣지 마세요.</div><div class="contact-actions27"><input class="field" id="contactSearch27" placeholder="이름·부서·위치·내선 검색"><label class="btn secondary contact-upload27">연락처 파일<input id="contactFile27" type="file" accept=".xlsx,.xls,.csv,.txt" hidden></label><button type="button" class="btn secondary" id="contactClear27">전체 삭제</button></div><div id="contactStatus27" class="mini"></div><div id="contactList27" class="contact-list27"></div></div></dialog>`);
    if(!q('#messageDlg27'))document.body.insertAdjacentHTML('beforeend',`<dialog id="messageDlg27"><div class="modal desk-modal27 message-modal27"><div class="modal-head"><div><span class="kicker">LOCAL TEXT TOOL</span><h2>메시지·공문 빠른 정리</h2><p class="muted">외부 AI로 전송하지 않고 브라우저에서 규칙 기반으로 정리합니다.</p></div><button type="button" class="close" data-close27>×</button></div><div class="notice"><b>정확도 우선:</b> 없는 내용을 만들어내지 않습니다. 원문에 적힌 내용만 추려 보여줍니다.</div><div class="message-mode27"><label><input type="radio" name="messageMode27" value="digest" checked> 긴 메시지 요약</label><label><input type="radio" name="messageMode27" value="tidy"> 공문 문장 정돈</label></div><textarea class="field" id="messageInput27" rows="9" placeholder="메신저 내용이나 공문 초안을 붙여넣으세요."></textarea><div class="message-actions27"><button type="button" class="btn primary" id="messageRun27">정리하기</button><button type="button" class="btn secondary" id="messageClear27">지우기</button></div><div id="messageResult27" class="message-result27"><div class="empty">원문을 붙여넣으면 요점·해야 할 일·기한을 분리합니다.</div></div></div></dialog>`);
    bindUI();
  }

  const LABELS={next:'다음 교시',brief:'오늘 한눈에',tools:'빠른 도구',docs:'최근 자료 서랍'};
  function openWidgetConfig(){const c=widgetConfig(),box=q('#deskWidgetList27');box.innerHTML=c.order.map((id,i)=>`<div class="desk-widget-row27" data-widget-row27="${id}"><label><input type="checkbox" data-widget-enable27="${id}" ${c.enabled[id]!==false?'checked':''}> <b>${LABELS[id]}</b></label><div><button type="button" class="linkbtn" data-widget-up27="${id}" ${i===0?'disabled':''}>↑</button><button type="button" class="linkbtn" data-widget-down27="${id}" ${i===c.order.length-1?'disabled':''}>↓</button></div></div>`).join('');q('#deskWidgetDlg27').showModal()}
  function moveWidget(id,delta){const c=widgetConfig(),i=c.order.indexOf(id),j=i+delta;if(i<0||j<0||j>=c.order.length)return;[c.order[i],c.order[j]]=[c.order[j],c.order[i]];saveWidgetConfig(c);openWidgetConfig();applyWidgetConfig()}
  function applyWidgetConfig(){const c=widgetConfig(),grid=q('#deskGrid27');if(!grid)return;c.order.forEach(id=>{const el=grid.querySelector(`[data-widget27="${id}"]`);if(el){el.hidden=c.enabled[id]===false;grid.appendChild(el)}})}

  function recentLog(y,target){return(y?.lessonLogs||[]).filter(l=>!l.undone&&D.normalizeTarget(l.target)===D.normalizeTarget(target)).sort((a,b)=>String(b.createdAt||b.date||'').localeCompare(String(a.createdAt||a.date||'')))[0]||null}
  function renderNext(){const box=q('#deskNext27'),y=currentYear();if(!box)return;if(!y){box.innerHTML='<div class="empty">학년도를 먼저 설정하세요.</div>';return}const d=D.lessonContext(y,new Date());if(!d.slot){box.innerHTML=`<div class="desk-next-top27"><span class="desk-status27">${d.status==='done'?'오늘 수업 완료':'다음 수업 없음'}</span><span class="mini">${esc(d.source)}</span></div><h3>${d.status==='done'?'오늘 예정된 수업이 끝났습니다.':'오늘 등록된 수업이 없습니다.'}</h3><div class="desk-next-foot27"><button type="button" class="btn secondary tiny" data-go27="timetable">시간표 확인</button></div>`;return}
    const slot=d.slot,target=D.normalizeTarget(slot.target),p=y.classProgress?.[target]||{},log=recentLog(y,target),time=d.seconds!==null?D.formatDuration(d.seconds):'',approx=d.exact?'':'약 ',status=d.status==='current'?'수업 중':'다음 수업',countLabel=d.status==='current'?`종료까지 ${approx}${time}`:`시작까지 ${approx}${time}`;
    const progress=p.lesson||p.topic?`Teacher OS 기록 · ${Number(p.lesson)||0}차시${p.topic?' · '+p.topic:''}`:'이 반의 최근 진도 기록이 아직 없습니다.';
    const last=log?.summary?`직전 수업 · ${log.summary}`:progress;
    box.innerHTML=`<div class="desk-next-top27"><span class="desk-status27 ${d.status==='current'?'live':''}">${status}</span><span class="mini">${esc(d.source)}${d.exact?' · 시간표 시각':' · 기본 교시시간 기준(예상)'}</span></div><div class="desk-count27"><strong>${slot.period}교시</strong><b>${esc(countLabel)}</b></div><h3>${esc(prettyTarget(target))} · ${esc(subjectOf(slot))}</h3><div class="desk-progress27"><span>${esc(last)}</span>${log?.summary&&progress!==last?`<small>${esc(progress)}</small>`:''}</div><div class="desk-next-foot27"><button type="button" class="btn primary tiny" data-go27="lessonlog">수업 기록 열기</button><button type="button" class="btn secondary tiny" data-go27="progress">반별 진도</button></div>`;
  }

  function renderBrief(){const y=currentYear(),box=q('#deskBrief27');if(!box)return;if(!y){box.innerHTML='<div class="empty">학년도를 먼저 설정하세요.</div>';return}const today=currentDate(),events=(y.calendarEvents||[]).filter(e=>e.date===today),tasks=(y.tasks||[]).filter(t=>!t.done);const due=[...(y.projects||[]).filter(x=>x.due===today).map(x=>({title:x.name,type:'행정'})),...(y.assessments||[]).filter(x=>x.due===today).map(x=>({title:x.name,type:'평가'}))];let rows=[];events.slice(0,3).forEach(x=>rows.push({tag:x.type||'일정',text:x.title}));due.slice(0,3).forEach(x=>rows.push({tag:x.type,text:x.title}));tasks.slice(0,3).forEach(x=>rows.push({tag:'할 일',text:x.text}));box.innerHTML=rows.length?`<div class="desk-brief-count27"><span>오늘 일정 <b>${events.length+due.length}</b></span><span>남은 할 일 <b>${tasks.length}</b></span></div>${rows.slice(0,6).map(r=>`<div class="desk-brief-row27"><span class="pill">${esc(r.tag)}</span><b>${esc(r.text)}</b></div>`).join('')}`:'<div class="empty">오늘 등록된 일정이나 남은 할 일이 없습니다.</div>'}

  function docLabel(f){return f.docLabel||f.docClass||f.kind||'자동분석'}
  function renderDocs(){const y=currentYear(),box=q('#deskDocs27');if(!box)return;const rows=(y?.imports||[]).slice().reverse().slice(0,5);box.innerHTML=rows.length?rows.map(f=>`<div class="desk-doc-row27"><span class="desk-doc-icon27">▤</span><div><b>${esc(f.name||'자료')}</b><small>${esc(docLabel(f))}${Number.isFinite(Number(f.confidence))?' · '+Math.round(Number(f.confidence)*100)+'%':''}</small></div></div>`).join(''):'<div class="empty">아직 자동세팅으로 읽은 자료가 없습니다.</div>'}
  function renderDesk(){ensureUI();applyWidgetConfig();renderNext();renderBrief();renderDocs();const foot=q('.side-foot');if(foot)foot.textContent='v0.27 · Teacher Desk live workspace'}

  function openContacts(){ensureUI();q('#contactSearch27').value='';q('#contactStatus27').textContent='';renderContacts();q('#contactDlg27').showModal()}
  function renderContacts(){const query=(q('#contactSearch27')?.value||'').trim().toLowerCase(),rows=contacts().filter(r=>!query||[r.name,r.extension,r.department,r.room].some(v=>String(v||'').toLowerCase().includes(query))).slice(0,80),box=q('#contactList27');if(!box)return;box.innerHTML=rows.length?rows.map((r,i)=>`<div class="contact-row27"><div><b>${esc(r.name)}</b><span>${esc([r.department,r.room].filter(Boolean).join(' · ')||'부서/위치 미등록')}</span></div><button type="button" class="contact-ext27" data-copy-ext27="${esc(r.extension)}">${esc(r.extension||'내선 없음')}</button></div>`).join(''):'<div class="empty">${contacts().length?'검색 결과가 없습니다.':'연락처 파일을 한 번 불러오세요.'}</div>'}
  function normalizeHeader(v){return String(v||'').replace(/\s+/g,'').toLowerCase()}
  function findHeader(aoa){for(let i=0;i<Math.min(10,aoa.length);i++){const row=(aoa[i]||[]).map(normalizeHeader),name=row.findIndex(x=>/(성명|이름|교사명|교직원명|name)/.test(x)),ext=row.findIndex(x=>/(내선|내선번호|extension|전화)/.test(x)),dept=row.findIndex(x=>/(부서|부서명|업무|department)/.test(x)),room=row.findIndex(x=>/(위치|교무실|실명|장소|room)/.test(x));if(name>=0&&(ext>=0||dept>=0||room>=0))return{row:i,name,ext,dept,room}}return null}
  function parseContactAOA(aoa){const h=findHeader(aoa);if(!h)return{rows:[],error:'이름과 내선/부서/위치 열 제목을 찾지 못했습니다.'};const out=[];for(let i=h.row+1;i<aoa.length;i++){const r=aoa[i]||[],name=String(r[h.name]||'').trim();if(!name)continue;out.push({name,extension:h.ext>=0?String(r[h.ext]||'').replace(/[^0-9-]/g,'').trim():'',department:h.dept>=0?String(r[h.dept]||'').trim():'',room:h.room>=0?String(r[h.room]||'').trim():''})}return{rows:D.safeContactRows(out),error:''}}
  async function importContacts(file){const status=q('#contactStatus27');status.textContent='연락처를 읽는 중…';try{let aoa=[];if(/\.txt$/i.test(file.name)){const text=await file.text();aoa=text.split(/\r?\n/).map(line=>line.split(/\t|,/))}else{if(!globalThis.XLSX)throw new Error('Excel 읽기 모듈을 불러오지 못했습니다.');const wb=XLSX.read(await file.arrayBuffer(),{type:'array'}),ws=wb.Sheets[wb.SheetNames[0]];aoa=XLSX.utils.sheet_to_json(ws,{header:1,defval:''})}const parsed=parseContactAOA(aoa);if(parsed.error)throw new Error(parsed.error);if(!parsed.rows.length)throw new Error('저장할 연락처를 찾지 못했습니다.');const map=new Map(contacts().map(r=>[`${r.name}|${r.extension}`,r]));parsed.rows.forEach(r=>map.set(`${r.name}|${r.extension}`,r));saveContacts([...map.values()].sort((a,b)=>a.name.localeCompare(b.name,'ko')));status.textContent=`${parsed.rows.length}건을 읽었습니다. 파일 원문은 저장하지 않습니다.`;renderContacts()}catch(e){status.textContent='가져오기 실패: '+String(e.message||e)}}

  function openMessage(){ensureUI();q('#messageDlg27').showModal()}
  function messageMode(){return q('input[name="messageMode27"]:checked')?.value||'digest'}
  function runMessage(){const text=q('#messageInput27').value.trim(),box=q('#messageResult27');if(!text){box.innerHTML='<div class="empty">정리할 원문을 입력하세요.</div>';return}if(messageMode()==='tidy'){const out=D.tidyText(text);box.innerHTML=`<div class="message-section27"><b>의미를 바꾸지 않고 공백·줄바꿈·중복 문장부호만 정돈</b><textarea class="field" id="messageOutput27" rows="9">${esc(out)}</textarea><button type="button" class="btn secondary tiny" data-copy-message27>결과 복사</button></div>`;return}const d=D.messageDigest(text),list=(title,rows,empty)=>`<div class="message-section27"><b>${title}</b>${rows.length?rows.map(x=>`<div class="message-line27">${esc(x)}</div>`).join(''):`<span class="mini">${empty}</span>`}</div>`;box.innerHTML=list('요점',d.points,'요점을 찾지 못했습니다.')+list('내가 해야 할 일',d.actions,'명시된 행동을 찾지 못했습니다.')+list('기한·시간',d.deadlines,'명시된 기한을 찾지 못했습니다.')+`<div class="mini message-caution27">원문에 명시된 문장만 추렸습니다. 자동 해석이므로 원문과 최종 대조하세요.</div>`}
  async function copyText(text){try{await navigator.clipboard.writeText(text);return true}catch{return false}}

  function bindUI(){if(document.body.dataset.deskBound27)return;document.body.dataset.deskBound27='1';document.body.addEventListener('click',async e=>{const go=e.target.closest('[data-go27]');if(go){if(typeof switchView==='function')switchView(go.dataset.go27);return}if(e.target.closest('#deskWidgetBtn27')){openWidgetConfig();return}const up=e.target.closest('[data-widget-up27]');if(up){moveWidget(up.dataset.widgetUp27,-1);return}const down=e.target.closest('[data-widget-down27]');if(down){moveWidget(down.dataset.widgetDown27,1);return}const tool=e.target.closest('[data-tool27]');if(tool?.dataset.tool27==='contacts'){openContacts();return}if(tool?.dataset.tool27==='message'){openMessage();return}if(e.target.closest('[data-close27]')){e.target.closest('dialog')?.close();return}const ext=e.target.closest('[data-copy-ext27]');if(ext){if(ext.dataset.copyExt27){const ok=await copyText(ext.dataset.copyExt27);if(ok){const old=ext.textContent;ext.textContent='복사됨';setTimeout(()=>ext.textContent=old,900)}}return}if(e.target.closest('#contactClear27')){if(confirm('이 브라우저에 저장된 교무실 연락처를 모두 삭제할까요?')){saveContacts([]);renderContacts();q('#contactStatus27').textContent='연락처를 삭제했습니다.'}return}if(e.target.closest('#messageRun27')){runMessage();return}if(e.target.closest('#messageClear27')){q('#messageInput27').value='';q('#messageResult27').innerHTML='<div class="empty">원문을 붙여넣으면 요점·해야 할 일·기한을 분리합니다.</div>';return}if(e.target.closest('[data-copy-message27]')){const ok=await copyText(q('#messageOutput27')?.value||'');if(ok)alert('정돈된 문장을 복사했습니다.');return}});
    q('#deskWidgetForm27')?.addEventListener('submit',e=>{e.preventDefault();const c=widgetConfig();qa('[data-widget-enable27]').forEach(x=>c.enabled[x.dataset.widgetEnable27]=x.checked);saveWidgetConfig(c);q('#deskWidgetDlg27').close();applyWidgetConfig()});
    q('#contactSearch27')?.addEventListener('input',renderContacts);q('#contactFile27')?.addEventListener('change',e=>{const f=e.target.files?.[0];if(f)importContacts(f);e.target.value=''});
  }

  function startTimer(){if(timer27)clearInterval(timer27);timer27=setInterval(()=>{if(!document.hidden&&q('#dashboard')?.classList.contains('active'))renderNext()},1000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)renderNext()},{passive:true})}
  function boot(){ensureUI();renderDesk();startTimer()}
  const prevRender=globalThis.render;if(typeof prevRender==='function')globalThis.render=function(){const r=prevRender.apply(this,arguments);setTimeout(renderDesk,0);return r};
  const prevSwitch=globalThis.switchView;if(typeof prevSwitch==='function')globalThis.switchView=function(id){const r=prevSwitch.apply(this,arguments);if(id==='dashboard')setTimeout(renderDesk,0);return r};
  setTimeout(boot,0);
})();
