(function(){
  const V6=globalThis.TeacherOSCoreV6;
  if(!V6)return;
  const q=s=>document.querySelector(s);
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#039;'}[m]));
  const pad=n=>String(n).padStart(2,'0');
  function iso(d){return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`}
  function parseDate(s){return new Date(String(s||'')+'T00:00:00')}
  function monday(d=new Date()){const x=new Date(d);x.setHours(0,0,0,0);x.setDate(x.getDate()-((x.getDay()+6)%7));return iso(x)}
  function addDays(s,n){const d=parseDate(s);d.setDate(d.getDate()+n);return iso(d)}
  function daysUntil(s){if(!s)return null;const a=parseDate(iso(new Date())),b=parseDate(s);return Math.ceil((b-a)/86400000)}
  function dayKo(s){return ['일','월','화','수','목','금','토'][parseDate(s).getDay()]}
  function ensureUI(){
    const body=q('#dashboardBody');if(!body||q('#visualCommand'))return;
    const anchor=body.querySelector('.summary');
    const html=`<div id="visualCommand" class="visual-command"><section class="visual-panel"><div class="visual-panel-head"><div><span class="kicker">WEEK FLOW</span><h2>이번 주 수업 흐름</h2><p class="muted mini">컴시간 변경표가 있으면 실제표를 우선해 보여줍니다.</p></div><span class="visual-badge" id="visualWeekBadge">LIVE</span></div><div id="visualWeek" class="week-board"></div><div id="visualInsight" class="visual-insight"></div></section><div class="visual-side-stack"><section class="visual-panel"><div class="visual-panel-head"><div><span class="kicker">PRIORITY</span><h3>곧 닥치는 일</h3></div></div><div id="visualUrgency" class="urgency-list"></div></section><section class="visual-panel"><div class="visual-panel-head"><div><span class="kicker">NOW</span><h3>오늘의 자동 판단</h3></div></div><div id="visualBrief" class="urgency-list"></div></section></div></div><div id="visualGrid" class="visual-grid"><section class="visual-panel"><div class="visual-panel-head"><div><span class="kicker">CLASS PACE</span><h3>반별 진도 지도</h3><p class="muted mini">같은 학년 안에서 어느 반이 빠르고 느린지 봅니다.</p></div></div><div id="visualProgress" class="progress-visual"></div></section><section class="visual-panel"><div class="visual-panel-head"><div><span class="kicker">ASSESSMENT RADAR</span><h3>평가까지 남은 수업</h3><p class="muted mini">달력 날짜보다 실제 수업 횟수를 우선합니다.</p></div></div><div id="visualAssessment" class="assessment-radar"></div></section></div>`;
    anchor?.insertAdjacentHTML('beforebegin',html);
    const foot=q('.side-foot');if(foot)foot.textContent='v0.12 · Visual command center';
  }
  function targets(y){return V6.classTargets(y.timetable||[])}
  function weekTruth(y,ws){const sync=String(y?.comciganSync?.status||''),hasBase=Array.isArray(y?.timetable)&&y.timetable.length>0,hasLive=!!y?.liveTimetableWeeks?.[ws];if(sync==='collector-error')return hasBase?{known:true,source:'basic',label:'기본 시간표'}:{known:false,label:'컴시간 수집 오류'};if(sync==='transport-unavailable')return hasBase?{known:true,source:'basic',label:'기본 시간표'}:{known:false,label:'동기화 경로 미구성'};if(sync==='mismatch')return hasBase?{known:true,source:'basic',label:'기본 시간표'}:{known:false,label:'컴시간 설정 불일치'};if(sync==='unconfigured')return hasBase?{known:true,source:'basic',label:'기본 시간표'}:{known:false,label:'컴시간 설정 필요'};if(hasLive)return{known:true,source:'live',label:'컴시간 실제표'};if(hasBase)return{known:true,source:'basic',label:'기본 시간표'};if(sync==='waiting')return{known:false,label:'컴시간 최신표 미확인'};return{known:false,label:'시간표 자료 미확인'}}
  function currentWeekSlots(y,ws,date,day,source){if(source==='live'){const live=y.liveTimetableWeeks?.[ws];return (live?.slots||[]).filter(s=>s.date===date).sort((a,b)=>Number(a.period)-Number(b.period))}return (y.timetable||[]).filter(s=>s.day===day).sort((a,b)=>Number(a.period)-Number(b.period)).map(s=>({...s,date,target:V6.normalizeScope(s.target||V6.targetFromLabel(s.label))}))}
  function renderWeek(y){const ws=monday(),today=iso(new Date()),days=['월','화','수','목','금'],truth=weekTruth(y,ws);q('#visualWeekBadge').textContent=truth.label;q('#visualWeek').innerHTML=days.map((day,i)=>{const date=addDays(ws,i),slots=truth.known?currentWeekSlots(y,ws,date,day,truth.source):[],events=(y.calendarEvents||[]).filter(e=>e.date===date).slice(0,2),empty=truth.known?'수업 없음':'시간표 미확인';return `<article class="week-day ${date===today?'is-today':''}"><div class="week-day-head"><span class="week-day-name">${day}${date===today?' · 오늘':''}</span><span class="week-day-date">${date.slice(5).replace('-','.')}</span></div>${slots.length?slots.map(s=>`<span class="week-slot ${s.changed?'changed':''}">${Number(s.period)||'-'}교시 · <b>${esc(s.target||V6.targetFromLabel(s.label)||'')}</b> ${esc(s.subject||'음악')}</span>`).join(''):`<div class="week-empty">${empty}</div>`}${events.map(e=>`<span class="week-event">${esc(e.title)}</span>`).join('')}</article>`}).join('')}
  function urgencyItems(y){const items=[];(y.assessments||[]).forEach(x=>x.due&&items.push({date:x.due,type:'평가',title:x.name||'평가'}));(y.projects||[]).forEach(x=>x.due&&items.push({date:x.due,type:'행정',title:x.name||'행정업무'}));(y.clubs||[]).forEach(x=>x.due&&items.push({date:x.due,type:'동아리',title:x.name||'동아리'}));(y.calendarEvents||[]).forEach(x=>x.date&&items.push({date:x.date,type:'학사',title:x.title||'학사일정'}));return items.map(x=>({...x,d:daysUntil(x.date)})).filter(x=>x.d!==null&&x.d>=0&&x.d<=21).sort((a,b)=>a.d-b.d||a.date.localeCompare(b.date)).slice(0,7)}
  function renderUrgency(y){const items=urgencyItems(y);q('#visualUrgency').innerHTML=items.length?items.map(x=>`<div class="urgency-item"><div class="urgency-day ${x.d<=2?'hot':x.d<=7?'warm':''}">${x.d===0?'TODAY':'D-'+x.d}</div><div><div class="urgency-type">${esc(x.type)} · ${esc(x.date.slice(5))}</div><div class="urgency-title">${esc(x.title)}</div></div></div>`).join(''):'<div class="visual-empty">21일 안에 급한 일정이 없습니다.</div>'}
  function renderBrief(y){const a=(y.skillBrief||[]).slice(0,4);q('#visualBrief').innerHTML=a.length?a.map((x,i)=>`<div class="urgency-item"><div class="urgency-day">${pad(i+1)}</div><div><div class="urgency-type">AUTO BRIEF</div><div class="urgency-title">${esc(x.text)}</div></div></div>`).join(''):'<div class="visual-empty">현재 자동 판단에서 특별한 경고가 없습니다.</div>'}
  function renderProgress(y){const ts=targets(y),stats=V6.paceStats(y.classProgress||{},ts);if(!stats.some(s=>s.recorded)){q('#visualProgress').innerHTML='<div class="visual-empty">수업기록이 쌓이면 반별 진도 차이를 자동으로 시각화합니다.</div>';return}const max=Math.max(1,...stats.map(s=>s.lesson));q('#visualProgress').innerHTML=stats.map(s=>{const pct=Math.max(4,Math.round(s.lesson/max*100));const cls=s.gap!=null&&s.gap<=-1?'behind':s.gap!=null&&s.gap>=1?'ahead':'';const gap=s.gap==null?'기록':Math.abs(s.gap)<.5?'평균':s.gap>0?`+${s.gap.toFixed(1)}`:s.gap.toFixed(1);return `<div class="progress-row"><div class="progress-label">${esc(s.target)}</div><div class="progress-track"><div class="progress-fill ${cls}" style="width:${pct}%"></div></div><div class="progress-meta">${s.lesson}차시 · ${gap}</div>${s.topic?`<div class="progress-topic">${esc(s.topic)}</div>`:''}</div>`}).join('')}
  function assessmentRows(y){const ts=targets(y),rows=[];(y.assessments||[]).forEach(a=>{if(!a.due||daysUntil(a.due)<0)return;let match=ts.filter(t=>!a.target||V6.scopeMatches(a.target,t));if(!match.length)match=[a.target||'전체'];match.forEach(t=>{const remaining=/^\d+-\d+$/.test(t)?V6.countClassTeachingSlots(y.timetable||[],y.calendarEvents||[],y.timetableExceptions||[],t,iso(new Date()),a.due):null;rows.push({name:a.name||'평가',due:a.due,target:t,remaining,d:daysUntil(a.due)})})});return rows.sort((a,b)=>(a.remaining??999)-(b.remaining??999)||a.d-b.d).slice(0,6)}
  function renderAssessment(y){const rows=assessmentRows(y);if(!rows.length){q('#visualAssessment').innerHTML='<div class="visual-empty">예정된 평가가 없습니다.</div>';return}const max=Math.max(1,...rows.map(r=>r.remaining==null?0:r.remaining));q('#visualAssessment').innerHTML=rows.map(r=>{const remain=r.remaining==null?'—':r.remaining,pct=r.remaining==null?15:Math.max(8,Math.min(100,Math.round(r.remaining/max*100)));return `<div class="radar-item"><div class="radar-ring" style="--pct:${pct}%"><span>${esc(r.target)}</span></div><div><div class="radar-title">${esc(r.name)}</div><div class="radar-sub">${esc(r.due)} · D-${r.d}</div></div><div class="radar-count"><strong>${remain}</strong><small>남은 수업</small></div></div>`}).join('')}
  function renderInsight(y){const stats=V6.paceStats(y.classProgress||{},targets(y)).filter(s=>s.recorded&&s.gap!=null),behind=stats.slice().sort((a,b)=>a.gap-b.gap)[0],urgent=urgencyItems(y)[0];let main='수업·평가·일정을 연결해 자동으로 우선순위를 계산하고 있습니다.',sub='수업기록이 쌓일수록 반별 진도 판단이 더 정확해집니다.';if(behind&&behind.gap<=-1)main=`${behind.target} 진도가 같은 학년 평균보다 ${Math.abs(behind.gap).toFixed(1)}차시 느립니다.`;if(urgent)sub=`가장 가까운 일정은 ${urgent.type} ‘${urgent.title}’이며 ${urgent.d===0?'오늘':`D-${urgent.d}`}입니다.`;q('#visualInsight').innerHTML=`<b>${esc(main)}</b><div class="sub">${esc(sub)}</div>`}
  function renderVisuals(){ensureUI();const y=typeof cur==='function'?cur():null;if(!y){['#visualWeek','#visualUrgency','#visualBrief','#visualProgress','#visualAssessment'].forEach(s=>{const el=q(s);if(el)el.innerHTML='<div class="visual-empty">학년도를 먼저 만들어 주세요.</div>'});return}renderWeek(y);renderUrgency(y);renderBrief(y);renderProgress(y);renderAssessment(y);renderInsight(y)}
  const previousRender=globalThis.render;if(typeof previousRender==='function'){globalThis.render=function(){const r=previousRender.apply(this,arguments);try{renderVisuals()}catch(e){console.warn('visual dashboard',e)}return r}}
  renderVisuals();requestAnimationFrame(renderVisuals);
})();