(function(){
  const V=globalThis.TeacherOSDocumentVersions;if(!V)return;
  const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)];
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  const HISTORY_KEY='myTeacherOS.importVersionHistory.v1';
  const pendingMeta=new Map(),overrides=new Map();
  let conflicts=[];
  const AUTO_CLASSES=new Set(['calendar','timetable','live','assessment','admin','club']);
  function y30(){try{return typeof cur==='function'?cur():null}catch{return null}}
  function saveState30(){try{localStorage.setItem(KEY,JSON.stringify(state))}catch{}}
  function allSuggestions(){try{return typeof suggestions!=='undefined'&&Array.isArray(suggestions)?suggestions:[]}catch{return[]}}
  function imports(y=y30()){return Array.isArray(y?.imports)?y.imports:[]}
  function latestImportByName(name,y=y30()){const a=imports(y).filter(x=>x.name===name);return a[a.length-1]||null}
  function readHistory(){try{const x=JSON.parse(localStorage.getItem(HISTORY_KEY)||'[]');return Array.isArray(x)?x:[]}catch{return[]}}
  function writeHistory(a){try{localStorage.setItem(HISTORY_KEY,JSON.stringify((a||[]).slice(-5)));return true}catch(e){console.error('Teacher OS document-version history save failed',e);return false}}
  function deep(v){return JSON.parse(JSON.stringify(v))}
  function captureFiles(e){const input=e.target;if(input?.id!=='importFiles'||!input.files?.length)return;[...input.files].forEach(f=>pendingMeta.set(f.name,{lastModified:Number(f.lastModified)||null,size:Number(f.size)||null,familyKey:V.familyKey(f.name)}))}
  function enrichImport(item){if(!item)return null;const p=pendingMeta.get(item.name)||{};if(!item.familyKey)item.familyKey=V.familyKey(item.name);if(!item.fileLastModified&&p.lastModified)item.fileLastModified=p.lastModified;if(!item.size&&p.size)item.size=p.size;return item}
  function candidateInfo(source,y=y30()){
    const ni=enrichImport(latestImportByName(source,y));if(!ni)return null;const candidates=V.activeCandidates(imports(y),ni);if(!candidates.length)return{newImport:ni,oldImports:[],relation:{relation:'unrelated',confidence:'high',reason:'no-prior-version'}};
    const old=candidates[candidates.length-1],nm=V.meta(ni.name,{hash:ni.hash,docClass:ni.docClass,lastModified:ni.fileLastModified,size:ni.size});return{newImport:ni,oldImports:candidates.map(x=>x.item),oldImport:old.item,relation:V.compare(nm,old.m)}
  }
  function derivedCount(y,sources){const set=new Set(sources);return['calendarEvents','timetable','assessments','projects'].reduce((n,k)=>n+(Array.isArray(y[k])?y[k].filter(x=>set.has(x.source)).length:0),0)}
  function snapshotBeforeReplace(y,newImport,oldImports){const h=readHistory();h.push({id:'iv-'+Date.now(),year:y.year,newSource:newImport.name,oldSources:oldImports.map(x=>x.name),savedAt:new Date().toISOString(),before:{calendarEvents:deep(y.calendarEvents||[]),timetable:deep(y.timetable||[]),assessments:deep(y.assessments||[]),projects:deep(y.projects||[]),imports:deep(y.imports||[])}});return writeHistory(h)}
  function prepareReplace(y,newImport,oldImports){const names=[...new Set(oldImports.map(x=>x.name))];if(!names.length)return true;if(!snapshotBeforeReplace(y,newImport,oldImports)){const status=q('#importStatus');if(status)status.innerHTML='<b>문서 교체를 중단했습니다.</b> 되돌리기용 복구 이력을 기기에 저장하지 못했습니다. 브라우저 저장공간을 확인한 뒤 다시 시도하세요.';return false}const set=new Set(names);['calendarEvents','timetable','assessments','projects'].forEach(k=>{if(Array.isArray(y[k]))y[k]=y[k].filter(x=>!set.has(x.source))});oldImports.forEach(x=>{x.status='superseded';x.supersededBy=newImport.name;x.supersededAt=new Date().toISOString()});newImport.status='current';newImport.replaces=oldImports.map(x=>x.id).filter(Boolean);newImport.versionResolvedAt=new Date().toISOString();saveState30();return true}
  function setConflict(info,type){if(!info?.newImport||!info?.oldImport)return;info.newImport.status='version-review';info.newImport.versionAgainst=info.oldImport.name;info.newImport.versionReason=info.relation.reason;info.newImport.versionRelation=info.relation.relation;const row={newName:info.newImport.name,newId:info.newImport.id||info.newImport.hash,oldName:info.oldImport.name,oldId:info.oldImport.id||info.oldImport.hash,type,reason:info.relation.reason,relation:info.relation.relation,docLabel:info.newImport.docLabel||info.newImport.docClass||'문서'};conflicts=conflicts.filter(x=>x.newId!==row.newId);conflicts.push(row);saveState30();renderVersionPanel()}
  function removeConflict(newId){conflicts=conflicts.filter(x=>x.newId!==newId);renderVersionPanel()}
  function relationLabel(c){if(c.relation==='older')return'새로 올린 파일이 이전 버전으로 보임';if(c.type==='latest-needs-review')return'수정본으로 보이지만 자동 교체 조건 미충족';return'같은 문서 계열 · 최신본 판단 필요'}
  function ensureUI(){const importer=q('#importer');if(!importer)return;if(!q('#rawPolicy30')){const intro=importer.querySelector('.section-intro');intro?.insertAdjacentHTML('afterend',`<article id="rawPolicy30" class="card raw-policy30"><div><span class="kicker">SOURCE FILE POLICY</span><b>원본 파일은 Teacher OS에 장기 보관하지 않습니다.</b><span>분석 후 파일 선택을 해제하고 이름·해시·분류·버전관계 같은 최소 메타데이터만 남깁니다. 원본은 본인 PC나 학교의 정식 저장공간에 보관하는 것을 권장합니다.</span></div><button type="button" class="btn secondary tiny" id="undoImportVersion30">최근 문서 교체 되돌리기</button></article>`)}if(!q('#versionReview30')){const anchor=q('#v23ReportPanel')||q('#suggestions')?.closest('article')||importer.querySelector('.notice');anchor?.insertAdjacentHTML('beforebegin','<article id="versionReview30" class="card version-review30" hidden></article>')}renderVersionPanel();renderUndoState()}
  function rebuildConflicts(){const y=y30();if(!y)return;const existing=imports(y).filter(x=>x.status==='version-review'&&x.versionAgainst);existing.forEach(x=>{const id=x.id||x.hash;if(conflicts.some(c=>c.newId===id))return;conflicts.push({newName:x.name,newId:id,oldName:x.versionAgainst,oldId:'',type:x.versionRelation==='older'?'older':'ambiguous',reason:x.versionReason||'',relation:x.versionRelation||'ambiguous',docLabel:x.docLabel||x.docClass||'문서'})})}
  function renderVersionPanel(){const box=q('#versionReview30');if(!box)return;rebuildConflicts();if(!conflicts.length){box.hidden=true;box.innerHTML='';return}box.hidden=false;box.innerHTML=`<div class="version-head30"><div><span class="kicker">DOCUMENT VERSION</span><h3>문서 버전 확인 ${conflicts.length}건</h3><p class="muted">업로드 순서만으로 덮어쓰지 않습니다. 파일명·버전표시·문서종류를 비교해 확실하지 않을 때만 선택을 요청합니다.</p></div></div><div class="version-list30">${conflicts.map(c=>`<div class="version-item30"><div class="version-state30">${esc(relationLabel(c))}</div><div class="version-compare30"><div><small>현재 사용</small><b>${esc(c.oldName)}</b></div><span>→</span><div><small>새로 업로드</small><b>${esc(c.newName)}</b></div></div><div class="version-actions30"><button type="button" class="btn primary tiny" data-v30-new="${esc(c.newId)}">새 파일을 최신본으로 사용</button><button type="button" class="btn secondary tiny" data-v30-old="${esc(c.newId)}">기존 파일 유지</button></div><div class="mini">${c.type==='latest-needs-review'?'새 파일이 수정본으로 보이지만 추출 결과 전체가 자동확정 기준을 통과하지 않아 검토가 필요합니다.':'최신임을 확정할 근거가 부족해 자동 덮어쓰지 않았습니다.'}</div></div>`).join('')}</div>`}
  function renderUndoState(){const b=q('#undoImportVersion30');if(!b)return;const h=readHistory().filter(x=>String(x.year)===String(y30()?.year));b.disabled=!h.length;b.title=h.length?`문서 교체 이력 ${h.length}건`:'되돌릴 문서 교체가 없습니다.'}
  function currentConflict(id){return conflicts.find(x=>String(x.newId)===String(id))}
  function chooseNew(id){const c=currentConflict(id),y=y30();if(!c||!y)return;const ni=latestImportByName(c.newName,y);if(!ni)return;overrides.set(c.newName,'new');ni.status='selected-new';ni.versionSelectedAt=new Date().toISOString();allSuggestions().filter(s=>s.source===c.newName&&s.v23Auto).forEach(s=>s.checked=true);saveState30();removeConflict(c.newId);try{if(typeof renderSuggestions==='function')renderSuggestions()}catch{}const status=q('#importStatus');if(status)status.innerHTML=`<b>${esc(c.newName)}</b>을 최신본으로 선택했습니다. 확실한 항목은 선택해 두었습니다. 아래 후보를 확인한 뒤 <b>선택 반영</b>을 누르세요.`}
  function chooseOld(id){const c=currentConflict(id),y=y30();if(!c||!y)return;const ni=latestImportByName(c.newName,y);if(ni){ni.status='ignored';ni.ignoredAt=new Date().toISOString();ni.ignoredBecause='기존 버전 유지'}overrides.set(c.newName,'old');allSuggestions().filter(s=>s.source===c.newName).forEach(s=>s.checked=false);saveState30();removeConflict(c.newId);try{if(typeof renderSuggestions==='function')renderSuggestions()}catch{}const status=q('#importStatus');if(status)status.innerHTML=`<b>${esc(c.oldName)}</b>을 계속 사용합니다. 새 파일은 반영하지 않고 버전 이력만 남겼습니다.`}
  function undoReplace(){const y=y30();if(!y)return;const h=readHistory();let idx=-1;for(let i=h.length-1;i>=0;i--)if(String(h[i].year)===String(y.year)){idx=i;break}if(idx<0)return;const snap=h[idx];if(!snap.before)return;['calendarEvents','timetable','assessments','projects','imports'].forEach(k=>{y[k]=deep(snap.before[k]||[])});h.splice(idx,1);writeHistory(h);saveState30();if(typeof render==='function')render();if(typeof switchView==='function')switchView('importer');ensureUI();const status=q('#importStatus');if(status)status.innerHTML=`문서 교체를 되돌렸습니다. <b>${esc((snap.oldSources||[]).join(', '))}</b> 상태로 복원했습니다.`}
  function releaseInputAfterAnalysis(){const status=q('#importStatus'),input=q('#importFiles');if(!status||!input)return;const txt=status.textContent||'';if(!/처리 완료/.test(txt)||input.dataset.v30Released==='1')return;input.dataset.v30Released='1';input.value='';if(!status.querySelector?.('.v30-release-note'))status.insertAdjacentHTML('beforeend',' <span class="v30-release-note">· 원본 파일 선택 해제 · 사이트에 원본 미보관</span>');if(conflicts.length)status.insertAdjacentHTML('beforeend',` <b>· 문서 버전 ${conflicts.length}건 검토 필요</b>`)}
  function observeImportStatus(){const box=q('#importStatus');if(!box||box.dataset.v30Observed)return;box.dataset.v30Observed='1';new MutationObserver(()=>{releaseInputAfterAnalysis();renderVersionPanel()}).observe(box,{childList:true,subtree:true,characterData:true})}
  function wrapApply(){const prev=globalThis.applySuggestions;if(typeof prev!=='function'||prev.__v30)return;const wrapped=function(){const y=y30(),ss=allSuggestions(),selected=ss.filter(x=>x.checked);if(!y||!selected.length)return prev.apply(this,arguments);const sources=[...new Set(selected.map(x=>x.source).filter(Boolean))];let blocked=0;for(const source of sources){const info=candidateInfo(source,y);if(!info||!info.oldImport)continue;const ov=overrides.get(source);if(ov==='old'){ss.filter(s=>s.source===source).forEach(s=>s.checked=false);blocked++;continue}if(ov==='new'){if(!prepareReplace(y,info.newImport,info.oldImports)){ss.filter(s=>s.source===source).forEach(s=>s.checked=false);blocked++;continue}overrides.delete(source);continue}const sourceSuggestions=ss.filter(s=>s.source===source&&s.v23BatchId);const allAuto=sourceSuggestions.length>0&&sourceSuggestions.every(s=>s.v23Auto===true);const safeClass=AUTO_CLASSES.has(info.newImport.docClass);const strongNew=info.relation.relation==='newer'&&info.relation.confidence==='high';const safeAuto=strongNew&&safeClass&&allAuto&&Number(info.newImport.confidence||0)>=.90;if(safeAuto){if(!prepareReplace(y,info.newImport,info.oldImports)){ss.filter(s=>s.source===source).forEach(s=>s.checked=false);blocked++}continue}ss.filter(s=>s.source===source).forEach(s=>s.checked=false);setConflict(info,strongNew?'latest-needs-review':info.relation.relation==='older'?'older':'ambiguous');blocked++}const remain=ss.filter(x=>x.checked);if(!remain.length){saveState30();try{if(typeof renderSuggestions==='function')renderSuggestions()}catch{}if(typeof switchView==='function')switchView('importer');return false}const r=prev.apply(this,arguments);renderUndoState();return r};wrapped.__v30=true;globalThis.applySuggestions=wrapped}
  function bind(){document.addEventListener('change',captureFiles,true);document.body.addEventListener('click',e=>{const n=e.target.closest('[data-v30-new]');if(n){chooseNew(n.dataset.v30New);return}const o=e.target.closest('[data-v30-old]');if(o){chooseOld(o.dataset.v30Old);return}if(e.target.closest('#undoImportVersion30'))undoReplace()});}
  function refresh(){ensureUI();observeImportStatus();releaseInputAfterAnalysis();renderVersionPanel();renderUndoState();const input=q('#importFiles');if(input&&!input.files?.length)delete input.dataset.v30Released;const foot=q('.side-foot');if(foot)foot.textContent='v0.30 · document version lineage'}
  wrapApply();bind();setTimeout(refresh,0);
  const prevRender=globalThis.render;if(typeof prevRender==='function')globalThis.render=function(){const r=prevRender.apply(this,arguments);setTimeout(refresh,0);return r};
  const prevSwitch=globalThis.switchView;if(typeof prevSwitch==='function')globalThis.switchView=function(id){const r=prevSwitch.apply(this,arguments);if(id==='importer'||id==='documents')setTimeout(refresh,0);return r};
})();