(function(){
  const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)];
  const KEY26='myTeacherOS.feedbackReports.v1';
  const VERSION26='v0.26';
  const MAX_REPORTS26=30;
  let lastRuntimeError26='';

  const esc26=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#039;'}[m]));
  const id26=()=>globalThis.crypto?.randomUUID?crypto.randomUUID():`fb-${Date.now()}-${Math.random().toString(16).slice(2)}`;
  function read26(){try{const x=JSON.parse(localStorage.getItem(KEY26)||'[]');return Array.isArray(x)?x:[]}catch{return[]}}
  function write26(rows){localStorage.setItem(KEY26,JSON.stringify((rows||[]).slice(-MAX_REPORTS26)))}
  function browser26(){const u=navigator.userAgent||'';if(/SamsungBrowser/i.test(u))return' Samsung Internet';if(/Edg\//.test(u))return'Edge';if(/CriOS|Chrome\//.test(u))return'Chrome';if(/FxiOS|Firefox\//.test(u))return'Firefox';if(/Safari\//.test(u))return'Safari';return'기타 브라우저'}
  function device26(){return /Android|iPhone|iPad|iPod|Mobile/i.test(navigator.userAgent||'')?'모바일':'PC/태블릿'}
  function activeView26(){const v=q('.view.active');return{view:v?.id||'',title:q('#title')?.textContent?.trim()||v?.querySelector('h2,h1')?.textContent?.trim()||'알 수 없음'}}
  function loadMs26(){try{const n=performance.getEntriesByType('navigation')?.[0];if(n?.loadEventEnd>0)return Math.round(n.loadEventEnd);if(n?.domContentLoadedEventEnd>0)return Math.round(n.domContentLoadedEventEnd)}catch{}return null}
  function meta26(){const a=activeView26(),conn=navigator.connection||navigator.mozConnection||navigator.webkitConnection;return{version:VERSION26,view:a.view,page:a.title,url:location.href.split('#')[0],device:device26(),browser:browser26().trim(),viewport:`${innerWidth}×${innerHeight}`,language:navigator.language||'',online:navigator.onLine!==false,network:conn?.effectiveType||'',loadMs:loadMs26(),lastRuntimeError:lastRuntimeError26||''}}
  function ensure26(){
    if(!q('#feedbackFab26'))document.body.insertAdjacentHTML('beforeend',`<button type="button" id="feedbackFab26" class="feedback-fab26" aria-label="오류·불편 신고"><span>!</span><b>오류·불편 신고</b></button>`);
    if(!q('#feedbackDlg26'))document.body.insertAdjacentHTML('beforeend',`<dialog id="feedbackDlg26" class="feedback-dialog26"><form id="feedbackForm26" class="feedback-modal26"><div class="feedback-head26"><div><span class="kicker">TEST FEEDBACK</span><h2>오류·불편 신고</h2><p class="muted">막히거나 이상한 순간에 짧게 남겨 주세요. 현재 화면·버전·기기 정보는 자동으로 붙습니다.</p></div><button type="button" class="close" id="feedbackClose26">×</button></div><div class="feedback-privacy26"><b>개인정보는 적지 마세요.</b><span>학생 이름·상담내용·전화번호·학교 내부문서 원문은 신고 내용에 넣지 않습니다.</span></div><div class="feedback-grid26"><label>문제 유형<select class="field" id="feedbackType26" required><option value="정확도">정확도가 이상함</option><option value="작동오류">버튼/기능이 안 됨</option><option value="느림">너무 느림</option><option value="이해어려움">어떻게 쓰는지 모르겠음</option><option value="화면불편">화면이 불편함</option><option value="개선제안">개선 아이디어</option></select></label><label>영향 정도<select class="field" id="feedbackImpact26"><option value="막힘">업무를 진행할 수 없음</option><option value="불편">진행은 되지만 불편함</option><option value="가벼움">가벼운 문제/제안</option></select></label></div><label>무엇을 하려고 했나요?<textarea class="field" id="feedbackAction26" rows="2" required placeholder="예: PDF와 HWP 파일 8개를 한꺼번에 자동세팅하려고 함"></textarea></label><label>무엇이 이상했나요?<textarea class="field" id="feedbackProblem26" rows="4" required placeholder="예: 평가계획서 1개가 학사일정으로 분류됨"></textarea></label><label>원래 어떻게 되길 기대했나요? <span class="mini">(선택)</span><textarea class="field" id="feedbackExpected26" rows="2" placeholder="예: 평가계획으로 분류되고 자동 적용 전 확인되길 기대함"></textarea></label><label class="feedback-check26"><input type="checkbox" id="feedbackPrivacy26" required><span>학생 개인정보나 민감한 학교 내부정보를 입력하지 않았습니다.</span></label><div id="feedbackMeta26" class="feedback-meta26"></div><div class="feedback-actions26"><button type="button" class="btn secondary" id="feedbackHistory26">내 신고함</button><span class="grow"></span><button type="button" class="btn secondary" id="feedbackCancel26">취소</button><button class="btn primary">신고 내용 만들기</button></div><div id="feedbackResult26" class="feedback-result26" hidden></div><div id="feedbackHistoryBox26" class="feedback-history26" hidden></div></form></dialog>`);
    bind26();
  }
  function open26(){ensure26();const m=meta26();q('#feedbackMeta26').innerHTML=`<b>자동진단</b><span>${esc26(m.page)} · ${esc26(m.version)} · ${esc26(m.device)} · ${esc26(m.browser)} · 화면 ${esc26(m.viewport)}${m.loadMs?` · 로딩 ${m.loadMs}ms`:''}</span>`;q('#feedbackResult26').hidden=true;q('#feedbackHistoryBox26').hidden=true;q('#feedbackDlg26').showModal()}
  function reportText26(r){const m=r.meta||{};return[`[Teacher OS 테스트 피드백 ${r.id}]`,`유형: ${r.type} / 영향: ${r.impact}`,`화면: ${m.page||'-'} (${m.view||'-'})`,`버전: ${m.version||VERSION26}`,`기기: ${m.device||'-'} / 브라우저: ${m.browser||'-'} / 화면: ${m.viewport||'-'}`,m.network?`네트워크: ${m.network}`:'',m.loadMs?`초기 로딩: ${m.loadMs}ms`:'',`시각: ${new Date(r.createdAt).toLocaleString('ko-KR')}`,'',`[하려던 일]`,` ${r.action}`,'',`[이상한 점]`,` ${r.problem}`,r.expected?`\n[기대한 결과]\n ${r.expected}`:'',m.lastRuntimeError?`\n[직전 기술 오류]\n ${m.lastRuntimeError}`:'','',`※ 학생 개인정보·상담내용·학교 내부문서 원문은 포함하지 않음`].filter(Boolean).join('\n')}
  function githubUrl26(r){const body=reportText26(r),title=`[테스트] ${r.type} · ${r.meta?.page||'Teacher OS'}`;const u=new URL('https://github.com/puzzlex5/my-teacher-os/issues/new');u.searchParams.set('title',title);u.searchParams.set('body',body);return u.toString()}
  async function copy26(text){try{await navigator.clipboard.writeText(text);return true}catch{const t=document.createElement('textarea');t.value=text;t.style.position='fixed';t.style.opacity='0';document.body.appendChild(t);t.select();let ok=false;try{ok=document.execCommand('copy')}catch{}t.remove();return ok}}
  async function share26(r){const text=reportText26(r);if(navigator.share){try{await navigator.share({title:'Teacher OS 테스트 피드백',text});return}catch(e){if(e?.name==='AbortError')return}}const ok=await copy26(text);alert(ok?'신고 내용을 복사했습니다. 카카오톡·문자 등으로 보내 주세요.':'복사하지 못했습니다. 아래 내용 복사 버튼을 다시 눌러 주세요.')}
  function saveReport26(){const r={id:id26().slice(0,12),createdAt:new Date().toISOString(),type:q('#feedbackType26').value,impact:q('#feedbackImpact26').value,action:q('#feedbackAction26').value.trim(),problem:q('#feedbackProblem26').value.trim(),expected:q('#feedbackExpected26').value.trim(),meta:meta26()};const rows=read26();rows.push(r);write26(rows);return r}
  function renderResult26(r){const box=q('#feedbackResult26');box.hidden=false;box.dataset.reportId=r.id;box.innerHTML=`<div><b>신고 내용이 준비됐습니다.</b><span>이 기기의 신고함에도 저장했습니다. 자동으로 학생정보나 Teacher OS 데이터는 첨부하지 않습니다.</span></div><div class="feedback-result-actions26"><button type="button" class="btn primary" data-feedback-share26="${esc26(r.id)}">공유하기</button><button type="button" class="btn secondary" data-feedback-copy26="${esc26(r.id)}">내용 복사</button><button type="button" class="btn secondary" data-feedback-github26="${esc26(r.id)}">GitHub 이슈로 보내기</button></div>`}
  function findReport26(id){return read26().find(x=>x.id===id)}
  function renderHistory26(){const box=q('#feedbackHistoryBox26'),rows=read26().slice().reverse();box.hidden=false;box.innerHTML=`<div class="feedback-history-head26"><b>이 기기의 최근 신고</b><span>${rows.length}건 · 최대 ${MAX_REPORTS26}건 보관</span></div>${rows.length?rows.map(r=>`<article class="feedback-history-item26"><div><b>${esc26(r.type)} · ${esc26(r.meta?.page||'화면')}</b><span>${esc26(new Date(r.createdAt).toLocaleString('ko-KR'))}</span><small>${esc26(r.problem)}</small></div><div><button type="button" class="linkbtn" data-feedback-share26="${esc26(r.id)}">공유</button><button type="button" class="linkbtn danger-text" data-feedback-del26="${esc26(r.id)}">삭제</button></div></article>`).join(''):'<div class="empty">아직 저장된 신고가 없습니다.</div>'}
  function delete26(id){write26(read26().filter(x=>x.id!==id));renderHistory26()}
  function clearForm26(){q('#feedbackAction26').value='';q('#feedbackProblem26').value='';q('#feedbackExpected26').value='';q('#feedbackPrivacy26').checked=false}
  function bind26(){if(document.body.dataset.feedbackBound26)return;document.body.dataset.feedbackBound26='1';document.body.addEventListener('click',async e=>{if(e.target.closest('#feedbackFab26')){open26();return}if(e.target.closest('#feedbackClose26')||e.target.closest('#feedbackCancel26')){q('#feedbackDlg26')?.close();return}if(e.target.closest('#feedbackHistory26')){renderHistory26();return}const sh=e.target.closest('[data-feedback-share26]');if(sh){const r=findReport26(sh.dataset.feedbackShare26);if(r)await share26(r);return}const cp=e.target.closest('[data-feedback-copy26]');if(cp){const r=findReport26(cp.dataset.feedbackCopy26);if(r){const ok=await copy26(reportText26(r));alert(ok?'신고 내용을 복사했습니다.':'복사하지 못했습니다.')}return}const gh=e.target.closest('[data-feedback-github26]');if(gh){const r=findReport26(gh.dataset.feedbackGithub26);if(r)window.open(githubUrl26(r),'_blank','noopener');return}const del=e.target.closest('[data-feedback-del26]');if(del){delete26(del.dataset.feedbackDel26);return}});q('#feedbackForm26').addEventListener('submit',e=>{e.preventDefault();if(!q('#feedbackPrivacy26').checked)return;const r=saveReport26();renderResult26(r);clearForm26()})}
  window.addEventListener('error',e=>{lastRuntimeError26=String(e?.message||'').slice(0,240)});
  window.addEventListener('unhandledrejection',e=>{lastRuntimeError26=String(e?.reason?.message||e?.reason||'').slice(0,240)});
  function boot26(){ensure26();const foot=q('.side-foot');if(foot)foot.textContent='v0.26 · tester feedback loop'}
  setTimeout(boot26,0);
})();
