(function(){
  const A=globalThis.TeacherOSLessonAudio,V6=globalThis.TeacherOSCoreV6;if(!A||!V6)return;
  const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)];
  const esc9=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#039;'}[m]));
  const id9=()=>crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random().toString(16).slice(2);
  let recognition=null,live=false,finalText='',startedAt=null,timer=null;
  function today(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
  function dayKo(){return ['일','월','화','수','목','금','토'][new Date().getDay()]}
  function targets(y){const out=[];(y.timetable||[]).forEach(s=>{const t=V6.normalizeScope(s.target||V6.targetFromLabel(s.label));if(t&&/^\d+-\d+$/.test(t))out.push(t)});Object.values(y.liveTimetableWeeks||{}).forEach(w=>(w.slots||[]).forEach(s=>{const t=V6.normalizeScope(s.target);if(t&&/^\d+-\d+$/.test(t))out.push(t)}));return [...new Set(out)].sort((a,b)=>a.localeCompare(b,'ko',{numeric:true}))}
  function todaysSlots(y){const d=today(),ws=(()=>{const x=new Date(d+'T00:00:00');x.setDate(x.getDate()-((x.getDay()+6)%7));return todayFrom(x)})();const livew=y.liveTimetableWeeks?.[ws];if(livew)return (livew.slots||[]).filter(s=>s.date===d).sort((a,b)=>a.period-b.period);return (y.timetable||[]).filter(s=>s.day===dayKo()).sort((a,b)=>a.period-b.period)}
  function todayFrom(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
  function ensureUI(){
    const nav=q('#nav');if(nav&&!nav.querySelector('[data-view="lessonlog"]'))nav.querySelector('[data-view="progress"]')?.insertAdjacentHTML('afterend','<button data-view="lessonlog">◉ <span>수업기록</span></button>');
    if(!q('#lessonlog'))q('#assessment')?.insertAdjacentHTML('beforebegin',`<section id="lessonlog" class="view"><div class="section-intro"><div><span class="kicker">LESSON AUDIO LOG</span><h2>수업 음성으로 진도 자동기록</h2><p class="muted">수업 시작 때 켜고 끝날 때 종료하면 실제 수업 내용을 분석해 반별 진도를 자동 갱신합니다.</p></div></div><div class="notice privacy-rule"><b>개인정보 보호 기본값:</b> 원음과 전체 대화문은 Teacher OS에 저장하지 않습니다. 분석 후 날짜·반·핵심 수업주제·진도만 남깁니다. 브라우저 음성인식 기능은 브라우저/기기 제공자의 음성 서비스를 사용할 수 있으므로 학교·교육청의 녹음 및 개인정보 지침을 확인한 뒤 사용하세요.</div><div class="lesson-capture spaced"><article class="card lesson-recorder"><div id="micStatus" class="mic-status"><span class="mic-dot"></span><div class="grow"><b id="micStatusText">마이크 꺼짐</b><div class="mini" id="micSub">수업을 시작할 때만 켜세요.</div></div><span class="recording-clock" id="recClock">00:00</span></div><div class="lesson-target-row spaced"><select class="field" id="lessonTarget"></select><input class="field" id="lessonPeriod" type="number" min="1" max="12" placeholder="교시"></div><textarea class="field lesson-transcript spaced" id="lessonTranscript" placeholder="실시간 인식된 교사 발화가 여기에 나타납니다. 브라우저 음성인식이 지원되지 않으면 직접 메모를 붙여넣어도 분석할 수 있습니다."></textarea><div class="lesson-controls"><button class="btn primary" id="lessonStart">수업 듣기 시작</button><button class="btn danger" id="lessonStop" disabled>수업 종료·자동기록</button><button class="btn secondary" id="lessonAnalyze">현재 내용만 분석</button><button class="btn secondary" id="lessonClear">지우기</button></div><p class="lesson-note" id="lessonSupport"></p></article><article class="card"><span class="kicker">AUTO RESULT</span><h3>이번 수업 분석</h3><div id="lessonResult" class="empty">아직 분석한 수업이 없습니다.</div></article></div><article class="card spaced"><div class="head"><div><h3>최근 수업기록</h3><p class="muted">전체 녹음이 아니라 진도에 필요한 최소 기록만 보관합니다.</p></div></div><div id="lessonLogList" class="lesson-log spaced"></div></article></section>`);
    const foot=q('.side-foot');if(foot)foot.textContent='v0.9 · 수업 음성 진도기록 + 자동세팅';
  }
  function migrate(){state.version=9;Object.values(state.years||{}).forEach(y=>{y.lessonLogs=Array.isArray(y.lessonLogs)?y.lessonLogs:[];y.classProgress=y.classProgress&&typeof y.classProgress==='object'?y.classProgress:{}});localStorage.setItem(KEY,JSON.stringify(state))}
  const oldSwitch=switchView;switchView=function(id){oldSwitch(id);if(id==='lessonlog'){qa('.view').forEach(x=>x.classList.toggle('active',x.id===id));qa('#nav button').forEach(x=>x.classList.toggle('active',x.dataset.view===id));q('#title').textContent='수업기록'}};
  function refreshTarget(){const y=cur();if(!y||!q('#lessonTarget'))return;const ts=targets(y),todaySlots=todaysSlots(y),first=todaySlots[0],current=q('#lessonTarget').value;q('#lessonTarget').innerHTML=ts.length?ts.map(t=>`<option value="${esc9(t)}">${esc9(t)}</option>`).join(''):'<option value="">등록된 반 없음</option>';if(current&&ts.includes(current))q('#lessonTarget').value=current;else if(first){const t=V6.normalizeScope(first.target||V6.targetFromLabel(first.label));if(ts.includes(t))q('#lessonTarget').value=t;q('#lessonPeriod').value=first.period||''}}
  function extraTerms(y){const a=[];(y.assessments||[]).forEach(x=>a.push(x.name||'',x.target||''));Object.values(y.classProgress||{}).forEach(p=>a.push(p.topic||''));return a}
  function analyzeText(){const y=cur();if(!y)return null;const r=A.analyze(q('#lessonTranscript').value,extraTerms(y)),target=V6.normalizeScope(q('#lessonTarget').value),period=Number(q('#lessonPeriod').value)||null;const ct=r.confidence==='high'?'높음':r.confidence==='medium'?'보통':'낮음';q('#lessonResult').innerHTML=`<div class="row"><div class="grow"><strong>${esc9(target||'반 미선택')} ${period?period+'교시':''}</strong><div class="mini">분석 신뢰도 <span class="confidence-${r.confidence}">${ct}</span></div></div></div><div class="spaced"><b>${esc9(r.summary)}</b></div><div class="mini spaced">${r.autoAdvance?'수업 종료 시 해당 반 진도를 자동으로 +1차시 기록합니다.':'발화량이나 수업주제 근거가 부족해 진도는 자동으로 올리지 않습니다.'}</div>`;return{...r,target,period}}
  function seconds(){return startedAt?Math.max(0,Math.round((Date.now()-startedAt)/1000)):0}
  function updateClock(){const s=seconds(),m=Math.floor(s/60),r=s%60;q('#recClock').textContent=`${String(m).padStart(2,'0')}:${String(r).padStart(2,'0')}`}
  function startRecognition(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){q('#lessonSupport').textContent='이 브라우저는 실시간 음성인식을 지원하지 않습니다. Chrome/Edge 등 지원 브라우저를 사용하거나 수업 메모를 붙여넣고 분석하세요.';return false}recognition=new SR();recognition.lang='ko-KR';recognition.continuous=true;recognition.interimResults=true;recognition.maxAlternatives=1;recognition.onresult=ev=>{let interim='';for(let i=ev.resultIndex;i<ev.results.length;i++){const t=ev.results[i][0].transcript;if(ev.results[i].isFinal)finalText+=' '+t;else interim+=t}q('#lessonTranscript').value=(finalText+' '+interim).trim();analyzeText()};recognition.onerror=ev=>{q('#lessonSupport').textContent='음성인식 상태: '+(ev.error||'오류')};recognition.onend=()=>{if(live){try{recognition.start()}catch{}}};try{recognition.start();return true}catch{return false}}
  function startLesson(){if(live||!cur())return;refreshTarget();finalText=q('#lessonTranscript').value.trim();live=true;startedAt=Date.now();q('#micStatus').classList.add('live');q('#micStatusText').textContent='수업 음성 듣는 중';q('#micSub').textContent='전체 녹음은 저장하지 않습니다.';q('#lessonStart').disabled=true;q('#lessonStop').disabled=false;timer=setInterval(updateClock,1000);updateClock();startRecognition()}
  function finishLesson(){if(!cur())return;const duration=seconds();live=false;if(timer)clearInterval(timer);timer=null;try{recognition?.stop()}catch{}recognition=null;q('#micStatus').classList.remove('live');q('#micStatusText').textContent='마이크 꺼짐';q('#micSub').textContent='분석을 마쳤습니다.';q('#lessonStart').disabled=false;q('#lessonStop').disabled=true;const r=analyzeText();if(!r)return;const y=cur(),target=r.target;if(!target){alert('반을 선택해 주세요.');return}let before=Number(y.classProgress?.[target]?.lesson)||0,after=before,advanced=false;if(r.autoAdvance){y.classProgress[target]=y.classProgress[target]||{lesson:0,topic:'',note:'',updatedAt:null};after=before+1;y.classProgress[target].lesson=after;y.classProgress[target].topic=r.keywords.slice(0,4).join(' · ')||y.classProgress[target].topic||'';y.classProgress[target].updatedAt=new Date().toISOString();advanced=true}y.lessonLogs.push({id:id9(),date:today(),target,period:r.period,durationSec:duration,summary:r.summary,keywords:r.keywords.slice(0,5),confidence:r.confidence,advanced,before,after,createdAt:new Date().toISOString()});q('#lessonTranscript').value='';finalText='';startedAt=null;localStorage.setItem(KEY,JSON.stringify(state));render();switchView('lessonlog')}
  function renderLogs(y){if(!q('#lessonLogList'))return;const logs=(y.lessonLogs||[]).slice().reverse().slice(0,30);q('#lessonLogList').innerHTML=logs.length?logs.map(l=>`<div class="lesson-log-item"><div class="meta"><span class="pill">${esc9(l.target)}</span><span>${esc9(l.date)}${l.period?' · '+l.period+'교시':''}</span><span class="confidence-${esc9(l.confidence)}">${l.confidence==='high'?'신뢰 높음':l.confidence==='medium'?'신뢰 보통':'신뢰 낮음'}</span></div><b>${esc9(l.summary)}</b><div class="mini spaced">${l.advanced?`진도 ${l.before} → ${l.after}차시 자동 반영`:'진도 자동 반영 안 함'} · 수업 음성 약 ${Math.max(1,Math.round((l.durationSec||0)/60))}분</div>${l.advanced&&!l.undone?`<button class="linkbtn spaced" data-lesson-undo="${l.id}">진도 반영 취소</button>`:''}</div>`).join(''):'<div class="empty">아직 수업기록이 없습니다.</div>'}
  function bind(){q('#lessonStart').onclick=startLesson;q('#lessonStop').onclick=finishLesson;q('#lessonAnalyze').onclick=analyzeText;q('#lessonClear').onclick=()=>{q('#lessonTranscript').value='';finalText='';q('#lessonResult').innerHTML='<div class="empty">아직 분석한 수업이 없습니다.</div>'};q('#lessonLogList').onclick=ev=>{const b=ev.target.closest('[data-lesson-undo]');if(!b)return;const y=cur(),l=y.lessonLogs.find(x=>x.id===b.dataset.lessonUndo);if(!l||l.undone)return;const p=y.classProgress?.[l.target];if(p&&Number(p.lesson)>0)p.lesson=Math.max(0,Number(p.lesson)-1);l.undone=true;l.advanced=false;save()};const SR=window.SpeechRecognition||window.webkitSpeechRecognition;q('#lessonSupport').textContent=SR?'실시간 음성인식 지원 브라우저입니다. 수업 종료 시 전체 대화문은 폐기됩니다.':'실시간 음성인식 미지원 브라우저입니다. 현재는 수업 메모를 붙여넣어 분석할 수 있습니다.'}
  const prevRender=render;render=function(){migrate();prevRender();const y=cur();if(y){refreshTarget();renderLogs(y)}else if(q('#lessonLogList'))q('#lessonLogList').innerHTML='<div class="empty">학년도를 먼저 만들어 주세요.</div>'};
  ensureUI();migrate();bind();render();
})();
