const KEY='myTeacherOS.v01';
const C=globalThis.TeacherOSCore;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],arr=C.arr;
const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random().toString(16).slice(2);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const OFFICES={
 '서울특별시교육청':'https://www.sen.go.kr/','부산광역시교육청':'https://www.pen.go.kr/','대구광역시교육청':'https://www.dge.go.kr/','인천광역시교육청':'https://www.ice.go.kr/','광주광역시교육청':'https://www.gen.go.kr/','대전광역시교육청':'https://www.dje.go.kr/','울산광역시교육청':'https://www.use.go.kr/','세종특별자치시교육청':'https://www.sje.go.kr/','경기도교육청':'https://www.goe.go.kr/','강원특별자치도교육청':'https://www.gwe.go.kr/','충청북도교육청':'https://www.cbe.go.kr/','충청남도교육청':'https://www.cne.go.kr/','전북특별자치도교육청':'https://www.jbe.go.kr/','전라남도교육청':'https://www.jne.go.kr/','경상북도교육청':'https://www.gbe.kr/','경상남도교육청':'https://www.gne.go.kr/','제주특별자치도교육청':'https://www.jje.go.kr/'
};
const fallbackPolicy={lastChecked:'2026-08-21',national:{curriculum2022:{title:'교육부 2022 개정 교육과정 시행 일정',url:'https://www.moe.go.kr/boardCnts/viewRenew.do?boardID=141&boardSeq=93458&lev=0&m=040401'},highSchoolCredit:{title:'교육부 고교학점제 종합 추진계획',url:'https://www.moe.go.kr/boardCnts/viewRenew.do?boardID=294&boardSeq=88188&lev=0&m=020402&opType=N&s=moe&statusYN=W'}},offices:{}};
let policyRegistry=fallbackPolicy,suggestions=[],lastSelfTest=null;
const fresh=()=>({version:5,currentYear:null,profile:{major:'음악',minutes:45},years:{}});
let state=(()=>{try{return JSON.parse(localStorage.getItem(KEY))||fresh()}catch{return fresh()}})();
function localISODate(d=new Date()){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function defaultClubs(){return[{id:uid(),name:'국제교류 자율동아리',type:'국제교류',goal:'해외 학교 학생들과 국제교류 활동 운영',due:'',activities:[]},{id:uid(),name:'밴드 자율동아리',type:'밴드',goal:'학생 주도 합주와 공연 운영',due:'',activities:[]}]}
function yearObj(n,l='중학교',s='',office='경기도교육청'){return{year:Number(n),schoolLevel:l,schoolName:s,educationOffice:office,subjects:['음악'],projects:[],clubs:defaultClubs(),assessments:[],memories:[],tasks:[],calendarEvents:[],timetable:[],imports:[],lastBackupAt:null}}
function migrate(){
 state=state&&typeof state==='object'?state:fresh();state.version=5;state.years=state.years||{};
 Object.values(state.years).forEach(y=>{y.projects=arr(y.projects);y.assessments=arr(y.assessments);y.memories=arr(y.memories);y.tasks=arr(y.tasks);y.calendarEvents=arr(y.calendarEvents);y.timetable=arr(y.timetable);y.imports=arr(y.imports);y.clubs=arr(y.clubs);if(!y.clubs.length)y.clubs=defaultClubs();if(!y.educationOffice)y.educationOffice='경기도교육청';if(!arr(y.subjects).length)y.subjects=['음악'];if(y.lastBackupAt===undefined)y.lastBackupAt=null});
 localStorage.setItem(KEY,JSON.stringify(state));
}
function cur(){return state.currentYear?state.years[state.currentYear]:null}
function save(){localStorage.setItem(KEY,JSON.stringify(state));render()}
function dueText(d){const n=C.dueDays(d);if(n===null)return'';if(n===0)return'오늘';return n>0?`D-${n}`:`${Math.abs(n)}일 지남`}
function openDlg(id){$(id).showModal()}function closeDlgs(){$$('dialog[open]').forEach(d=>d.close())}
function ensureYear(){if(cur())return true;openYear('first');return false}
function switchView(id){$$('.view').forEach(x=>x.classList.toggle('active',x.id===id));$$('#nav button').forEach(x=>x.classList.toggle('active',x.dataset.view===id));$('#title').textContent=({dashboard:'오늘',importer:'자동세팅',calendar:'학사일정',timetable:'시간표',assessment:'수업·평가',clubs:'동아리',projects:'행정업무',policy:'교육과정·지침',documents:'자료함',memory:'업무기억',settings:'백업·점검'})[id]||id}
async function loadPolicyRegistry(){try{const r=await fetch('./policy-registry.json?v='+Date.now(),{cache:'no-store'});if(r.ok)policyRegistry=await r.json()}catch{}render()}
function policyInfo(y){
 const office=y.educationOffice||'경기도교육청',year=String(y.year),officeData=policyRegistry.offices?.[office]||{},yearData=officeData[year]||{};
 const sources=[];
 if(policyRegistry.national?.curriculum2022)sources.push({...policyRegistry.national.curriculum2022,status:'국가 기준'});
 if(C.creditMode(y.year,y.schoolLevel)&&policyRegistry.national?.highSchoolCredit)sources.push({...policyRegistry.national.highSchoolCredit,status:'국가 기준'});
 ['gradeManagement','middleCurriculum','highCurriculum','creditSupport'].forEach(k=>{const s=yearData[k];if(s&&((k!=='middleCurriculum'||y.schoolLevel==='중학교')&&(k!=='highCurriculum'||y.schoolLevel==='고등학교')))sources.push({...s,status:'해당 연도 공식'})});
 if(!Object.keys(yearData).length&&OFFICES[office])sources.push({title:`${office} 공식 누리집 · ${y.year}학년도 지침 확인`,url:OFFICES[office],status:'업데이트 확인 필요'});
 const pending=yearData.status==='pending'||(!yearData.gradeManagement&&Number(y.year)>=2027);
 return {office,sources,pending,curriculum:C.curriculumMode(y.year,y.schoolLevel),credit:C.creditMode(y.year,y.schoolLevel)};
}
function renderPolicy(y){
 const p=policyInfo(y),checked=policyRegistry.lastChecked||'미상';
 $('#policyBanner').innerHTML=`<div class="head"><div><span class="pill">자동 적용</span><h3>${esc(p.curriculum)}</h3><div class="profile-line"><span>${esc(p.office)}</span><span>${esc(y.schoolLevel)}</span>${p.credit?'<span>고교학점제 모드</span>':''}</div></div><button class="btn secondary tiny" data-go-policy>기준 보기</button></div>`;
 $('#assessmentPolicy').innerHTML=`<b>${esc(y.year)}학년도 평가:</b> ${esc(p.office)}의 해당 연도 학업성적관리 시행지침과 단위학교 규정을 최종 기준으로 확인합니다. ${p.pending?'<span class="status-warn">해당 연도 세부 지침 업데이트 확인이 필요합니다.</span>':''}`;
 $('#policySummary').innerHTML=`<article class="card policy-card"><span class="kicker">CURRICULUM</span><strong>${esc(p.curriculum)}</strong><div class="mini">학년도·학교급 자동 판정</div></article><article class="card policy-card"><span class="kicker">HIGH SCHOOL CREDIT</span><strong>${p.credit?'고교학점제 모드':'해당 없음'}</strong><div class="mini">고등학교 2025학년도 이후 활성화</div></article><article class="card policy-card"><span class="kicker">LOCAL RULE</span><strong>${esc(p.office)}</strong><div class="mini">평가·성적관리 세부는 연도별 최신 지침 우선</div></article>`;
 $('#policySources').innerHTML=p.sources.length?p.sources.map(s=>`<div class="policy-source"><div class="grow"><a class="source-link" href="${esc(s.url)}" target="_blank" rel="noopener">${esc(s.title)}</a><div class="mini">${esc(s.effective?'적용: '+s.effective:'')}</div></div><span class="pill ${s.status.includes('필요')?'warn':''}">${esc(s.status)}</span></div>`).join(''):'<div class="empty">등록된 공식 출처가 없습니다.</div>';
 $('#policyChecked').textContent='정책 확인 '+checked;
 $('#policyWarning').innerHTML=p.pending?`<b>${esc(y.year)}학년도 최신 교육청 지침 확인 필요.</b> 아직 정책 레지스트리에 해당 연도 학업성적관리 지침이 등록되지 않았습니다. 자동 유지관리에서 공식 발표 여부를 계속 확인합니다.`:`<b>공식 자료 기준.</b> 정책 레지스트리는 ${esc(checked)} 기준으로 확인되었습니다.`;
}
function allUpcoming(y){let a=[];y.calendarEvents.forEach(e=>a.push({date:e.date,title:e.title,type:e.type||'학교'}));y.assessments.forEach(e=>e.due&&a.push({date:e.due,title:e.name,type:'평가'}));y.projects.forEach(e=>e.due&&a.push({date:e.due,title:e.name,type:'행정'}));y.clubs.forEach(e=>e.due&&a.push({date:e.due,title:e.name,type:'동아리'}));return a.filter(x=>x.date&&C.dueDays(x.date)>=0).sort((a,b)=>a.date.localeCompare(b.date))}
function renderNext(y){const a=allUpcoming(y).slice(0,10);$('#nextList').innerHTML=a.length?a.map(x=>`<div class="row"><div class="calendar-date">${esc(x.date)}</div><div class="grow"><strong>${esc(x.title)}</strong><div class="mini">${esc(x.type)} · ${dueText(x.date)}</div></div></div>`).join(''):'<div class="empty">다가오는 일정이 없습니다.</div>'}
function renderCalendar(y){const a=y.calendarEvents.slice().sort((a,b)=>(a.date||'').localeCompare(b.date||''));$('#calendarList').innerHTML=a.length?a.map(e=>`<div class="row"><div class="calendar-date">${esc(e.date)}</div><div class="grow"><strong>${esc(e.title)}</strong><div class="mini">${esc(e.type||'학교')} · ${esc(e.source||'예외 입력')}</div></div><button class="linkbtn danger-text" data-cal-del="${e.id}">삭제</button></div>`).join(''):'<div class="empty">자동세팅에서 학교 학사일정 자료를 올리세요.</div>'}
function renderTimetable(y){
 const days=C.WEEKDAYS,maxPeriod=Math.max(7,...y.timetable.map(x=>Number(x.period)||0));let h='<thead><tr><th>교시</th>'+days.map(d=>`<th>${d}</th>`).join('')+'</tr></thead><tbody>';
 for(let p=1;p<=maxPeriod;p++){h+=`<tr><td><b>${p}</b></td>`+days.map(d=>{const slots=y.timetable.filter(x=>x.day===d&&Number(x.period)===p);return `<td>${slots.map(s=>`<div class="slot">${esc(s.label)}</div>`).join('')}</td>`}).join('')+'</tr>'}h+='</tbody>';$('#timetableTable').innerHTML=y.timetable.length?h:'<tbody><tr><td class="empty">자동세팅에서 교사 시간표 Excel/CSV를 올리세요.</td></tr></tbody>';
 const wd=['일','월','화','수','목','금','토'][new Date().getDay()],today=y.timetable.filter(x=>x.day===wd).sort((a,b)=>a.period-b.period);$('#todayTimetable').innerHTML=today.length?today.map(x=>`<span>${x.period}교시 · ${esc(x.label)}</span>`).join(''):'<span class="muted">오늘 등록된 수업이 없습니다.</span>';
}
function renderFlow(y){
 const upcoming=y.assessments.filter(a=>a.due&&C.dueDays(a.due)>=0).sort((a,b)=>a.due.localeCompare(b.due)).slice(0,8);
 $('#flowList').innerHTML=upcoming.length?upcoming.map(a=>{const n=C.countTeachingSlots(y.timetable,y.calendarEvents,a.target||'',localISODate(),a.due);return `<div class="row"><div class="grow"><strong>${esc(a.name)}</strong><div class="mini">${esc(a.target||'대상 미확인')} · ${esc(a.due)} · 평가까지 수업 약 <b>${n}회</b></div></div></div>`}).join(''):'<div class="empty">날짜가 있는 평가 항목이 없습니다.</div>';
}
function renderAssess(y){$('#assItems').innerHTML=y.assessments.length?y.assessments.map(a=>{const n=a.due?C.countTeachingSlots(y.timetable,y.calendarEvents,a.target||'',localISODate(),a.due):null;return `<div class="row"><div class="grow"><strong>${esc(a.name)}</strong><div class="mini">${esc(a.target||'대상 미확인')} ${a.weight?'· '+esc(a.weight):''} ${a.due?'· '+esc(a.due)+' · 남은 수업 추정 '+n+'회':''}</div><div class="source">${esc(a.source||'')}</div></div><button class="linkbtn danger-text" data-ass-del="${a.id}">삭제</button></div>`}).join(''):'<div class="empty">평가계획서를 자동세팅에서 올리세요.</div>'}
function renderClubs(y){$('#clubGrid').innerHTML=y.clubs.length?y.clubs.map(c=>`<article class="card project"><span class="pill blue">${c.type==='국제교류'?'🌏':c.type==='밴드'?'🎸':'♬'} ${esc(c.type||'동아리')}</span><h3>${esc(c.name)}</h3><p class="muted">${esc(c.goal||'')}</p><div class="mini due">${c.due?esc(c.due)+' · '+dueText(c.due):'다음 일정 미정'}</div></article>`).join(''):'<div class="empty">동아리가 없습니다.</div>'}
function renderProjects(y){$('#projectGrid').innerHTML=y.projects.length?y.projects.map(p=>`<article class="card project"><span class="pill">행정</span><h3>${esc(p.name)}</h3><p class="muted">${esc(p.desc||'')}</p><div class="mini due">${p.due?esc(p.due)+' · '+dueText(p.due):'마감 미정'}</div><div class="source">${esc(p.source||'')}</div></article>`).join(''):'<div class="empty">업무분장표나 공문을 자동세팅에서 올리세요.</div>'}
function renderSources(y){$('#sourceList').innerHTML=y.imports.length?y.imports.slice().reverse().map(f=>`<div class="row"><div class="grow"><strong>${esc(f.name)}</strong><div class="mini">${esc(f.kind||'자동분석')} · ${esc(f.when||'')} · 원문 미저장</div></div></div>`).join(''):'<div class="empty">분석한 원본 자료가 없습니다.</div>'}
function renderMemory(y){$('#memoryList').innerHTML=y.memories.length?y.memories.slice().reverse().map(m=>`<div class="row"><div class="grow"><strong>${esc(m.note)}</strong><div class="mini">다음: ${esc(m.improve||'')}</div></div><button class="linkbtn danger-text" data-mem-del="${m.id}">삭제</button></div>`).join(''):'<div class="empty">다음 해에 재사용할 업무기억이 없습니다.</div>'}
function renderTasks(y){$('#taskList').innerHTML=y.tasks.length?y.tasks.map(t=>`<div class="row task ${t.done?'done':''}"><input type="checkbox" data-task="${t.id}" ${t.done?'checked':''}><div class="grow">${esc(t.text)}</div><button class="linkbtn danger-text" data-task-del="${t.id}">삭제</button></div>`).join(''):'<div class="empty">문서에 없는 임시 할 일만 적으세요.</div>'}
function renderHealth(y){
 const backupDays=y.lastBackupAt?Math.floor((Date.now()-new Date(y.lastBackupAt).getTime())/86400000):null;const policyAge=policyRegistry.lastChecked?Math.floor((Date.now()-new Date(policyRegistry.lastChecked+'T00:00:00').getTime())/86400000):null;
 const tests=lastSelfTest?.ok?'통과':lastSelfTest?'오류':'미실행';
 $('#healthGrid').innerHTML=`<div class="health"><span class="mini">브라우저 저장</span><b class="status-ok">정상</b></div><div class="health"><span class="mini">마지막 백업</span><b class="${backupDays===null||backupDays>14?'status-warn':'status-ok'}">${backupDays===null?'없음':backupDays+'일 전'}</b></div><div class="health"><span class="mini">정책 확인</span><b class="${policyAge!==null&&policyAge<=90?'status-ok':'status-warn'}">${policyRegistry.lastChecked||'미상'}</b></div><div class="health"><span class="mini">핵심 테스트</span><b class="${tests==='통과'?'status-ok':'status-warn'}">${tests}</b></div>`;
 $('#backupInfo').textContent=y.lastBackupAt?'마지막 JSON 백업: '+new Date(y.lastBackupAt).toLocaleString('ko-KR'):'아직 JSON 백업을 받지 않았습니다.';
}
function render(){
 const y=cur(),years=Object.keys(state.years).sort((a,b)=>b-a);$('#yearSelect').innerHTML=years.length?years.map(k=>`<option value="${k}" ${String(state.currentYear)===String(k)?'selected':''}>${k}학년도</option>`).join(''):'<option>학년도 없음</option>';$('#firstHero').hidden=!!y;$('#dashboardBody').style.display=y?'block':'none';
 if(!y){['nextList','calendarList','assItems','clubGrid','projectGrid','sourceList','memoryList','flowList','todayTimetable'].forEach(id=>$('#'+id).innerHTML='<div class="empty">학년도를 먼저 만들어 주세요.</div>');$('#timetableTable').innerHTML='';$('#policySummary').innerHTML='<div class="empty">학년도를 먼저 만들어 주세요.</div>';$('#policySources').innerHTML='';$('#healthGrid').innerHTML='';return}
 ['projects','assessments','memories','tasks','calendarEvents','timetable','imports','clubs'].forEach(k=>y[k]=arr(y[k]));
 $('#mEnv').textContent=[y.schoolLevel,y.schoolName].filter(Boolean).join(' · ')||y.schoolLevel||'-';$('#mCal').textContent=y.calendarEvents.length+'개';$('#mTT').textContent=y.timetable.length+'칸';$('#mAss').textContent=y.assessments.length+'개';$('#mClub').textContent=y.clubs.length+'개';$('#mProj').textContent=y.projects.length+'개';
 renderPolicy(y);renderNext(y);renderCalendar(y);renderTimetable(y);renderFlow(y);renderAssess(y);renderClubs(y);renderProjects(y);renderSources(y);renderMemory(y);renderTasks(y);renderHealth(y);
}
function openYear(mode='new'){
 const y=cur(),base=mode==='first'?null:y;const proposed=mode==='new'?(y?Number(y.year)+1:new Date().getFullYear()):(y?.year||new Date().getFullYear());$('#yYear').value=proposed;$('#yLevel').value=base?.schoolLevel||'중학교';$('#yOffice').innerHTML=Object.keys(OFFICES).map(o=>`<option ${o===(base?.educationOffice||'경기도교육청')?'selected':''}>${esc(o)}</option>`).join('');$('#ySchool').value=base?.schoolName||'';$('#carryPrev').checked=true;openDlg('#yearDlg')
}
function cloneCarry(prev){return{clubs:arr(prev?.clubs).map(c=>({id:uid(),name:c.name,type:c.type,goal:c.goal||'',due:'',activities:[]})),memories:arr(prev?.memories).map(m=>({...m,id:uid(),carried:true}))}}
function conflictMessages(y){
 const out=[],p=policyInfo(y);if(p.pending)out.push(`${y.year}학년도 ${p.office} 최신 학업성적관리 지침 업데이트 확인 필요`);if(!y.calendarEvents.length)out.push('학사일정 자료가 아직 없습니다. 수업·평가 일정 판단 정확도가 낮습니다.');if(y.assessments.length&&!y.timetable.length)out.push('평가가 있지만 시간표가 없어 평가 전 남은 수업 횟수를 계산할 수 없습니다.');
 y.assessments.filter(a=>a.due).forEach(a=>{const same=y.calendarEvents.find(e=>e.date===a.due&&C.isNoClassEvent(e));if(same)out.push(`일정 충돌 후보: ${a.name} ↔ ${same.title} (${a.due})`)});
 const bd=y.lastBackupAt?Math.floor((Date.now()-new Date(y.lastBackupAt))/86400000):999;if(bd>14)out.push('브라우저 데이터 백업이 14일 이상 없거나 아직 없습니다.');
 allUpcoming(y).filter(x=>C.dueDays(x.date)<=14).slice(0,7).forEach(x=>out.push(`${x.type} · ${x.title}: ${dueText(x.date)}`));return out;
}
function runAgent(){const y=cur();if(!y)return;const msgs=conflictMessages(y);$('#agentResult').innerHTML=msgs.length?msgs.slice(0,12).map(x=>'• '+esc(x)).join('<br>'):'현재 등록 데이터에서는 특별한 경고를 찾지 못했습니다.'}
function textSuggestions(text,source,hint,year){
 const lines=String(text||'').replace(/\r/g,'').split('\n').map(x=>x.trim()).filter(Boolean),res=[];
 const office=C.detectOffice(text,Object.keys(OFFICES));if(office)res.push({id:uid(),checked:true,kind:'profile',profileType:'office',title:office,source,confidence:.99});const school=C.detectSchoolName(text);if(school)res.push({id:uid(),checked:true,kind:'profile',profileType:'school',title:school,source,confidence:.88});
 lines.forEach(line=>{const ds=C.findDates(line,year);ds.forEach(d=>{const kind=C.classifyLine(line,hint),title=C.cleanTitle(line,d.raw),weight=kind==='assessment'?C.extractWeight(line):'',target=kind==='assessment'?C.extractTarget(line):'';let confidence=.74;if(hint&&hint!=='auto')confidence=.93;else if(kind==='assessment'&&/수행평가|지필평가|평가계획/.test(line))confidence=.9;else if(kind==='admin'&&/업무분장|제출|마감/.test(line))confidence=.87;res.push({id:uid(),checked:confidence>=.7,kind,date:d.date,title,source,raw:line,weight,target,confidence})});
   if(!ds.length&&(hint==='admin'||(hint==='auto'&&/업무분장|담당 업무|담당자/.test(line)))&&line.length>=4&&line.length<=100){res.push({id:uid(),checked:false,kind:'admin',date:'',title:line.slice(0,100),source,raw:line,confidence:.55})}
 });return C.dedupe(res,x=>`${x.kind}|${x.date||''}|${x.title}|${x.profileType||''}`)
}
async function readTextFile(file){const ext=file.name.split('.').pop().toLowerCase();if(['txt','csv','ics'].includes(ext))return await file.text();if(['xlsx','xls'].includes(ext)){const ab=await file.arrayBuffer(),wb=XLSX.read(ab,{type:'array',cellDates:false});return wb.SheetNames.map(n=>XLSX.utils.sheet_to_csv(wb.Sheets[n])).join('\n')}if(ext==='docx'){const r=await mammoth.extractRawText({arrayBuffer:await file.arrayBuffer()});return r.value}if(ext==='hwpx'){const zip=await JSZip.loadAsync(await file.arrayBuffer());const names=Object.keys(zip.files).filter(n=>/Contents\/section\d+\.xml$/i.test(n));let s='';for(const n of names)s+='\n'+(await zip.file(n).async('text')).replace(/<[^>]+>/g,' ');return s}if(ext==='pdf'){const pdfjs=await import('https://cdn.jsdelivr.net/npm/pdfjs-dist@4.8.69/build/pdf.min.mjs');pdfjs.GlobalWorkerOptions.workerSrc='https://cdn.jsdelivr.net/npm/pdfjs-dist@4.8.69/build/pdf.worker.min.mjs';const doc=await pdfjs.getDocument({data:new Uint8Array(await file.arrayBuffer())}).promise;let out='';for(let i=1;i<=doc.numPages;i++){const p=await doc.getPage(i),c=await p.getTextContent();out+='\n'+c.items.map(x=>x.str).join(' ')}return out}throw new Error('지원하지 않는 형식')}
async function spreadsheetRows(file){const ext=file.name.split('.').pop().toLowerCase();if(!['xlsx','xls','csv'].includes(ext))return[];const data=ext==='csv'?await file.text():await file.arrayBuffer(),wb=XLSX.read(data,{type:ext==='csv'?'string':'array',cellDates:false});let best=[];wb.SheetNames.forEach(n=>{const rows=XLSX.utils.sheet_to_json(wb.Sheets[n],{header:1,defval:''});if(rows.length>best.length)best=rows});return best}
function parseICS(text,source){const r=[];for(const block of String(text).split('BEGIN:VEVENT').slice(1)){const dt=(block.match(/DTSTART(?:;[^:]*)?:(\d{8})/)||[])[1],sum=(block.match(/SUMMARY:(.*)/)||[])[1];if(dt&&sum)r.push({id:uid(),checked:true,kind:'calendar',date:`${dt.slice(0,4)}-${dt.slice(4,6)}-${dt.slice(6,8)}`,title:sum.trim(),source,confidence:.99})}return r}
function confidenceLabel(n){return n>=.9?['높음','high']:n>=.7?['보통','mid']:['검토','low']}
function renderSuggestions(){if(!suggestions.length){$('#suggestions').innerHTML='<div class="empty">추출된 항목이 없습니다.</div>';return}$('#suggestions').innerHTML=suggestions.map(s=>{const [ct,cc]=confidenceLabel(s.confidence||.5),kind=s.kind==='calendar'?'학사':s.kind==='timetable'?'시간표':s.kind==='assessment'?'평가':s.kind==='admin'?'행정':'환경';const detail=s.kind==='timetable'?`${s.day} ${s.period}교시`:s.kind==='profile'?(s.profileType==='office'?'교육청':'학교명'):(s.date||'날짜 없음');return `<label class="suggestion"><input type="checkbox" data-sg="${s.id}" ${s.checked?'checked':''}><span class="tag ${s.kind==='timetable'?'timetable':''}">${kind}</span><span class="sg-date">${esc(detail)}</span><span class="sg-title"><b>${esc(s.title||s.label)}</b><div class="source">${esc(s.source)}${s.weight?' · '+esc(s.weight):''}${s.target?' · '+esc(s.target):''}</div></span><span class="confidence ${cc}">${ct}</span></label>`}).join('')}
async function analyzeFiles(){
 if(!ensureYear())return;const files=[...$('#importFiles').files];if(!files.length){alert('파일을 선택해 주세요.');return}const hint=$('#importHint').value,y=cur();$('#importStatus').textContent='자료를 읽고 구조화하는 중...';let add=[],privacy=[];
 for(const f of files){try{const ext=f.name.split('.').pop().toLowerCase(),text=await readTextFile(f);privacy.push(...C.privacySignals(text).map(x=>`${f.name}: ${x}`));let got=ext==='ics'?parseICS(text,f.name):textSuggestions(text,f.name,hint,y.year);const rows=await spreadsheetRows(f);if(rows.length&&(hint==='timetable'||hint==='auto')){const tt=C.parseTimetableGrid(rows,'음악');got.push(...tt.map(x=>({id:uid(),checked:true,kind:'timetable',title:x.label,label:x.label,day:x.day,period:x.period,target:x.target,source:f.name,confidence:.96})))}add.push(...got);if(!y.imports.some(x=>x.name===f.name))y.imports.push({id:uid(),name:f.name,kind:hint==='auto'?'자동판별':hint,when:new Date().toLocaleString('ko-KR')})}catch(e){add.push({id:uid(),checked:false,kind:'calendar',date:'',title:`${f.name} 분석 실패: ${e.message}`,source:f.name,confidence:.1})}}
 suggestions=C.dedupe([...suggestions,...add],x=>`${x.kind}|${x.date||''}|${x.day||''}|${x.period||''}|${x.title}|${x.profileType||''}`);$('#importStatus').textContent=`${files.length}개 파일에서 ${add.length}개 후보를 찾았습니다.`;$('#privacyNotice').hidden=!privacy.length;$('#privacyNotice').innerHTML=privacy.length?`<b>개인정보 형태 감지:</b> ${esc([...new Set(privacy)].join(' / '))}. 원문은 저장하지 않지만, 민감 정보가 포함된 파일은 가능하면 학생정보를 제거한 사본을 사용하세요.`:'';renderSuggestions();save()
}
function applySuggestions(){const y=cur();if(!y)return;const sel=suggestions.filter(x=>x.checked);sel.forEach(s=>{if(s.kind==='profile'){if(s.profileType==='office')y.educationOffice=s.title;if(s.profileType==='school'&&!y.schoolName)y.schoolName=s.title;return}if(s.kind==='calendar'&&s.date&&!y.calendarEvents.some(e=>e.date===s.date&&e.title===s.title))y.calendarEvents.push({id:uid(),date:s.date,title:s.title,type:'학교',source:s.source});if(s.kind==='timetable'&&!y.timetable.some(t=>t.day===s.day&&t.period===s.period&&t.label===s.title))y.timetable.push({id:uid(),day:s.day,period:s.period,label:s.title,target:s.target||C.extractTarget(s.title),source:s.source});if(s.kind==='assessment'&&!y.assessments.some(a=>a.name===s.title&&a.due===s.date))y.assessments.push({id:uid(),name:s.title,target:s.target||'',weight:s.weight||'',due:s.date||'',source:s.source});if(s.kind==='admin'&&!y.projects.some(p=>p.name===s.title&&p.due===(s.date||'')))y.projects.push({id:uid(),name:s.title,desc:'',due:s.date||'',source:s.source})});suggestions=suggestions.filter(x=>!x.checked);renderSuggestions();save();switchView('dashboard')}
function exportICS(){const y=cur();if(!y)return;const events=C.dedupe([...y.calendarEvents,...y.assessments.filter(a=>a.due).map(a=>({date:a.due,title:'[평가] '+a.name})),...y.projects.filter(p=>p.due).map(p=>({date:p.due,title:'[행정] '+p.name})),...y.clubs.filter(c=>c.due).map(c=>({date:c.due,title:'[동아리] '+c.name}))],x=>`${x.date}|${x.title}`);const lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//MY TEACHER OS//KO'];events.forEach(e=>{const d=e.date.replaceAll('-','');lines.push('BEGIN:VEVENT','UID:'+uid()+'@my-teacher-os','DTSTART;VALUE=DATE:'+d,'SUMMARY:'+String(e.title).replace(/[\n,;]/g,' '),'END:VEVENT')});lines.push('END:VCALENDAR');downloadBlob(new Blob([lines.join('\r\n')],{type:'text/calendar;charset=utf-8'}),`teacher-os-${y.year}.ics`)}
function downloadBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function exportJSON(){const y=cur();if(y)y.lastBackupAt=new Date().toISOString();localStorage.setItem(KEY,JSON.stringify(state));downloadBlob(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),`my-teacher-os-backup-${localISODate()}.json`);render()}
async function importJSON(file){try{const obj=JSON.parse(await file.text());if(!obj||typeof obj!=='object'||!obj.years)throw new Error('Teacher OS 백업 형식이 아닙니다.');if(!confirm('현재 브라우저 데이터를 백업 파일로 교체할까요?'))return;state=obj;migrate();render();alert('복구했습니다.')}catch(e){alert('복구 실패: '+e.message)}}
function runSelfTests(){const tests=[];const t=(name,fn)=>{try{fn();tests.push({name,ok:true})}catch(e){tests.push({name,ok:false,msg:e.message})}};t('2027 중학교 전 학년 2022 개정',()=>{if(C.curriculumMode(2027,'중학교')!=='2022 개정 교육과정 · 전 학년 적용')throw Error('교육과정 판정')});t('고교학점제 모드',()=>{if(!C.creditMode(2025,'고등학교')||C.creditMode(2025,'중학교'))throw Error('학점제 판정')});t('날짜 파싱',()=>{if(C.findDates('9월 3일 학교축제',2026)[0]?.date!=='2026-09-03')throw Error('날짜')});t('반영비율 파싱',()=>{if(C.extractWeight('반영 30%')!=='30%')throw Error('비율')});t('시간표 파싱',()=>{const r=C.parseTimetableGrid([['교시','월','화','수','목','금'],['1교시','2-1','','2-3','','']],'음악');if(r.length!==2)throw Error('시간표')});t('개인정보 감지',()=>{if(!C.privacySignals('010-1234-5678').length)throw Error('개인정보')});lastSelfTest={ok:tests.every(x=>x.ok),tests,at:new Date().toISOString()};$('#selfTestResult').innerHTML=tests.map(x=>`<div class="row"><span class="${x.ok?'status-ok':'status-bad'}">${x.ok?'PASS':'FAIL'}</span><div class="grow">${esc(x.name)} ${x.msg?'· '+esc(x.msg):''}</div></div>`).join('');renderHealth(cur())}
function openSimple(kind){$('#simpleKind').value=kind;$('#simpleTitle').textContent=kind==='club'?'예외 동아리':'예외 행정업무';$('#simpleName').value='';$('#simpleMemo').value='';$('#simpleDue').value='';openDlg('#simpleDlg')}
function initEvents(){
 $('#nav').addEventListener('click',e=>{const b=e.target.closest('button[data-view]');if(b)switchView(b.dataset.view)});document.body.addEventListener('click',e=>{if(e.target.closest('[data-go-policy]'))switchView('policy')});
 $('#yearSelect').onchange=e=>{if(state.years[e.target.value]){state.currentYear=e.target.value;save()}};$('#editYear').onclick=()=>openYear('edit');$('#newYear').onclick=()=>openYear('new');$('#firstYear').onclick=()=>openYear('first');
 $('#yearForm').onsubmit=e=>{e.preventDefault();const yr=String($('#yYear').value),prev=cur(),exists=state.years[yr];let y=exists||yearObj(Number(yr),$('#yLevel').value,$('#ySchool').value.trim(),$('#yOffice').value);if(!exists&&$('#carryPrev').checked&&prev){const carry=cloneCarry(prev);y.clubs=carry.clubs.length?carry.clubs:defaultClubs();y.memories=carry.memories}y.year=Number(yr);y.schoolLevel=$('#yLevel').value;y.educationOffice=$('#yOffice').value;y.schoolName=$('#ySchool').value.trim();state.years[yr]=y;state.currentYear=yr;closeDlgs();save()};
 $('#analyzeBtn').onclick=analyzeFiles;$('#applySuggestions').onclick=applySuggestions;$('#suggestions').onchange=e=>{const c=e.target.closest('[data-sg]');if(c){const s=suggestions.find(x=>x.id===c.dataset.sg);if(s)s.checked=c.checked}};
 $('#manualCal').onclick=()=>ensureYear()&&openDlg('#calDlg');$('#calForm').onsubmit=e=>{e.preventDefault();cur().calendarEvents.push({id:uid(),date:$('#calDate').value,title:$('#calTitle').value.trim(),type:$('#calType').value,source:'예외 입력'});e.target.reset();closeDlgs();save()};$('#calendarList').onclick=e=>{const b=e.target.closest('[data-cal-del]');if(b){cur().calendarEvents=cur().calendarEvents.filter(x=>x.id!==b.dataset.calDel);save()}};$('#exportICS').onclick=exportICS;
 $('#assItems').onclick=e=>{const b=e.target.closest('[data-ass-del]');if(b){cur().assessments=cur().assessments.filter(x=>x.id!==b.dataset.assDel);save()}};$('#clubAdd').onclick=()=>ensureYear()&&openSimple('club');$('#projAdd').onclick=()=>ensureYear()&&openSimple('project');$('#simpleForm').onsubmit=e=>{e.preventDefault();const data={id:uid(),name:$('#simpleName').value.trim(),due:$('#simpleDue').value};if($('#simpleKind').value==='club')cur().clubs.push({...data,type:'기타',goal:$('#simpleMemo').value.trim(),activities:[]});else cur().projects.push({...data,desc:$('#simpleMemo').value.trim(),source:'예외 입력'});e.target.reset();closeDlgs();save()};
 $('#memoryAdd').onclick=()=>ensureYear()&&openDlg('#memoryDlg');$('#memoryForm').onsubmit=e=>{e.preventDefault();cur().memories.push({id:uid(),note:$('#memNote').value.trim(),improve:$('#memImprove').value.trim(),created:new Date().toISOString()});e.target.reset();closeDlgs();save()};$('#memoryList').onclick=e=>{const b=e.target.closest('[data-mem-del]');if(b){cur().memories=cur().memories.filter(x=>x.id!==b.dataset.memDel);save()}};
 $('#taskAdd').onclick=()=>{if(!ensureYear())return;const v=$('#taskInput').value.trim();if(v){cur().tasks.push({id:uid(),text:v,done:false});$('#taskInput').value='';save()}};$('#taskList').onclick=e=>{const c=e.target.closest('[data-task]'),d=e.target.closest('[data-task-del]');if(c){const t=cur().tasks.find(x=>x.id===c.dataset.task);if(t){t.done=c.checked;save()}}if(d){cur().tasks=cur().tasks.filter(x=>x.id!==d.dataset.taskDel);save()}};$('#agentRun').onclick=runAgent;
 $('#exportJSON').onclick=exportJSON;$('#importJSON').onchange=e=>e.target.files[0]&&importJSON(e.target.files[0]);$('#runSelfTest').onclick=runSelfTests;$$('[data-close]').forEach(b=>b.onclick=closeDlgs)
}
$('#today').textContent=new Intl.DateTimeFormat('ko-KR',{dateStyle:'full'}).format(new Date());migrate();initEvents();render();runSelfTests();loadPolicyRegistry();
