(function(){
  const V6=globalThis.TeacherOSCoreV6;
  if(!V6||!globalThis.TeacherOSCore)return;
  const q=s=>document.querySelector(s), qa=s=>[...document.querySelectorAll(s)];
  const e=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  const makeId=()=>crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random().toString(16).slice(2);
  const todayISO=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
  const impactText=x=>x==='no-class'?'수업 없음':x==='partial'?'일부 영향':x==='none'?'영향 없음':'자동';
  const actionText=x=>x==='cancel'?'수업 없음':x==='add'?'추가 수업':'대체/변경';
  const paceText=x=>x==='조기완료'?'조기 완료':x==='여유진행'?'여유 있게':'표준';

  function ensureV6UI(){
    const nav=document.querySelector('#nav');
    if(nav&&!nav.querySelector('[data-view="progress"]')){
      const tt=nav.querySelector('[data-view="timetable"]');
      tt?.insertAdjacentHTML('afterend','<button data-view="progress">↗ <span>반별 진도</span></button>');
    }
    const foot=document.querySelector('.side-foot'); if(foot)foot.textContent='v0.6 · 반별 수업운영 + 편집형 시간표';
    const ttSection=document.querySelector('#timetable');
    if(ttSection&&!document.querySelector('#ttAdd')){
      ttSection.innerHTML=`<div class="section-intro"><div><span class="kicker">WEEKLY TIMETABLE</span><h2>월~금 시간표</h2><p class="muted">기본 시간표는 주간 반복표로 두고, 실제 학교행사·봉사·고사·학년행사는 날짜별 변동으로 따로 처리합니다.</p></div><div class="section-actions"><button class="btn secondary" id="ttAdd">+ 시간표 칸</button><button class="btn secondary" id="ttExceptionAdd">+ 날짜별 수업 변동</button></div></div><div class="notice"><b>원칙:</b> 기본 시간표를 매번 고치지 않습니다. 특정 날짜에 수업이 없어지거나 바뀌는 경우는 <b>날짜별 수업 변동</b>으로 기록합니다. 각 칸은 언제든 클릭해 수정할 수 있습니다.</div><article class="card spaced timetable-wrap"><table class="timetable editable-timetable" id="timetableTable"></table></article><article class="card spaced"><div class="head"><div><h3>날짜별 수업 변동</h3><p class="muted">특정 반·특정 교시만 빠지거나 대체되는 경우에 사용합니다.</p></div></div><div id="ttExceptionList"></div></article>`;
    }
    if(!document.querySelector('#progress')){
      document.querySelector('#assessment')?.insertAdjacentHTML('beforebegin',`<section id="progress" class="view"><div class="section-intro"><div><span class="kicker">CLASS PACING</span><h2>반별 진도</h2><p class="muted">같은 학년이라도 반마다 실제 수업 횟수가 다르므로 반별 실제 차시를 따로 봅니다.</p></div><button class="btn secondary" id="progressAdd">+ 진도 기록</button></div><div class="notice"><b>실제 수업만 1회로 기록.</b> 학사일정에서 수업이 빠진 날은 남은 수업 계산에서 제외하고, 수업 후에는 해당 반 카드에서 <b>+1차시</b>만 누르면 됩니다.</div><div id="gradeStrategy" class="grade-strategy spaced"></div><div id="progressGrid" class="progress-grid spaced"></div></section>`);
    }
    const calDesc=document.querySelector('#calendar .section-intro .muted');
    if(calDesc)calDesc.textContent='학교 문서에서 자동 추출된 일정입니다. 각 일정마다 전체학교·학년·특정 반 범위와 수업 영향 여부를 수정할 수 있습니다.';
    const calType=document.querySelector('#calType')?.closest('label');
    if(calType&&!document.querySelector('#calScope')){
      calType.insertAdjacentHTML('afterend','<label>적용 범위<input class="field" id="calScope" list="scopeOptions" placeholder="전체 / 2학년 / 3-4"></label><label>수업 영향<select class="field" id="calImpact"><option value="auto">자동 판단</option><option value="none">수업 영향 없음</option><option value="partial">일부 수업 영향</option><option value="no-class">해당 범위 수업 없음</option></select></label>');
    }
    if(!document.querySelector('#scopeOptions'))document.body.insertAdjacentHTML('beforeend','<datalist id="scopeOptions"><option value="전체"><option value="1학년"><option value="2학년"><option value="3학년"></datalist><datalist id="classOptions"></datalist>');
    if(!document.querySelector('#ttDlg'))document.body.insertAdjacentHTML('beforeend',`
<dialog id="ttDlg"><form class="modal" id="ttForm"><div class="modal-head"><div><span class="kicker">WEEKLY SLOT</span><h2>시간표 칸 수정</h2></div><button type="button" class="close" data-v6-close>×</button></div><input id="ttId" type="hidden"><div class="stack"><label>요일<select class="field" id="ttDay"><option>월</option><option>화</option><option>수</option><option>목</option><option>금</option></select></label><label>교시<input class="field" id="ttPeriod" type="number" min="1" max="12" required></label><label>반/대상<input class="field" id="ttTarget" placeholder="예: 3-7, 2-8" required></label><label>과목<input class="field" id="ttSubject" value="음악"></label><label>표시 이름<input class="field" id="ttLabel" placeholder="비우면 '3-7 음악'"></label><label>수업 시간 <span class="mini">선택</span><input class="field" id="ttTime" placeholder="예: 09:10~09:55"></label></div><div class="modal-actions"><button type="button" class="btn danger" id="ttDelete" hidden>삭제</button><button type="button" class="btn secondary" data-v6-close>취소</button><button class="btn primary">저장</button></div></form></dialog>
<dialog id="ttExceptionDlg"><form class="modal" id="ttExceptionForm"><div class="modal-head"><div><span class="kicker">DATE OVERRIDE</span><h2>날짜별 수업 변동</h2></div><button type="button" class="close" data-v6-close>×</button></div><input id="ttExId" type="hidden"><div class="stack"><label>날짜<input class="field" id="ttExDate" type="date" required></label><label>반/범위<input class="field" id="ttExTarget" list="scopeOptions" placeholder="예: 2학년 / 3-7" required></label><label>교시 <span class="mini">학년 전체면 비워도 됨</span><input class="field" id="ttExPeriod" type="number" min="1" max="12"></label><label>변동<select class="field" id="ttExAction"><option value="cancel">수업 없음</option><option value="add">추가 수업</option><option value="replace">대체/변경 수업</option></select></label><label>메모<input class="field" id="ttExLabel" placeholder="예: 봉사활동, 체육대회, 보강"></label></div><div class="modal-actions"><button type="button" class="btn danger" id="ttExDelete" hidden>삭제</button><button type="button" class="btn secondary" data-v6-close>취소</button><button class="btn primary">저장</button></div></form></dialog>
<dialog id="progressDlg"><form class="modal" id="progressForm"><div class="modal-head"><div><span class="kicker">ACTUAL PROGRESS</span><h2>반별 실제 진도</h2></div><button type="button" class="close" data-v6-close>×</button></div><div class="stack"><label>반<input class="field" id="progTarget" list="classOptions" placeholder="예: 3-7" required></label><label>현재 실제 차시<input class="field" id="progLesson" type="number" min="0" value="0" required></label><label>현재 단원/내용<input class="field" id="progTopic" placeholder="예: 드럼 스트로크 2차시"></label><label>메모<textarea class="field" id="progNote" placeholder="이 반만 늦어진 이유, 다음 시간 조정 등"></textarea></label></div><div class="modal-actions"><button type="button" class="btn secondary" data-v6-close>취소</button><button class="btn primary">저장</button></div></form></dialog>
<dialog id="eventEditDlg"><form class="modal" id="eventEditForm"><div class="modal-head"><div><span class="kicker">CALENDAR SCOPE</span><h2>학사일정 범위·영향 수정</h2></div><button type="button" class="close" data-v6-close>×</button></div><input id="eventEditId" type="hidden"><div class="stack"><label>날짜<input class="field" id="eventEditDate" type="date" required></label><label>일정명<input class="field" id="eventEditTitle" required></label><label>종류<select class="field" id="eventEditType"><option>학교</option><option>수업</option><option>평가</option><option>동아리</option><option>행정</option></select></label><label>적용 범위<input class="field" id="eventEditScope" list="scopeOptions" placeholder="전체 / 2학년 / 3-4"></label><label>수업 영향<select class="field" id="eventEditImpact"><option value="auto">자동 판단</option><option value="none">수업 영향 없음</option><option value="partial">일부 수업 영향</option><option value="no-class">해당 범위 수업 없음</option></select></label></div><div class="modal-actions"><button type="button" class="btn secondary" data-v6-close>취소</button><button class="btn primary">저장</button></div></form></dialog>`);
  }

  function migrateV6(){
    state.version=6;
    Object.values(state.years||{}).forEach(y=>{
      y.timetable=Array.isArray(y.timetable)?y.timetable:[];
      y.calendarEvents=Array.isArray(y.calendarEvents)?y.calendarEvents:[];
      y.timetableExceptions=Array.isArray(y.timetableExceptions)?y.timetableExceptions:[];
      y.classProgress=y.classProgress&&typeof y.classProgress==='object'&&!Array.isArray(y.classProgress)?y.classProgress:{};
      y.paceStrategies=y.paceStrategies&&typeof y.paceStrategies==='object'&&!Array.isArray(y.paceStrategies)?y.paceStrategies:{};
      y.calendarEvents.forEach(ev=>{if(!ev.scope)ev.scope='전체';if(!ev.impact)ev.impact=V6.inferImpact(ev.title)});
      y.timetable.forEach(s=>{if(!s.target)s.target=V6.targetFromLabel(s.label);if(!s.subject)s.subject='음악';if(!s.time)s.time=''});
      const grades=[...new Set(V6.classTargets(y.timetable).map(V6.gradeFromTarget))];
      grades.forEach(g=>{if(!y.paceStrategies[g])y.paceStrategies[g]=V6.defaultPaceStrategy(y.schoolLevel,g)});
    });
    localStorage.setItem(KEY,JSON.stringify(state));
  }

  switchView=function(id){qa('.view').forEach(x=>x.classList.toggle('active',x.id===id));qa('#nav button').forEach(x=>x.classList.toggle('active',x.dataset.view===id));q('#title').textContent=({dashboard:'오늘',importer:'자동세팅',calendar:'학사일정',timetable:'시간표',progress:'반별 진도',assessment:'수업·평가',clubs:'동아리',projects:'행정업무',policy:'교육과정·지침',documents:'자료함',memory:'업무기억',settings:'백업·점검'})[id]||id};

  function exactTargets(y){return V6.classTargets(y.timetable)}
  function periodTime(slot){return slot.time?`<div class="slot-time">${e(slot.time)}</div>`:''}
  function openTT(slot,day,period){q('#ttId').value=slot?.id||'';q('#ttDay').value=slot?.day||day||'월';q('#ttPeriod').value=slot?.period||period||1;q('#ttTarget').value=slot?.target||V6.targetFromLabel(slot?.label)||'';q('#ttSubject').value=slot?.subject||'음악';q('#ttLabel').value=slot?.label||'';q('#ttTime').value=slot?.time||'';q('#ttDelete').hidden=!slot;q('#ttDlg').showModal()}
  function openException(ex){q('#ttExId').value=ex?.id||'';q('#ttExDate').value=ex?.date||todayISO();q('#ttExTarget').value=ex?.target||'';q('#ttExPeriod').value=ex?.period||'';q('#ttExAction').value=ex?.action||'cancel';q('#ttExLabel').value=ex?.label||'';q('#ttExDelete').hidden=!ex;q('#ttExceptionDlg').showModal()}
  function openProgress(target){const y=cur(),p=y?.classProgress?.[target]||{};q('#progTarget').value=target||'';q('#progLesson').value=Number(p.lesson)||0;q('#progTopic').value=p.topic||'';q('#progNote').value=p.note||'';q('#progressDlg').showModal()}
  function openEvent(ev){q('#eventEditId').value=ev.id;q('#eventEditDate').value=ev.date||'';q('#eventEditTitle').value=ev.title||'';q('#eventEditType').value=ev.type||'학교';q('#eventEditScope').value=ev.scope||'전체';q('#eventEditImpact').value=ev.impact||'auto';q('#eventEditDlg').showModal()}
  function updateClassOptions(y){q('#classOptions').innerHTML=exactTargets(y).map(t=>`<option value="${e(t)}"></option>`).join('')}

  renderTimetable=function(y){
    const days=V6.WEEKDAYS,maxPeriod=Math.max(7,...y.timetable.map(x=>Number(x.period)||0));let h='<thead><tr><th>교시</th>'+days.map(d=>`<th>${d}</th>`).join('')+'</tr></thead><tbody>';
    for(let p=1;p<=maxPeriod;p++){h+=`<tr><td><b>${p}</b></td>`+days.map(d=>{const slots=y.timetable.filter(x=>x.day===d&&Number(x.period)===p);return `<td class="tt-cell" data-add-day="${d}" data-add-period="${p}">${slots.map(s=>`<button class="slot editable-slot" data-tt-edit="${s.id}" type="button"><b>${e(s.target||V6.targetFromLabel(s.label)||s.label)}</b><span>${e(s.subject||'음악')}</span>${periodTime(s)}</button>`).join('')}<button class="cell-add" type="button">＋</button></td>`}).join('')+'</tr>'}h+='</tbody>';q('#timetableTable').innerHTML=h;
    const wd=['일','월','화','수','목','금','토'][new Date().getDay()],date=todayISO(),todaySlots=[];exactTargets(y).forEach(t=>V6.teachingSlotsForDate(y.timetable,y.calendarEvents,y.timetableExceptions,t,date).forEach(s=>{if(s.day===wd)todaySlots.push({...s,target:t})}));const unique=new Map();todaySlots.forEach(s=>unique.set(`${s.target}|${s.period}|${s.label}`,s));const list=[...unique.values()].sort((a,b)=>Number(a.period)-Number(b.period));q('#todayTimetable').innerHTML=list.length?list.map(s=>`<span class="today-slot">${e(s.period)}교시 · ${e(s.target)} ${e(s.subject||'음악')} <button type="button" class="mini-action" data-progress-plus="${e(s.target)}">수업완료 +1</button></span>`).join(''):'<span class="muted">오늘 실제로 진행할 등록 수업이 없습니다.</span>';renderTimetableExceptions(y);updateClassOptions(y)
  };
  function renderTimetableExceptions(y){const box=q('#ttExceptionList');if(!box)return;const a=y.timetableExceptions.slice().sort((a,b)=>(a.date||'').localeCompare(b.date||''));box.innerHTML=a.length?a.map(x=>`<div class="row"><div class="calendar-date">${e(x.date)}</div><div class="grow"><strong>${e(x.target||'전체')} ${x.period?e(x.period)+'교시 ':''}· ${actionText(x.action)}</strong><div class="mini">${e(x.label||'')}</div></div><button class="linkbtn" data-tt-ex-edit="${x.id}">수정</button></div>`).join(''):'<div class="empty">등록된 날짜별 수업 변동이 없습니다.</div>'}
  renderCalendar=function(y){const a=y.calendarEvents.slice().sort((a,b)=>(a.date||'').localeCompare(b.date||''));q('#calendarList').innerHTML=a.length?a.map(ev=>{const impact=ev.impact&&ev.impact!=='auto'?ev.impact:V6.inferImpact(ev.title);return `<div class="row calendar-row"><div class="calendar-date">${e(ev.date)}</div><div class="grow"><strong>${e(ev.title)}</strong><div class="mini">${e(ev.type||'학교')} · 범위 ${e(ev.scope||'전체')} · ${impactText(impact)} · ${e(ev.source||'예외 입력')}</div></div><button class="linkbtn" data-cal-edit="${ev.id}">범위/영향</button><button class="linkbtn danger-text" data-cal-del="${ev.id}">삭제</button></div>`}).join(''):'<div class="empty">자동세팅에서 학교 학사일정 자료를 올리세요.</div>'};

  function matchingAssessments(y,target){return y.assessments.filter(a=>a.due&&C.dueDays(a.due)>=0&&(!a.target||V6.scopeMatches(a.target,target))).sort((a,b)=>a.due.localeCompare(b.due))}
  function remainingFor(y,target,due){return V6.countClassTeachingSlots(y.timetable,y.calendarEvents,y.timetableExceptions,target,todayISO(),due)}
  renderAssess=function(y){const classes=exactTargets(y);q('#assItems').innerHTML=y.assessments.length?y.assessments.map(a=>{let remain='';if(a.due){const matched=classes.filter(t=>!a.target||V6.scopeMatches(a.target,t));if(matched.length){const vals=matched.map(t=>({t,n:remainingFor(y,t,a.due)})),min=Math.min(...vals.map(v=>v.n)),max=Math.max(...vals.map(v=>v.n));remain=` · 반별 남은 수업 ${min===max?min+'회':min+'~'+max+'회'}`;if(max-min>=2)remain+=` <span class="status-warn">격차 ${max-min}회</span>`}}return `<div class="row"><div class="grow"><strong>${e(a.name)}</strong><div class="mini">${e(a.target||'대상 미확인')} ${a.weight?'· '+e(a.weight):''} ${a.due?'· '+e(a.due):''}${remain}</div><div class="source">${e(a.source||'')}</div></div><button class="linkbtn danger-text" data-ass-del="${a.id}">삭제</button></div>`}).join(''):'<div class="empty">평가계획서를 자동세팅에서 올리세요.</div>'};
  function gradeNote(y,g){const st=y.paceStrategies?.[g]||V6.defaultPaceStrategy(y.schoolLevel,g);if(y.schoolLevel==='중학교'&&g==='3')return `입시 일정 고려 · ${paceText(st)} 모드`;if(y.schoolLevel==='중학교'&&g==='2')return `반별 결손을 감안 · ${paceText(st)} 모드`;return `${paceText(st)} 모드`}
  function renderGradeStrategies(y){const grades=[...new Set(exactTargets(y).map(V6.gradeFromTarget))].filter(Boolean);q('#gradeStrategy').innerHTML=grades.length?grades.map(g=>{const val=y.paceStrategies[g]||V6.defaultPaceStrategy(y.schoolLevel,g);return `<div class="strategy-card"><div><b>${g}학년</b><div class="mini">${e(gradeNote(y,g))}</div></div><select class="field strategy-select" data-grade-strategy="${g}"><option value="조기완료" ${val==='조기완료'?'selected':''}>조기 완료</option><option value="표준" ${val==='표준'?'selected':''}>표준</option><option value="여유진행" ${val==='여유진행'?'selected':''}>여유 있게</option></select></div>`}).join(''):'<div class="empty">시간표에서 반을 먼저 등록하면 학년별 운영속도를 설정할 수 있습니다.</div>'}
  function renderProgress(y){const targets=exactTargets(y),stats=V6.paceStats(y.classProgress,targets);renderGradeStrategies(y);q('#progressGrid').innerHTML=stats.length?stats.map(s=>{const delta=s.gap==null?'아직 비교 없음':Math.abs(s.gap)<.5?'학년 평균':s.gap>0?`평균보다 ${Math.abs(s.gap).toFixed(s.gap%1?1:0)}차시 빠름`:`평균보다 ${Math.abs(s.gap).toFixed(s.gap%1?1:0)}차시 느림`;const next=matchingAssessments(y,s.target)[0],remain=next?remainingFor(y,s.target,next.due):null;return `<article class="card progress-card ${s.gap!=null&&s.gap<=-2?'behind':''}"><div class="head"><div><span class="pill">${e(s.target)}</span><h3>${s.recorded?e(s.lesson)+'차시':'진도 미기록'}</h3></div><button class="linkbtn" data-progress-edit="${e(s.target)}">상세</button></div><p class="muted">${e(s.topic||'현재 단원/내용 미입력')}</p><div class="progress-meta"><span>${e(delta)}</span><span>${e(gradeNote(y,s.grade))}</span>${next?`<span>${e(next.name)}까지 약 ${remain}회</span>`:''}</div><div class="progress-actions"><button class="btn secondary tiny" data-progress-minus="${e(s.target)}">−1</button><button class="btn primary tiny" data-progress-plus="${e(s.target)}">+1차시</button></div>${s.note?`<div class="mini progress-note">${e(s.note)}</div>`:''}</article>`}).join(''):'<div class="empty">시간표의 반 정보를 기준으로 자동 생성됩니다.</div>'}
  renderFlow=function(y){const stats=V6.paceStats(y.classProgress,exactTargets(y)),alerts=stats.filter(s=>s.gap!=null&&s.gap<=-1.5).sort((a,b)=>a.gap-b.gap),evals=y.assessments.filter(a=>a.due&&C.dueDays(a.due)>=0).sort((a,b)=>a.due.localeCompare(b.due)).slice(0,4);let h='';if(alerts.length)h+=`<div class="flow-alert"><b>진도 차이 확인</b>${alerts.slice(0,4).map(s=>`<div>${e(s.target)} · 학년 평균보다 ${Math.abs(s.gap).toFixed(1)}차시 느림</div>`).join('')}</div>`;h+=evals.length?evals.map(a=>{const cs=exactTargets(y).filter(t=>!a.target||V6.scopeMatches(a.target,t)),vals=cs.map(t=>remainingFor(y,t,a.due)),range=vals.length?`${Math.min(...vals)}~${Math.max(...vals)}회`:'계산 불가';return `<div class="row"><div class="grow"><strong>${e(a.name)}</strong><div class="mini">${e(a.target||'전체')} · ${e(a.due)} · 반별 남은 수업 ${range}</div></div></div>`}).join(''):'<div class="empty">날짜가 있는 평가가 없습니다.</div>';q('#flowList').innerHTML=h};
  renderNext=function(y){const a=allUpcoming(y).slice(0,10);q('#nextList').innerHTML=a.length?a.map(x=>{const src=y.calendarEvents.find(ev=>ev.date===x.date&&ev.title===x.title),scope=src?.scope&&src.scope!=='전체'?` · ${src.scope}`:'';return `<div class="row"><div class="calendar-date">${e(x.date)}</div><div class="grow"><strong>${e(x.title)}</strong><div class="mini">${e(x.type)}${e(scope)} · ${dueText(x.date)}</div></div></div>`}).join(''):'<div class="empty">다가오는 일정이 없습니다.</div>'};

  const originalConflict=conflictMessages;
  conflictMessages=function(y){const out=originalConflict(y),stats=V6.paceStats(y.classProgress,exactTargets(y));stats.filter(s=>s.gap!=null&&s.gap<=-2).forEach(s=>out.push(`반별 진도: ${s.target}가 같은 학년 평균보다 ${Math.abs(s.gap).toFixed(1)}차시 느립니다.`));y.calendarEvents.filter(ev=>C.dueDays(ev.date)>=0&&C.dueDays(ev.date)<=14&&(ev.impact==='partial'||(ev.impact==='auto'&&V6.inferImpact(ev.title)==='partial'))).slice(0,4).forEach(ev=>out.push(`수업영향 확인 필요: ${ev.title} (${ev.date}, ${ev.scope||'전체'})`));return [...new Set(out)]};

  const oldRender=render;
  render=function(){migrateV6();oldRender();const y=cur();if(y){renderProgress(y);renderTimetableExceptions(y);updateClassOptions(y)}else{if(q('#progressGrid'))q('#progressGrid').innerHTML='<div class="empty">학년도를 먼저 만들어 주세요.</div>';if(q('#gradeStrategy'))q('#gradeStrategy').innerHTML='';if(q('#ttExceptionList'))q('#ttExceptionList').innerHTML=''}};
  function plusProgress(target,delta){const y=cur();if(!y||!target)return;y.classProgress[target]=y.classProgress[target]||{lesson:0,topic:'',note:'',updatedAt:null};y.classProgress[target].lesson=Math.max(0,(Number(y.classProgress[target].lesson)||0)+delta);y.classProgress[target].updatedAt=new Date().toISOString();save()}

  function initV6Events(){
    q('#ttAdd').onclick=()=>ensureYear()&&openTT(null,'월',1);q('#ttExceptionAdd').onclick=()=>ensureYear()&&openException(null);q('#progressAdd').onclick=()=>ensureYear()&&openProgress(exactTargets(cur())[0]||'');
    q('#timetableTable').onclick=ev=>{const edit=ev.target.closest('[data-tt-edit]');if(edit){ev.stopPropagation();const s=cur().timetable.find(x=>x.id===edit.dataset.ttEdit);if(s)openTT(s);return}const cell=ev.target.closest('[data-add-day]');if(cell)openTT(null,cell.dataset.addDay,Number(cell.dataset.addPeriod))};
    q('#ttExceptionList').onclick=ev=>{const b=ev.target.closest('[data-tt-ex-edit]');if(b){const x=cur().timetableExceptions.find(z=>z.id===b.dataset.ttExEdit);if(x)openException(x)}};
    q('#ttForm').onsubmit=ev=>{ev.preventDefault();const y=cur(),id=q('#ttId').value,target=V6.normalizeScope(q('#ttTarget').value),subject=q('#ttSubject').value.trim()||'음악',data={day:q('#ttDay').value,period:Number(q('#ttPeriod').value),target,subject,label:q('#ttLabel').value.trim()||`${target} ${subject}`,time:q('#ttTime').value.trim(),source:'직접 수정'};if(id){const s=y.timetable.find(x=>x.id===id);if(s)Object.assign(s,data)}else y.timetable.push({id:makeId(),...data});q('#ttDlg').close();save()};
    q('#ttDelete').onclick=()=>{const id=q('#ttId').value;if(id&&confirm('이 시간표 칸을 삭제할까요?')){cur().timetable=cur().timetable.filter(x=>x.id!==id);q('#ttDlg').close();save()}};
    q('#ttExceptionForm').onsubmit=ev=>{ev.preventDefault();const y=cur(),id=q('#ttExId').value,data={date:q('#ttExDate').value,target:V6.normalizeScope(q('#ttExTarget').value),period:Number(q('#ttExPeriod').value)||null,action:q('#ttExAction').value,label:q('#ttExLabel').value.trim()};if(id){const x=y.timetableExceptions.find(z=>z.id===id);if(x)Object.assign(x,data)}else y.timetableExceptions.push({id:makeId(),...data});q('#ttExceptionDlg').close();save()};
    q('#ttExDelete').onclick=()=>{const id=q('#ttExId').value;if(id&&confirm('이 수업 변동을 삭제할까요?')){cur().timetableExceptions=cur().timetableExceptions.filter(x=>x.id!==id);q('#ttExceptionDlg').close();save()}};
    q('#progressGrid').onclick=ev=>{const plus=ev.target.closest('[data-progress-plus]'),minus=ev.target.closest('[data-progress-minus]'),edit=ev.target.closest('[data-progress-edit]');if(plus)plusProgress(plus.dataset.progressPlus,1);if(minus)plusProgress(minus.dataset.progressMinus,-1);if(edit)openProgress(edit.dataset.progressEdit)};
    q('#todayTimetable').onclick=ev=>{const b=ev.target.closest('[data-progress-plus]');if(b)plusProgress(b.dataset.progressPlus,1)};
    q('#progressForm').onsubmit=ev=>{ev.preventDefault();const y=cur(),t=V6.normalizeScope(q('#progTarget').value);y.classProgress[t]={lesson:Number(q('#progLesson').value)||0,topic:q('#progTopic').value.trim(),note:q('#progNote').value.trim(),updatedAt:new Date().toISOString()};q('#progressDlg').close();save()};
    q('#gradeStrategy').onchange=ev=>{const s=ev.target.closest('[data-grade-strategy]');if(s){cur().paceStrategies[s.dataset.gradeStrategy]=s.value;save()}};
    q('#calendarList').onclick=ev=>{const edit=ev.target.closest('[data-cal-edit]'),del=ev.target.closest('[data-cal-del]');if(edit){const x=cur().calendarEvents.find(z=>z.id===edit.dataset.calEdit);if(x)openEvent(x)}if(del&&confirm('이 일정을 삭제할까요?')){cur().calendarEvents=cur().calendarEvents.filter(x=>x.id!==del.dataset.calDel);save()}};
    q('#eventEditForm').onsubmit=ev=>{ev.preventDefault();const x=cur().calendarEvents.find(z=>z.id===q('#eventEditId').value);if(x){x.date=q('#eventEditDate').value;x.title=q('#eventEditTitle').value.trim();x.type=q('#eventEditType').value;x.scope=V6.normalizeScope(q('#eventEditScope').value||'전체');x.impact=q('#eventEditImpact').value}q('#eventEditDlg').close();save()};
    q('#calForm').onsubmit=ev=>{ev.preventDefault();cur().calendarEvents.push({id:makeId(),date:q('#calDate').value,title:q('#calTitle').value.trim(),type:q('#calType').value,scope:V6.normalizeScope(q('#calScope').value||'전체'),impact:q('#calImpact').value,source:'예외 입력'});ev.target.reset();q('#calScope').value='전체';q('#calImpact').value='auto';closeDlgs();save()};
    qa('[data-v6-close]').forEach(b=>b.onclick=()=>b.closest('dialog')?.close());
  }

  ensureV6UI();migrateV6();initV6Events();render();
})();
