(function(){
  const q=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  function year(){try{return typeof cur==='function'?cur():null}catch{return null}}
  function rows(){const y=year();if(!y)return[];const tasks=(Array.isArray(y.tasks)?y.tasks:[]).filter(x=>x?.source==='Desktop Bridge 자동감지'&&/^NEIS\s/i.test(String(x.text||''))).map(x=>({kind:'task',title:x.text,due:x.due||'',done:!!x.done}));const projects=(Array.isArray(y.projects)?y.projects:[]).filter(x=>x?.source==='Desktop Bridge 자동감지'&&/^NEIS\s/i.test(String(x.name||''))).map(x=>({kind:'project',title:x.name,due:x.due||'',done:String(x.status||'').includes('완료')}));return[...tasks,...projects]}
  function render37(){const card=q('#desktopBridge36');if(card&&!q('#neisLocal37')){card.insertAdjacentHTML('beforeend','<div id="neisLocal37" class="neis-local37"></div>')}const box=q('#neisLocal37');if(box){const all=rows(),open=all.filter(x=>!x.done),student=open.filter(x=>/학생부|출결/.test(x.title)),assessment=open.filter(x=>/평가|성적/.test(x.title)),progress=open.filter(x=>/진도/.test(x.title));box.innerHTML=`<div class="neis-local37-head"><div><span class="kicker">NEIS LOCAL ADAPTER · v0.37</span><b>나이스 내보내기 자동 집계</b></div><span class="pill ${open.length?'warn':''}">${open.length?`확인 ${open.length}건`:'대기 업무 없음'}</span></div><div class="neis-local37-grid"><div><b>${assessment.length}</b><span>평가·성적</span></div><div><b>${student.length}</b><span>학생부·출결</span></div><div><b>${progress.length}</b><span>진도</span></div><div><b>${open.length}</b><span>전체 확인</span></div></div>${open.length?'<div class="neis-local37-list">'+open.slice(0,4).map(x=>`<span>${esc(x.title)}${x.due?' · '+esc(x.due):''}</span>`).join('')+'</div>':'<div class="mini">NEIS에서 내려받은 파일이 Downloads 또는 Teacher OS Inbox에 들어오면 이름과 원문을 외부로 보내지 않고 필요한 건수만 로컬 집계합니다.</div>'}`}
    const settings=q('#desktopSettings36');if(settings&&!q('#neisLocalPolicy37'))settings.insertAdjacentHTML('beforeend','<div id="neisLocalPolicy37" class="notice"><b>v0.37 NEIS Local Adapter:</b> 학생부·출결·성적·평가·진도 관련 내보내기 파일에서 미입력/누락/미완료 건수만 집계합니다. 학생 이름과 원문 행은 Teacher OS로 전달하지 않습니다.</div>')
  }
  const previous=globalThis.render;if(typeof previous==='function')globalThis.render=function(){const r=previous.apply(this,arguments);setTimeout(render37,0);return r};
  setTimeout(render37,900);setInterval(render37,120000);
})();
