(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.TeacherOSDocumentVersions=api})(typeof globalThis!=='undefined'?globalThis:this,function(){
  const REV_MARKERS=[['재수정',30],['최종',40],['확정',40],['개정',25],['수정',20],['변경',15],['final',40],['revised',25],['revision',25],['rev',25]];
  function baseName(name){return String(name||'').normalize('NFKC').replace(/^.*[\\/]/,'').replace(/\.[^.]+$/,'').trim()}
  function versionNumber(name){const s=baseName(name);let m=s.match(/(?:^|[\s_\-(])(v|ver|version)\s*([0-9]+(?:\.[0-9]+)*)/i);if(m)return m[2].split('.').map(Number);m=s.match(/(?:수정|개정|변경)\s*([0-9]+)\s*(?:차|판|본)?/);if(m)return[Number(m[1])];m=s.match(/([0-9]+)\s*차\s*(?:수정|개정|변경)/);return m?[Number(m[1])]:null}
  function markerRank(name){const s=baseName(name).toLowerCase();let rank=0,label='';for(const [token,n] of REV_MARKERS){if(s.includes(token)&&n>rank){rank=n;label=token}}return{rank,label}}
  function embeddedDate(name){const s=baseName(name);let m=s.match(/(20\d{2})[._-](\d{1,2})[._-](\d{1,2})/);if(!m)m=s.match(/(20\d{2})(\d{2})(\d{2})/);if(!m)return null;const y=Number(m[1]),mo=Number(m[2]),d=Number(m[3]);const t=Date.UTC(y,mo-1,d);const dt=new Date(t);return dt.getUTCFullYear()===y&&dt.getUTCMonth()===mo-1&&dt.getUTCDate()===d?t:null}
  function familyKey(name){let s=baseName(name).toLowerCase();s=s.replace(/\((?:복사본|copy|사본|\d+)\)\s*$/gi,' ');s=s.replace(/(?:^|[\s_\-(])(?:v|ver|version)\s*[0-9]+(?:\.[0-9]+)*/gi,' ');s=s.replace(/(?:재수정|최종본?|확정본?|수정본?|개정본?|변경본?|수정\s*\d*\s*(?:차|판|본)?|개정\s*\d*\s*(?:차|판|본)?|변경\s*\d*\s*(?:차|판|본)?|final|revised|revision|rev)/gi,' ');s=s.replace(/[\s_\-([\]]+(20\d{2}[._-]\d{1,2}[._-]\d{1,2}|20\d{6})\s*$/,' ');return s.replace(/[()[\]{}]/g,' ').replace(/[\s_-]+/g,' ').trim()}
  function meta(name,extra={}){const mr=markerRank(name);return{name:String(name||''),familyKey:familyKey(name),version:versionNumber(name),markerRank:mr.rank,marker:mr.label,date:embeddedDate(name),lastModified:Number(extra.lastModified)||null,size:Number(extra.size)||null,hash:extra.hash||'',docClass:extra.docClass||''}}
  function cmpVersion(a,b){const n=Math.max(a?.length||0,b?.length||0);for(let i=0;i<n;i++){const x=Number(a?.[i]||0),y=Number(b?.[i]||0);if(x!==y)return x>y?1:-1}return 0}
  function compare(newMeta,oldMeta){const a=newMeta||{},b=oldMeta||{};if(!a.familyKey||!b.familyKey||a.familyKey!==b.familyKey)return{relation:'unrelated',confidence:'high',reason:'different-family'};if(a.docClass&&b.docClass&&a.docClass!==b.docClass)return{relation:'unrelated',confidence:'high',reason:'different-class'};if(a.hash&&b.hash&&a.hash===b.hash)return{relation:'duplicate',confidence:'high',reason:'same-hash'};if(a.version&&b.version){const c=cmpVersion(a.version,b.version);if(c)return{relation:c>0?'newer':'older',confidence:'high',reason:'explicit-version'}}if(a.markerRank!==b.markerRank&&(a.markerRank||b.markerRank)){return{relation:a.markerRank>b.markerRank?'newer':'older',confidence:'high',reason:'revision-marker'}}if(a.date&&b.date&&a.date!==b.date)return{relation:a.date>b.date?'newer':'older',confidence:'high',reason:'embedded-date'};return{relation:'ambiguous',confidence:'low',reason:a.name===b.name?'same-name-different-content':'no-authoritative-version-evidence'}}
  function activeCandidates(imports,newImport){const nm=meta(newImport?.name,{hash:newImport?.hash,docClass:newImport?.docClass,lastModified:newImport?.fileLastModified,size:newImport?.size});return(imports||[]).filter(x=>x!==newImport&&x.status!=='ignored'&&x.status!=='superseded').map(x=>({item:x,m:meta(x.name,{hash:x.hash,docClass:x.docClass,lastModified:x.fileLastModified,size:x.size})})).filter(x=>x.m.familyKey===nm.familyKey&&(!nm.docClass||!x.m.docClass||nm.docClass===x.m.docClass))}
  return{baseName,versionNumber,markerRank,embeddedDate,familyKey,meta,compare,activeCandidates};
});