const fs=require('fs');
const cfg=JSON.parse(fs.readFileSync('comcigan-config.json','utf8'));
if(!cfg.enabled)throw new Error('Comcigan config must be enabled');
if(Number(cfg.schoolCode)!==65231)throw new Error('Unexpected school code');
if(Number(cfg.teacherIndex)!==37)throw new Error('Unexpected teacher index');
if(!String(cfg.teacherName||'').trim())throw new Error('Teacher name is required');
const wf=fs.readFileSync('.github/workflows/sync-comcigan.yml','utf8');
if(!wf.includes("cron: '0 0 * * *'"))throw new Error('09:00 KST daily cron missing');
const app=fs.readFileSync('app-v14.js','utf8');
if(!app.includes("./live/comcigan.json"))throw new Error('Plain live Comcigan feed missing');
if(!app.includes('매일 09:00'))throw new Error('9am sync UI copy missing');
if(!app.includes('lockTimetableReadOnly'))throw new Error('Read-only timetable guard missing');
if(!app.includes("q('#ttAdd')?.remove()"))throw new Error('Manual timetable add control must be removed');
if(!app.includes("q('#ttExceptionAdd')?.remove()"))throw new Error('Manual exception control must be removed');
if(!app.includes("myTeacherOS.comciganConfig"))throw new Error('Per-browser Comcigan config storage missing');
if(!app.includes('컴시간 설정 변경'))throw new Error('Comcigan edit button missing');
if(!app.includes('sameConfig'))throw new Error('Comcigan payload/config mismatch guard missing');
if(!app.includes('다시 변경할 때만 바뀝니다'))throw new Error('Persistent config explanation missing');
console.log('v0.14 Comcigan editable config + read-only timetable tests passed');
