const assert=require('node:assert');
const fs=require('fs');
const D=require('../core-v23.js');
const cal=D.classifyDocument({name:'2026학년도 학사일정.pdf',text:'학사 일정 개학 방학 체육대회 상담주간 2026-03-02 2026-07-20',ext:'pdf'});
assert.equal(cal.classId,'calendar');
assert.ok(cal.confidence>.7);
const ass=D.classifyDocument({name:'2026 음악 평가계획.hwp',text:'수행평가 평가계획 반영비율 40% 성취기준 평가방법 지필평가',ext:'hwp'});
assert.equal(ass.classId,'assessment');
const adm=D.classifyDocument({name:'교직원 업무분장.xlsx',text:'업무분장 담당업무 담당자 담당부서 제출 보고 공문',ext:'xlsx',layout:{tableRows:30}});
assert.equal(adm.classId,'admin');
const tt=D.classifyDocument({name:'교사 시간표.xlsx',text:'월 화 수 목 금 1교시 2교시 시간표',ext:'xlsx',layout:{tableRows:10,timetableSlots:24,dayHeaders:5}});
assert.equal(tt.classId,'timetable');
assert.equal(D.feedbackSignature('2026_1학기_평가계획.xlsx'),D.feedbackSignature('2027_1학기_평가계획.xlsx'));
const good=D.fuseSuggestion({baseConfidence:.96,docClass:'assessment',docConfidence:.95,extractionQuality:.95,kind:'assessment'});
assert.ok(good.auto);assert.ok(good.confidence>.9);
const wrong=D.fuseSuggestion({baseConfidence:.9,docClass:'admin',docConfidence:.96,extractionQuality:.95,kind:'assessment'});
assert.equal(wrong.auto,false);
const ambiguousWrong=D.fuseSuggestion({baseConfidence:.99,docClass:'admin',docConfidence:.84,extractionQuality:.99,kind:'assessment',mixed:true});
assert.equal(ambiguousWrong.auto,false,'ambiguous mixed documents must not broaden auto-apply to mismatched suggestion kinds');
assert.ok(ambiguousWrong.compatibility<.9,'mixed classification must retain primary-class compatibility instead of granting blanket compatibility');
const mixedSchoolplan=D.fuseSuggestion({baseConfidence:.96,docClass:'schoolplan',docConfidence:.84,extractionQuality:.95,kind:'assessment',mixed:true});
assert.equal(mixedSchoolplan.auto,true,'explicit school-plan documents may retain multi-domain auto-apply after confidence checks');
const student=D.fuseSuggestion({baseConfidence:.98,docClass:'student',docConfidence:.98,extractionQuality:.95,kind:'admin',sensitive:true});
assert.equal(student.auto,false);
assert.ok(D.extractionQuality({text:'학교교육계획 학사일정 평가계획 업무분장'.repeat(20),method:'hwp-native'})>=.9);
const degradedNative=D.extractionQuality({text:'수행평가 □□□□ 30% ※※※ 9월 3일',method:'docx-native'});
assert.ok(degradedNative<.72,'low-quality native extraction must not receive an automatic high-confidence floor');
const degradedSuggestion=D.fuseSuggestion({baseConfidence:.96,docClass:'assessment',docConfidence:.95,extractionQuality:degradedNative,kind:'assessment'});
assert.equal(degradedSuggestion.auto,false,'degraded native text must require review even when filename/document classification is strong');
const app=fs.readFileSync('app-v23.js','utf8'),css=fs.readFileSync('app-v23.css','utf8'),index=fs.readFileSync('index.html','utf8');
['PaddleOCR','PP-OCRv5','pdf-hybrid-layout+ocr','feedbackSignature','v23DocReport','고정밀 다시 분석','학생자료는 자동 적용 차단','TeacherOSStorage.writeJSON(KEY,state)'].forEach(t=>{if(!app.includes(t))throw new Error('v0.23 app missing: '+t)});
if(app.includes('localStorage.setItem(KEY')||app.includes('localStorage.getItem(KEY'))throw new Error('v0.23 document import state bypasses shared storage');
if(!app.includes('localStorage.setItem(FEEDBACK_KEY')||!app.includes('localStorage.getItem(FEEDBACK_KEY'))throw new Error('v0.23 classifier feedback must remain a separate local preference key');
if(!css.includes('.v23-file-row')||!css.includes('@media(max-width:780px)'))throw new Error('v0.23 responsive report CSS missing');
if(!index.includes('core-v23.js')||!index.includes('app-v23.js')||!index.includes('app-v23.css'))throw new Error('v0.23 loader missing');
console.log('v0.23 document intelligence tests passed with shared-storage guard');
