const fs=require('fs');
const R=require('../core-v25.js');
const goodEvidence=[
  {id:'e1',date:'2026-04-12',text:'모둠 합주에서 리듬이 맞지 않는 부분을 스스로 찾아 반복 연습하고 친구에게 박자를 설명함.'},
  {id:'e2',date:'2026-05-03',text:'합주 발표에서 다른 파트의 소리를 들으며 자신의 연주 세기를 조절하고 모둠원과 시작 박자를 맞춤.'}
];
const good=R.analyzeDraft({area:'subject',evidence:goodEvidence,text:'모둠 합주에서 리듬이 맞지 않는 부분을 스스로 찾아 반복 연습하고 친구에게 박자를 설명함. 이후 합주 발표에서는 다른 파트의 소리를 들으며 연주 세기를 조절하고 모둠원과 시작 박자를 맞추는 모습이 관찰됨.'});
if(good.critical)throw new Error('grounded draft must not be critical');
if(good.score<75)throw new Error('grounded draft quality unexpectedly low: '+good.score);
if(good.dimensions.grounding<25)throw new Error('grounding score too low');
if(R.tokens('음악으로 표현함').includes('음악으'))throw new Error('으로 suffix must not be truncated as 로');
if(!R.tokens('음악으로 표현함').includes('음악'))throw new Error('으로 suffix must normalize to the base token');
const directionalGrounding=R.grounding('음악으로 감정을 표현함.',[{text:'음악을 활용해 감정을 표현함.'}]);
if(directionalGrounding.ratio!==1)throw new Error('으로/을 particle variation should preserve evidence overlap');
const noEvidence=R.analyzeDraft({area:'subject',evidence:[],text:'수업에 적극적으로 참여하며 탐구 역량이 향상됨.'});
if(!noEvidence.critical||!noEvidence.issues.some(x=>x.code==='NO_EVIDENCE'))throw new Error('missing evidence must be critical');
const prohibited=R.analyzeDraft({area:'subject',evidence:goodEvidence,text:'모둠 합주에 참여하고 교외 대회 수상 실적을 바탕으로 탁월한 음악적 역량을 보임.'});
if(!prohibited.critical||!prohibited.issues.some(x=>x.code==='PROHIBITED'))throw new Error('prohibited expression guard missing');
const unsupported=R.analyzeDraft({area:'subject',evidence:goodEvidence,text:'모둠 합주에서 반복 연습함. 인공지능 작곡 프로그램을 독학하여 전문 작곡가 수준의 작품을 완성함.'});
if(!unsupported.issues.some(x=>x.code==='UNSUPPORTED'))throw new Error('unsupported sentence must be flagged');
const multiline=R.grounding('리듬을 반복 연습함\n전문 작곡가 수준 작품 완성함',goodEvidence);
if(multiline.unsupported.length!==1||!multiline.unsupported[0].includes('전문 작곡가'))throw new Error('newline-separated unsupported claim is being merged into supported evidence');
const multilineAnalyze=R.analyzeDraft({area:'subject',evidence:[goodEvidence[0]],text:'리듬을 반복 연습함\n전문 작곡가 수준 작품 완성함'});
if(multilineAnalyze.unsupportedSentences.length!==1||!multilineAnalyze.unsupportedSentences[0].includes('전문 작곡가')||!multilineAnalyze.issues.some(x=>x.code==='UNSUPPORTED'))throw new Error('analyzeDraft must preserve line breaks before grounding');
const shortUnsupported=R.grounding('천재적임.',goodEvidence);
if(shortUnsupported.ratio!==0||shortUnsupported.unsupported.length!==1)throw new Error('short unsupported sentence must not be auto-grounded');
const genericObserved=R.grounding('전문 작곡가 수준 작품이 관찰됨.',goodEvidence);
if(genericObserved.ratio!==0)throw new Error('generic observed wording must not bypass evidence overlap');
const staleIneligible=R.analyzeDraft({area:'subject',evidence:[{id:'s1',eligible:false,area:'subject',kind:'교과관찰',text:'합주에서 반복 연습하고 박자를 설명함.'}],text:'합주에서 반복 연습하고 박자를 설명함.'});
if(!staleIneligible.critical||staleIneligible.evidenceCount!==0||!staleIneligible.issues.some(x=>x.code==='NO_EVIDENCE'))throw new Error('evidence later marked ineligible must stop supporting the draft');
const staleSensitive=R.analyzeDraft({area:'subject',evidence:[{id:'s2',eligible:true,area:'subject',kind:'교과관찰',text:'우울 증상과 관련해 상담한 뒤 합주에 참여함.'}],text:'합주에 참여함.'});
if(!staleSensitive.critical||staleSensitive.evidenceCount!==0)throw new Error('sensitive evidence must not support school-record quality scoring');
const directPhoneEvidence=R.analyzeDraft({area:'subject',evidence:[{id:'s2p',eligible:true,area:'subject',kind:'교과관찰',text:'연락처 010-1234-5678을 확인한 뒤 합주에서 리듬을 반복 연습함.'}],text:'합주에서 리듬을 반복 연습함.'});
if(!directPhoneEvidence.critical||directPhoneEvidence.evidenceCount!==0||!directPhoneEvidence.issues.some(x=>x.code==='NO_EVIDENCE'))throw new Error('direct phone number in evidence must invalidate that evidence');
const directEmailDraft=R.analyzeDraft({area:'subject',evidence:goodEvidence,text:'모둠 합주에 참여함. 연락은 student@example.com으로 함.'});
if(!directEmailDraft.critical||!directEmailDraft.issues.some(x=>x.code==='SENSITIVE'))throw new Error('direct email address in draft must be treated as sensitive');
const directRrnDraft=R.analyzeDraft({area:'subject',evidence:goodEvidence,text:'주민 식별값 060101-3123456을 기록함.'});
if(!directRrnDraft.critical||!directRrnDraft.issues.some(x=>x.code==='SENSITIVE'))throw new Error('resident-registration-shaped value in draft must be treated as sensitive');
const wrongArea=R.analyzeDraft({area:'subject',evidence:[{id:'s3',eligible:true,area:'career',kind:'진로활동',text:'음악 관련 진로를 조사하고 발표함.'}],text:'음악 관련 진로를 조사하고 발표함.'});
if(!wrongArea.critical||wrongArea.evidenceCount!==0)throw new Error('evidence moved to another record area must not support this draft');
const wrongKind=R.analyzeDraft({area:'subject',evidence:[{id:'s4',eligible:true,area:'subject',kind:'상담',text:'합주에서 반복 연습함.'}],text:'합주에서 반복 연습함.'});
if(!wrongKind.critical||wrongKind.evidenceCount!==0)throw new Error('non-observation record kinds must not count as school-record evidence');
const app=fs.readFileSync('app-v25.js','utf8'),css=fs.readFileSync('app-v25.css','utf8'),idx=fs.readFileSync('index.html','utf8'),lib=JSON.parse(fs.readFileSync('school-record-quality-library.json','utf8'));
for(const token of ['QUALITY GATE','현재 초안 품질검사','공식 기준 보기','합격 가능성 점수','qualityCheck','function saveMain25(){globalThis.TeacherOSStorage.writeJSON(KEY,state)}'])if(!app.includes(token))throw new Error('v25 app missing '+token);
if(/localStorage\.setItem\(KEY\s*,/.test(app))throw new Error('v0.25 quality snapshot must use shared TeacherOSStorage');
if(!css.includes('@media(max-width:780px)'))throw new Error('v25 mobile CSS missing');
if(!Array.isArray(lib.sources)||lib.sources.length<4)throw new Error('official quality source library too small');
if(!lib.sources.some(x=>x.authority==='rule'&&x.publisher==='교육부'))throw new Error('MOE rule source missing');
if(!idx.includes('core-v25.js')||!idx.includes('app-v25.js')||!idx.includes('app-v25.css'))throw new Error('v25 loader missing');
console.log('v0.25 grounded school-record quality tests passed with strict sentence, Korean particle, stale-evidence, and direct-PII checks');
