const assert=require('assert');
const P=require('../core-v28.js');
let n=0;const ok=(cond,msg)=>{assert.ok(cond,msg);n++};
ok(P.chosung('김하늘')==='ㄱㅎㄴ','Korean initial consonants');
ok(P.match('김하늘','ㄱㅎㄴ')===true,'chosung search match');
ok(P.match('박서준','ㄱㅎㄴ')===false,'chosung search mismatch');
ok(P.match('2학년 음악 수행평가','음악')===true,'normal substring search');
ok(P.neisBytes('가A\n')===5,'UTF-8 Korean/ASCII/newline byte count');
ok(P.neisBytes('😀')===4,'emoji UTF-8 byte count');
ok(P.limitFor(2026,'behavior').bytes===900,'2026 behavior byte limit');
ok(P.limitFor(2026,'subject').bytes===1500,'2026 subject byte limit');
ok(P.limitFor(2026,'career').bytes===1500,'2026 career byte limit');
ok(P.limitFor(2027,'subject')===null,'future year limits are not hard-coded');
ok(P.byteState('가'.repeat(301),2026,'behavior').over===true,'behavior over-limit guard');
ok(P.byteState('가'.repeat(300),2026,'behavior').over===false,'behavior exact limit accepted');
const fs=require('fs');
const app=fs.readFileSync(require('path').join(__dirname,'../app-v28.js'),'utf8');
ok(app.includes('myTeacherOS.calendarEditHistory.v1'),'calendar edit history local key');
ok(app.includes('myTeacherOS.staffContacts.v1'),'local staff contact search');
ok(app.includes('data-v28-contact'),'contact search result hook');
ok(app.includes('NEIS 입력 한도를 초과했습니다'),'NEIS save block warning');
ok(app.includes("ev.target?.id!=='eventEditForm'"),'calendar edit capture');
ok(app.includes('해당 연도 공식 한도 확인 필요'),'unknown year safety label');
console.log(`v0.28 precision UX tests passed (${n} assertions)`);
