const assert=require('assert');
const T=require('../core-v29.js');
let n=0;const ok=(v,m)=>{assert.ok(v,m);n++};
ok(T.nextLessonTruth({}, {status:'none',live:false,slot:null}).known===false,'no source is unknown');
ok(T.nextLessonTruth({comciganSync:{status:'waiting'}},{status:'none',live:false,slot:null}).label==='컴시간 최신표 미확인','waiting label');
ok(T.nextLessonTruth({comciganSync:{status:'mismatch'}},{status:'none',live:false,slot:null}).label==='컴시간 설정 불일치','mismatch label');
ok(T.nextLessonTruth({comciganSync:{status:'collector-error'}},{status:'none',live:false,slot:null}).label==='컴시간 수집 오류','collector error label');
ok(T.nextLessonTruth({comciganSync:{status:'collector-error'}},{status:'none',live:true,slot:null}).known===false,'collector error overrides stale live-week certainty');
ok(T.nextLessonTruth({timetable:[{day:'월',period:1}]},{status:'none',live:false,slot:null}).known===true,'basic timetable makes zero-day result interpretable');
ok(T.nextLessonTruth({}, {status:'none',live:true,slot:null}).known===true,'live week with zero slots is confirmed zero');
ok(T.nextLessonTruth({}, {status:'done',live:false,slot:null}).known===true,'completed day is known');
const fs=require('fs'),p=require('path');const app=fs.readFileSync(p.join(__dirname,'../app-v29.js'),'utf8');
ok(app.includes('오늘 수업 여부를 확정할 수 없습니다.'),'unknown-state copy');
ok(app.includes('0건으로 처리하지 않습니다.'),'zero-vs-unknown guard copy');
ok(app.includes('correctTodayTimetableTruth'),'legacy today timetable is truth-guarded');
ok(app.includes('수업 없음으로 처리하지 않습니다.'),'today timetable does not claim zero before verification');
ok(app.includes('./live/comcigan-status.json'),'sanitized collector status is checked');
ok(app.includes("status='collector-error'"),'collector failure is persisted as an explicit truth state');
ok(app.includes('이전 표를 현재표로 간주하지 않습니다.'),'stale live data is not presented as current after collector failure');
ok(app.includes('TeacherOSStorage'),'v1 collector truth state uses shared storage service');
ok(app.includes('S?.writeJSON(KEY,state)'),'v1 collector truth state writes through shared storage boundary');
ok(!app.includes('localStorage.setItem(KEY'),'v1 collector truth state must not bypass storage service');
ok(app.includes('COLLECTOR_STATE_PERSIST_MS29=60000'),'collector truth persistence is rate-limited without delaying fetch freshness');
ok(app.includes('changed=')&&app.includes('due=')&&app.includes('if(!changed&&!due)return'),'unchanged collector errors skip redundant whole-state writes');
console.log(`v0.29 data truth tests passed (${n} assertions)`);
