const assert=require('assert');
const V=require('../core-v30.js');
let n=0;const ok=(v,m)=>{assert.ok(v,m);n++};
ok(V.familyKey('2026학년도 2학기 평가계획.hwp')===V.familyKey('2026학년도 2학기 평가계획(수정).hwp'),'revision marker keeps same family');
ok(V.familyKey('2026학년도 학사일정 v2.xlsx')===V.familyKey('2026학년도 학사일정 v1.xlsx'),'explicit versions keep same family');
let a=V.meta('2026학년도 평가계획 v2.hwp',{docClass:'assessment'}),b=V.meta('2026학년도 평가계획 v1.hwp',{docClass:'assessment'});ok(V.compare(a,b).relation==='newer','v2 newer than v1');
a=V.meta('2026학년도 평가계획(수정).hwp',{docClass:'assessment'});b=V.meta('2026학년도 평가계획.hwp',{docClass:'assessment'});ok(V.compare(a,b).relation==='newer','revision marker newer than base');
a=V.meta('2026학년도 평가계획.hwp',{hash:'new',docClass:'assessment'});b=V.meta('2026학년도 평가계획.hwp',{hash:'old',docClass:'assessment'});ok(V.compare(a,b).relation==='ambiguous','same filename changed content is not blindly newer');
a=V.meta('2026학년도 평가계획.hwp',{hash:'same',docClass:'assessment'});b=V.meta('2026학년도 평가계획.hwp',{hash:'same',docClass:'assessment'});ok(V.compare(a,b).relation==='duplicate','same hash duplicate');
a=V.meta('2026학년도 평가계획 v1.hwp',{docClass:'assessment'});b=V.meta('2026학년도 평가계획 v2.hwp',{docClass:'assessment'});ok(V.compare(a,b).relation==='older','older explicit version rejected');
ok(V.compare(V.meta('평가계획.hwp',{docClass:'assessment'}),V.meta('업무분장.hwp',{docClass:'admin'})).relation==='unrelated','different families unrelated');
const fs=require('fs'),path=require('path'),app=fs.readFileSync(path.join(__dirname,'../app-v30.js'),'utf8'),css=fs.readFileSync(path.join(__dirname,'../app-v30.css'),'utf8');
ok(app.includes('새 파일을 최신본으로 사용'),'explicit new version choice exists');
ok(app.includes('기존 파일 유지'),'explicit existing version choice exists');
ok(app.includes('원본 파일은 Teacher OS에 장기 보관하지 않습니다'),'raw source retention policy exists');
ok(app.includes("input.value=''"),'file input released after analysis');
ok(app.includes('myTeacherOS.importVersionHistory.v1'),'replacement undo history exists');
ok(app.includes("AUTO_CLASSES=new Set(['calendar','timetable','live','assessment','admin','club'])"),'auto replacement limited to structured document classes');
ok(css.includes('@media(max-width:680px)'),'mobile version review UI');
console.log(`v0.30 document version tests passed (${n} assertions)`);