const assert=require('assert');
const R=require('../core-v31.js');
let n=0;const ok=(v,m)=>{assert.ok(v,m);n++};
ok(R.defaultLevel('assessment')==='reference','assessment defaults to reference metadata');
ok(R.defaultLevel('calendar')==='reference','calendar defaults to reference metadata');
ok(R.defaultLevel('schoolplan')==='reference','school plan defaults to reference metadata');
ok(R.defaultLevel('student')==='transient','student source original not retained by default');
ok(R.defaultLevel('unknown')==='transient','unknown source original not retained by default');
ok(R.resolveLevel('auto','admin')==='reference','auto resolves important class');
ok(R.resolveLevel('local','student')==='local','explicit local retention allowed');
ok(R.resolveLevel('bad','admin')==='transient','invalid explicit level fails to transient');
ok(R.formatBytes(1024).includes('KB'),'byte formatter');
ok(R.canStoreOriginal(5,{quota:100,usage:0},10).ok===true,'storage quota permits safe file');
ok(R.canStoreOriginal(95,{quota:100,usage:0},10).ok===false,'storage reserve prevents overfill');
const rec=R.retentionRecord('reference',{sourceLocation:'교무공유 > 평가',originalStored:true,vaultKey:'x'});ok(rec.retentionLevel==='reference'&&rec.originalStored===false&&rec.vaultKey==='','reference never claims original blob');
const local=R.retentionRecord('local',{sourceLocation:'학교폴더',originalStored:true,vaultKey:'hash'});ok(local.originalStored===true&&local.vaultKey==='hash','local retention records vault key');
const fs=require('fs'),path=require('path'),app=fs.readFileSync(path.join(__dirname,'../app-v31.js'),'utf8'),css=fs.readFileSync(path.join(__dirname,'../app-v31.css'),'utf8');
ok(app.includes("DB_NAME='myTeacherOS.sourceVault'"),'private IndexedDB vault');
ok(app.includes('navigator.storage?.estimate'),'quota estimate used before local original storage');
ok(app.includes('navigator.storage.persist'),'persistent storage request supported');
ok(app.includes('JSON 백업에도 원본 Blob은 포함하지 않습니다'),'raw blob excluded from JSON backup warning');
ok(app.includes('원본 미보관 · 분석 후 해제'),'transient option visible');
ok(app.includes('출처·해시·버전만 보관'),'reference option visible');
ok(app.includes('이 기기에 원본도 보관'),'local original option visible');
ok(app.includes('원본 위치 메모'),'source location metadata input');
ok(app.includes('로컬 원본 전체 삭제'),'local vault purge control');
ok(app.includes('출처·해시·버전 이력은 유지됩니다'),'single raw deletion preserves lineage');
ok(!app.includes('fetch('),'retention layer has no network upload');
ok(css.includes('@media(max-width:680px)'),'mobile retention UI');
console.log(`v0.31 source retention tests passed (${n} assertions)`);
