const assert=require('assert'),fs=require('fs'),path=require('path');
const app=fs.readFileSync(path.join(__dirname,'../app-v32.js'),'utf8'),css=fs.readFileSync(path.join(__dirname,'../app-v32.css'),'utf8');
let n=0;const ok=(v,m)=>{assert.ok(v,m);n++};
ok(app.includes("DB_NAME='myTeacherOS.sourceVault'"),'uses same local vault database as retention layer');
ok(app.includes("RESULT_KEY='myTeacherOS.deviceStorageSelfTest.v1'"),'stores per-device self-test result');
ok(app.includes('objectStore(STORE).put(record)'),'writes synthetic test file');
ok(app.includes('objectStore(STORE).get(key)'),'reads synthetic test file back');
ok(app.includes('restored!==payload||restoredDigest!==digest'),'verifies byte/content integrity');
ok(app.includes('objectStore(STORE).delete(key)'),'deletes synthetic test file');
ok(app.includes("const after=await getRecord(db,key);if(after)"),'verifies deletion');
ok(app.includes("function freshPass(r)"),'fresh pass helper exists');
ok(app.includes("r?.ok===true&&age>=0&&age<=DAY"),'passed result must also be recent and not future-dated');
ok(app.includes("const passed=freshPass(r)"),'local retention guard uses fresh pass, not stale success');
ok(app.includes("opt.disabled=!passed"),'local raw retention blocked until current real-device test passes');
ok(app.includes("select.value='reference'"),'failed or stale test falls back to reference retention');
ok(app.includes("if(!freshPass(r))"),'auto-tests unverified, failed, stale, or malformed device state');
ok(app.includes('24시간 유효기간이 지났습니다'),'stale success is visibly distinguished from current pass');
ok(app.includes('IndexedDB 쓰기·읽기·무결성·삭제 통과'),'visible successful device result');
ok(app.includes('안전하게 출처·버전 보관으로 사용합니다'),'visible safe fallback on failure');
ok(app.includes("input.accept='.hwpx,.pdf,.xlsx,.xls,.csv,.txt,.docx,.pptx,.ics,.jpg,.jpeg,.png,.webp,.bmp'"),'legacy HWP is not advertised as directly supported');
ok(app.includes("/\\.hwp$/i"),'legacy HWP selection is explicitly detected');
ok(app.includes('구형 HWP는 아직 직접 분석하지 않습니다'),'legacy HWP failure is truthful and actionable');
ok(app.includes('HWPX 또는 PDF로 저장한 뒤 다시 올려 주세요'),'legacy HWP tells user the safe conversion path');
ok(!app.includes('fetch('),'device self-test has no network upload');
ok(css.includes('@media(max-width:680px)'),'mobile self-test UI');
console.log(`v0.32 real-device storage self-test checks passed (${n} assertions)`);
