const assert=require('assert');
const A=require('../autonomous-core-v40.js');
const now=new Date(2026,7,30,9,0,0);
assert.strictEqual(A.dueDays('2026-08-30',now),0);
assert.strictEqual(A.dueDays('2026-09-01',now),2);
assert.strictEqual(A.domain('2학년 수행평가 계획'),'assessment');
assert.strictEqual(A.domain('K-에듀파인 결재 점검'),'admin');
const overdue={id:'we1',title:'수행평가 계획 제출',due:'2026-08-29',sourceCount:3,completed:false,dueConflict:false};
const today={id:'we2',title:'공문 제출',due:'2026-08-30',sourceCount:2,completed:false,dueConflict:false};
const conflict={id:'we3',title:'평가계획',due:'2026-09-01',sourceCount:2,completed:false,dueConflict:true};
const later={id:'we4',title:'연수 참가',due:'2026-09-20',sourceCount:1,completed:false,dueConflict:false};
const year={workEntities39:[later,today,conflict,overdue],tasks:[]};
const plan=A.buildPlan(year,{now,desktopConfigured:true,desktopConnected:false,neisConfigured:true,neisHealthy:true,googleConfigured:false});
assert(plan.actions.length>=5);
const urgentIds=plan.actions.slice(0,3).map(x=>x.entityId);
assert(urgentIds.includes('we1'));
assert(urgentIds.includes('we3'));
assert(plan.actions.find(x=>x.entityId==='we3').score>plan.actions.find(x=>x.entityId==='we4').score);
assert(plan.summary.critical>=3);
assert(plan.summary.autoSafe>=2);
assert(plan.summary.approvalOnly>=2);
const c=A.safeTaskCandidates(plan,[],4);
assert(c.some(x=>x.sourceEntityId==='we1'));
assert(c.some(x=>x.sourceEntityId==='we2'));
assert(!c.some(x=>x.sourceEntityId==='we3'));
const again=A.safeTaskCandidates(plan,c,4);
assert.strictEqual(again.length,0);
assert.strictEqual(A.highRiskType('neis_score_write'),true);
assert.strictEqual(A.highRiskType('kedufine_approve'),true);
assert.strictEqual(A.mayAutoExecute({type:'task_add'}),true);
assert.strictEqual(A.mayAutoExecute({type:'gmail_send'}),false);
assert.strictEqual(A.mayAutoExecute({type:'finance_execute'}),false);
console.log('v40 autonomous teacher agent tests passed');
