const assert=require('assert');
const S=require('../supervisor-core-v41.js');
const now=new Date('2026-08-30T10:00:00Z');
assert.strictEqual(S.retryDelayMs(0),15*60*1000);
assert.strictEqual(S.retryDelayMs(1),30*60*1000);
assert(S.retryDelayMs(10)<=6*60*60*1000);
const ctx={desktopConfigured:true,desktopConnected:false,desktopError:'connection refused',neisConfigured:true,neisHealthy:true,googleConfigured:true,googleConnected:false,googleError:'timeout'};
let p=S.plan(ctx,S.emptyState(),now);
assert.strictEqual(p.summary.configured,3);
assert.strictEqual(p.summary.healthy,1);
assert.strictEqual(p.summary.unhealthy,2);
assert.strictEqual(p.actions[0].type,'desktop_rescan');
assert(p.actions.some(x=>x.type==='google_repair'));
assert(!p.actions.some(x=>x.type==='neis_sync'));
assert(p.actions.every(S.mayAutoExecute));
let state=S.recordAttempt(p.state,p.actions[0],now);
assert.strictEqual(state.sources.desktop.attempts,1);
p=S.plan(ctx,state,new Date('2026-08-30T10:05:00Z'));
assert(!p.actions.some(x=>x.source==='desktop'));
p=S.plan(ctx,state,new Date('2026-08-30T10:16:00Z'));
assert(p.actions.some(x=>x.source==='desktop'));
const healthy={...ctx,desktopConnected:true,desktopError:'',googleConnected:true,googleError:''};
p=S.plan(healthy,state,new Date('2026-08-30T10:20:00Z'));
assert.strictEqual(p.summary.unhealthy,0);
assert.strictEqual(p.state.sources.desktop.attempts,0);
assert.strictEqual(S.mayAutoExecute({type:'gmail_send',safe:true}),false);
assert.strictEqual(S.mayAutoExecute({type:'kedufine_approve',safe:true}),false);
console.log('v41 autonomous supervisor tests passed');
