const assert=require('assert');
const fs=require('fs');
const vm=require('vm');
const path=require('path');
const root=path.join(__dirname,'..');
const gs=fs.readFileSync(path.join(root,'backend/apps-script/Code.gs'),'utf8');
const ctx={console};vm.createContext(ctx);vm.runInContext(gs,ctx);
assert.strictEqual(typeof ctx.pageItems_,'function');
const items=Array.from({length:600},(_,i)=>({seq:i+1,id:`x${i+1}`}));
let p=ctx.pageItems_(items,0,250);
assert.strictEqual(p.items.length,250);
assert.strictEqual(p.items[0].seq,1);
assert.strictEqual(p.items[249].seq,250);
assert.strictEqual(p.cursor,250);
assert.strictEqual(p.hasMore,true);
assert.strictEqual(p.remaining,350);
p=ctx.pageItems_(items,p.cursor,250);
assert.strictEqual(p.items[0].seq,251);
assert.strictEqual(p.items[249].seq,500);
assert.strictEqual(p.cursor,500);
assert.strictEqual(p.hasMore,true);
p=ctx.pageItems_(items,p.cursor,250);
assert.strictEqual(p.items.length,100);
assert.strictEqual(p.items[0].seq,501);
assert.strictEqual(p.items[99].seq,600);
assert.strictEqual(p.cursor,600);
assert.strictEqual(p.hasMore,false);
assert.strictEqual(p.remaining,0);
const shuffled=[{seq:12},{seq:9},{seq:11},{seq:10}];
p=ctx.pageItems_(shuffled,9,2);
assert.deepStrictEqual(Array.from(p.items,x=>x.seq),[10,11]);
assert.strictEqual(p.cursor,11);
assert.strictEqual(p.hasMore,true);
assert(gs.includes('MAX_ITEMS: 2000'));
assert(gs.includes('PAGE_SIZE: 250'));
assert(gs.includes('const page = pageItems_(state.items || [], cursor, TOS34.PAGE_SIZE)'));
assert(!gs.includes("filter(x => Number(x.seq || 0) > n).slice(-250)"));
const app=fs.readFileSync(path.join(root,'app-v34.js'),'utf8');
assert(app.includes('fetchSnapshotPages(cursor,5)'));
assert(app.includes('pagesFetched'));
assert(app.includes("if(next<=before)throw new Error('Google 동기화 페이지 cursor가 진행되지 않습니다.')"));
assert(app.includes('lastSnapshot?.hasMore'));
assert(app.includes('timer=setTimeout(()=>syncNow(false),10000)'));
console.log('v42 lossless Google sync tests passed');
